use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::types::{
    Color, CommonDefinition, DateDef, DateDefExceptions, MartyrologyItemPointer, Precedence,
    TitlesDef,
};

// Type aliases
pub type DayId = String;
pub type LocaleId = String;

// Macro to generate SingleOrMultiple types
macro_rules! single_or_multiple {
    ($name:ident, $type:ty) => {
        #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
        #[serde(untagged)]
        pub enum $name {
            Single($type),
            Multiple(Vec<$type>),
        }
    };
}

single_or_multiple!(CommonsDef, CommonDefinition);
single_or_multiple!(ColorsDef, Color);

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct DayDefinition {
    pub id: DayId,
    /// Date definition
    pub date_def: Option<DateDef>,
    /// Date definition exception
    pub date_exceptions: Option<DateDefExceptions>,
    /// The precedence type of the liturgical day.
    pub precedence: Option<Precedence>,
    /// The **Common** refers to a set of prayers, readings, and chants used for celebrating saints or
    /// feasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed
    /// Virgin Mary.
    pub commons_def: Option<CommonsDef>,
    /// Holy days of obligation are days on which the faithful are expected to attend Mass,
    /// and engage in rest from work and recreation.
    pub is_holy_day_of_obligation: Option<bool>,
    /// In addition to this liturgical day, allow similar items that have the same rank,
    /// and the same or lower precedence,
    /// so the current liturgical day will not overwrite another defined item.
    pub allow_similar_rank_items: Option<bool>,
    /// Specify is this LiturgicalDay is optional within a specific liturgical calendar.
    ///
    /// UNLY #14:
    /// Memorials are either obligatory or optional; their observance is integrated into
    /// the celebration of the occurring weekday in accordance with the norms set forth in the
    /// General Instruction of the Roman Missal and of the Liturgy of the Hours
    ///
    /// Note: also used for the dedication of consecrated churches, which is an optional solemnity
    /// that should not overwrite the default weekday.
    pub is_optional: Option<bool>,
    /// Specify a custom locale ID for this date definition, in this calendar.
    pub custom_locale_id: Option<LocaleId>,
    /// Link one or multiple Saints, Blessed, or any other celebrations from the Martyrology catalog.
    pub martyrology: Option<Vec<MartyrologyItemPointer>>,
    /// Combined titles of each Saints linked to this date definition.
    pub titles: Option<TitlesDef>,
    /// If this liturgical day must be removed from this calendar and from all those it inherits
    /// (the parent calendars), on the final calendar generated by romcal.
    pub drop: Option<bool>,
    /// The liturgical color(s) of the liturgical day.
    /// @deprecated
    pub colors: Option<ColorsDef>,
}
