/*
 Generated by typeshare 1.13.4
 */

import Foundation

/// Unique identifier for a calendar
public typealias CalendarId = String

/// Unique identifier for a day definition
public typealias DayId = String

/// Day of week (0-6, where 0=Sunday) with automatic validation
/// 
/// This type ensures that only valid day-of-week values are accepted during
/// deserialization. The value 0 represents Sunday, 1 represents Monday, etc.
public typealias DayOfWeek = UInt8

/// The unique identifier of the entity
public typealias EntityId = String

/// Unique identifier for a liturgical day
public typealias LiturgicalDayId = String

/// Locale code of the resources, in BCP-47 IETF tag format
public typealias LocaleId = String

/// Content of a mass for a specific liturgical cycle
/// Maps mass parts (readings, psalms, prayers, antiphons, etc.) to their texts
public typealias MassContent = BTreeMap<MassPart, String>

/// Mass contents for a specific mass time, organized by liturgical cycle
public typealias MassCycleDefinition = BTreeMap<LiturgicalCycle, MassContent>

/// All mass definitions for a liturgical day
public typealias MassesDefinitions = BTreeMap<MassTime, MassCycleDefinition>

/// Month index (1-12) with automatic validation
/// 
/// This type ensures that only valid month values are accepted during
/// deserialization. The value 1 represents January, 2 represents February, etc.
public typealias MonthIndex = UInt8

/// Advent season localized names and descriptions.
/// Provides specific terminology for the Advent season in the locale language.
public struct AdventSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Advent
	public let season: String?
	/// Weekday terminology during Advent
	public let weekday: String?
	/// Sunday terminology during Advent
	public let sunday: String?
	/// Privileged weekday terminology during Advent
	public let privileged_weekday: String?

	public init(season: String?, weekday: String?, sunday: String?, privileged_weekday: String?) {
		self.season = season
		self.weekday = weekday
		self.sunday = sunday
		self.privileged_weekday = privileged_weekday
	}
}

/// The type of the calendar.
/// Defines the scope and authority level of the liturgical calendar.
public enum CalendarType: String, Codable, Equatable, Hashable, Sendable {
	/// General Roman Calendar (universal)
	case generalRoman = "GENERAL_ROMAN"
	/// Regional calendar (multiple countries)
	case region = "REGION"
	/// National calendar (single country)
	case country = "COUNTRY"
	/// Archdiocesan calendar
	case archdiocese = "ARCHDIOCESE"
	/// Diocesan calendar
	case diocese = "DIOCESE"
	/// City calendar
	case city = "CITY"
	/// Parish calendar
	case parish = "PARISH"
	/// General religious community calendar
	case generalCommunity = "GENERAL_COMMUNITY"
	/// Regional religious community calendar
	case regionalCommunity = "REGIONAL_COMMUNITY"
	/// Local religious community calendar
	case localCommunity = "LOCAL_COMMUNITY"
	/// Other specialized calendar
	case other = "OTHER"
}

/// The jurisdiction of the calendar.
/// Determines whether the calendar follows ecclesiastical or civil authority.
public enum CalendarJurisdiction: String, Codable, Equatable, Hashable, Sendable {
	/// Calendar under ecclesiastical authority (Church)
	case ecclesiastical = "ECCLESIASTICAL"
	/// Calendar under civil authority (State)
	case civil = "CIVIL"
}

/// Metadata for a calendar.
/// Contains essential information about the calendar's type and jurisdiction.
public struct CalendarMetadata: Codable, Equatable, Hashable, Sendable {
	/// The type of the calendar
	public let type: CalendarType
	/// The jurisdiction of the calendar
	public let jurisdiction: CalendarJurisdiction

	public init(type: CalendarType, jurisdiction: CalendarJurisdiction) {
		self.type = type
		self.jurisdiction = jurisdiction
	}
}

/// Easter date calculation method.
/// 
/// Determines which algorithm to use for calculating the date of Easter Sunday,
/// which is the basis for most movable feasts in the liturgical calendar.
public enum EasterCalculationType: String, Codable, Equatable, Hashable, Sendable {
	/// Gregorian calculation (default)
	case gregorian = "GREGORIAN"
	/// Julian calculation converted to Gregorian
	case julian = "JULIAN"
}

/// Configuration options for "particular" (local/diocesan) calendars.
/// 
/// In liturgical terminology, a "particular" calendar is one that applies to a specific
/// region, diocese, or religious community, as opposed to the General Roman Calendar
/// which applies universally.
/// 
/// These settings can override or extend the default Romcal configuration or any parent
/// calendar configuration.
public struct ParticularConfig: Codable, Equatable, Hashable, Sendable {
	/// Epiphany is celebrated on a Sunday
	public let epiphany_on_sunday: Bool?
	/// Ascension is celebrated on a Sunday
	public let ascension_on_sunday: Bool?
	/// Corpus Christi is celebrated on a Sunday
	public let corpus_christi_on_sunday: Bool?
	/// The type of Easter calculation
	public let easter_calculation_type: EasterCalculationType?

	public init(epiphany_on_sunday: Bool?, ascension_on_sunday: Bool?, corpus_christi_on_sunday: Bool?, easter_calculation_type: EasterCalculationType?) {
		self.epiphany_on_sunday = epiphany_on_sunday
		self.ascension_on_sunday = ascension_on_sunday
		self.corpus_christi_on_sunday = corpus_christi_on_sunday
		self.easter_calculation_type = easter_calculation_type
	}
}

/// Calendar definition
public struct CalendarDefinition: Codable, Equatable, Hashable, Sendable {
	public let id: CalendarId
	public let metadata: CalendarMetadata
	public let particular_config: ParticularConfig?
	public let parent_calendar_ids: [CalendarId]
	public let days_definitions: BTreeMap<DayId, DayDefinition>

	public init(id: CalendarId, metadata: CalendarMetadata, particular_config: ParticularConfig?, parent_calendar_ids: [CalendarId], days_definitions: BTreeMap<DayId, DayDefinition>) {
		self.id = id
		self.metadata = metadata
		self.particular_config = particular_config
		self.parent_calendar_ids = parent_calendar_ids
		self.days_definitions = days_definitions
	}
}

/// Liturgical precedence levels for determining which celebration takes priority.
/// Defines the hierarchical order of liturgical celebrations according to UNLY norms.
public enum Precedence: String, Codable, Equatable, Hashable, Sendable {
	/// 1 - The Paschal Triduum of the Passion and Resurrection of the Lord.
	case triduum1 = "TRIDUUM_1"
	/// 2 - The Nativity of the Lord, the Epiphany, the Ascension, or Pentecost.
	case properOfTimeSolemnity2 = "PROPER_OF_TIME_SOLEMNITY_2"
	/// 2 - A Sunday of Advent, Lent, or Easter.
	case privilegedSunday2 = "PRIVILEGED_SUNDAY_2"
	/// 2 - Ash Wednesday.
	case ashWednesday2 = "ASH_WEDNESDAY_2"
	/// 2 - A weekday of Holy Week from Monday up to and including Thursday.
	case weekdayOfHolyWeek2 = "WEEKDAY_OF_HOLY_WEEK_2"
	/// 2 - A day within the Octave of Easter.
	case weekdayOfEasterOctave2 = "WEEKDAY_OF_EASTER_OCTAVE_2"
	/// 3 - A Solemnity inscribed in the General Calendar, whether of the Lord, of the Blessed Virgin Mary, or of a Saint.
	case generalSolemnity3 = "GENERAL_SOLEMNITY_3"
	/// 3 - The Commemoration of All the Faithful Departed.
	case commemorationOfAllTheFaithfulDeparted3 = "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3"
	/// 4a - A proper Solemnity of the principal Patron of the place, city, or state.
	case properSolemnityPrincipalPatron4a = "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A"
	/// 4b - The Solemnity of the dedication and of the anniversary of the dedication of the own church.
	case properSolemnityDedicationOfTheOwnChurch4b = "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B"
	/// 4c - The solemnity of the title of the own church.
	case properSolemnityTitleOfTheOwnChurch4c = "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C"
	/// 4d - A Solemnity either of the Title or of the Founder or of the principal Patron of an Order or Congregation.
	case properSolemnityTitleOrFounderOrPrimaryPatronOfAReligiousOrg4d = "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D"
	/// 5 - A Feast of the Lord inscribed in the General Calendar.
	case generalLordFeast5 = "GENERAL_LORD_FEAST_5"
	/// 6 - A Sunday of Christmas Time or a Sunday in Ordinary Time.
	case unprivilegedSunday6 = "UNPRIVILEGED_SUNDAY_6"
	/// 7 - A Feast of the Blessed Virgin Mary or of a Saint in the General Calendar.
	case generalFeast7 = "GENERAL_FEAST_7"
	/// 8a - The Proper Feast of the principal Patron of the diocese.
	case properFeastPrincipalPatronOfADiocese8a = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A"
	/// 8b - The Proper Feast of the anniversary of the dedication of the cathedral church.
	case properFeastDedicationOfTheCathedralChurch8b = "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B"
	/// 8c - The Proper Feast of the principal Patron of a region or province, or a country, or of a wider territory.
	case properFeastPrincipalPatronOfARegion8c = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C"
	/// 8d - The Proper Feast of the Title, Founder, or principal Patron of an Order or Congregation.
	case properFeastTitleOrFounderOrPrimaryPatronOfAReligiousOrg8d = "PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D"
	/// 8e - Other Feast, proper to an individual church.
	case properFeastToAnIndividualChurch8e = "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E"
	/// 8f - Other Proper Feast inscribed in the Calendar of each diocese or Order or Congregation.
	case properFeast8f = "PROPER_FEAST_8F"
	/// 9 - Privileged Weekday.
	case privilegedWeekday9 = "PRIVILEGED_WEEKDAY_9"
	/// 10 - Obligatory Memorials in the General Calendar.
	case generalMemorial10 = "GENERAL_MEMORIAL_10"
	/// 11a - Proper Obligatory Memorial of a secondary Patron of the place, diocese, region, or religious province.
	case properMemorialSecondPatron11a = "PROPER_MEMORIAL__SECOND_PATRON_11A"
	/// 11b - Other Proper Obligatory Memorial inscribed in the Calendar of each diocese, or Order or congregation.
	case properMemorial11b = "PROPER_MEMORIAL_11B"
	/// 12 - Optional Memorial.
	case optionalMemorial12 = "OPTIONAL_MEMORIAL_12"
	/// 13 - Weekday.
	case weekday13 = "WEEKDAY_13"
}

/// Liturgical rank indicating the importance and celebration style of a liturgical day
public enum Rank: String, Codable, Equatable, Hashable, Sendable {
	/// Solemnities are counted among the most important days, whose celebration
	/// begins with First Vespers (Evening Prayer I) on the preceding day. Some Solemnities
	/// are also endowed with their own Vigil Mass, which is to be used on the evening of the
	/// preceding day, if an evening Mass is celebrated. (UNLY #11)
	case solemnity = "SOLEMNITY"
	/// On the first day of each week, which is known as the Day of the Lord or the Lord's
	/// Day, the Church, by an apostolic tradition that draws its origin from the very day of
	/// the Resurrection of Christ, celebrates the Paschal Mystery. Hence, Sunday must be
	/// considered the primordial feast day. (UNLY #4)
	case sunday = "SUNDAY"
	/// Feasts are celebrated within the limits of the natural day; accordingly they have
	/// no First Vespers (Evening Prayer I), except in the case of Feasts of the Lord that fall
	/// on a Sunday in Ordinary Time or in Christmas Time and which replace the Sunday
	/// Office. (UNLY #13)
	case feast = "FEAST"
	/// **Obligatory memorials** are liturgical commemorations of saints, events, or aspects of the
	/// faith. Their observance is mandatory and integrated into the celebration of the occurring
	/// weekday, following the liturgical norms outlined in the General Instruction of the Roman Missal
	/// and the Liturgy of the Hours.
	/// When an **obligatory memorial** falls on a weekday during the liturgical season of Lent or a
	/// privileged weekday of Advent, it must only be celebrated as an **optional memorial**, as Lent
	/// and Advent have their own specific liturgical observances that take precedence.
	case memorial = "MEMORIAL"
	/// **Optional memorials** are liturgical commemorations of saints, events, or aspects of the
	/// faith, but they are not obligatory.
	/// Their observance is integrated into the celebration of the occurring weekday, adhering to the
	/// liturgical norms provided in the General Instruction of the Roman Missal and the Liturgy of
	/// the Hours.
	/// In cases where multiple **optional memorials** are designated on the same day in the liturgical
	/// calendar, only one of them may be celebrated, and the others must be omitted (UNLY #14).
	/// This allows for some flexibility in choosing which optional memorial to commemorate when
	/// multiple options are available.
	case optionalMemorial = "OPTIONAL_MEMORIAL"
	/// The days of the week that follow Sunday are called weekdays; however, they are
	/// celebrated differently according to the importance of each.
	/// 
	/// a. Ash Wednesday and the weekdays of Holy Week, from Monday up to and including
	/// Thursday, take precedence over all other celebrations.
	/// b. The weekdays of Advent from 17 December up to and including 24 December
	/// and all the weekdays of Lent have precedence over Obligatory Memorials.
	/// c. Other weekdays give way to all Solemnities and Feasts and are combined with
	/// Memorials.
	/// 
	/// (UNLY #16)
	case weekday = "WEEKDAY"
}

/// Liturgical colors used in the celebration of Mass and other liturgical services.
/// Each color has specific liturgical significance and is used during particular seasons or celebrations.
public enum Color: String, Codable, Equatable, Hashable, Sendable {
	/// Red - used for martyrs, Pentecost, and Palm Sunday
	case red = "RED"
	/// Rose - used on Gaudete Sunday (3rd Advent) and Laetare Sunday (4th Lent)
	case rose = "ROSE"
	/// Purple - used during Advent and Lent
	case purple = "PURPLE"
	/// Green - used during Ordinary Time
	case green = "GREEN"
	/// White - used for Christmas, Easter, and most feasts
	case white = "WHITE"
	/// Gold - used for solemn celebrations and special occasions
	case gold = "GOLD"
	/// Black - used for funerals and All Souls' Day
	case black = "BLACK"
}

/// Liturgical color information with localized name.
public struct ColorInfo: Codable, Equatable, Hashable, Sendable {
	/// The color key
	public let key: Color
	/// The localized name of the color
	public let name: String

	public init(key: Color, name: String) {
		self.key = key
		self.name = name
	}
}

/// Common prayers and readings for different categories of saints and celebrations.
/// Provides standardized liturgical texts for various types of commemorations.
public enum Common: String, Codable, Equatable, Hashable, Sendable {
	/// No common.
	case none = "NONE"
	/// Dedication anniversary (in the Church that was Dedicated).
	case dedicationAnniversaryInside = "DEDICATION_ANNIVERSARY__INSIDE"
	/// Dedication anniversary (outside the Church that was Dedicated).
	case dedicationAnniversaryOutside = "DEDICATION_ANNIVERSARY__OUTSIDE"
	/// Common of the Blessed Virgin Mary (Ordinary Time).
	case blessedVirginMaryOrdinaryTime = "BLESSED_VIRGIN_MARY__ORDINARY_TIME"
	/// Common of the Blessed Virgin Mary (Advent).
	case blessedVirginMaryAdvent = "BLESSED_VIRGIN_MARY__ADVENT"
	/// Common of the Blessed Virgin Mary (Christmas Time).
	case blessedVirginMaryChristmas = "BLESSED_VIRGIN_MARY__CHRISTMAS"
	/// Common of the Blessed Virgin Mary (Easter Time).
	case blessedVirginMaryEaster = "BLESSED_VIRGIN_MARY__EASTER"
	/// Common of Several Martyrs (outside Easter).
	case martyrsOutsideEasterSeveral = "MARTYRS__OUTSIDE_EASTER__SEVERAL"
	/// Common of One Martyr (outside Easter).
	case martyrsOutsideEasterOne = "MARTYRS__OUTSIDE_EASTER__ONE"
	/// Common of Several Martyrs (Easter Time).
	case martyrsEasterSeveral = "MARTYRS__EASTER__SEVERAL"
	/// Common of One Martyr (Easter Time).
	case martyrsEasterOne = "MARTYRS__EASTER__ONE"
	/// Common for Several Missionary Martyrs.
	case martyrsMissionarySeveral = "MARTYRS__MISSIONARY__SEVERAL"
	/// Common for One Missionary Martyr.
	case martyrsMissionaryOne = "MARTYRS__MISSIONARY__ONE"
	/// Common for Virgin Martyrs.
	case martyrsVirgin = "MARTYRS__VIRGIN"
	/// Common for Holy Woman Martyrs.
	case martyrsWoman = "MARTYRS__WOMAN"
	/// Common for a Pope or for a Bishop
	case pastorsPopeOrBishop = "PASTORS__POPE_OR_BISHOP"
	/// Common for a Bishop
	case pastorsBishop = "PASTORS__BISHOP"
	/// Common for Several Pastors
	case pastorsSeveral = "PASTORS__SEVERAL"
	/// Common for One Pastor
	case pastorsOne = "PASTORS__ONE"
	/// Common for one Founder
	case pastorsFounderOne = "PASTORS__FOUNDER__ONE"
	/// Common for several Founders
	case pastorsFounderSeveral = "PASTORS__FOUNDER__SEVERAL"
	/// Common for Missionaries
	case pastorsMissionary = "PASTORS__MISSIONARY"
	/// Common for Doctors of the Church.
	case doctorsOfTheChurch = "DOCTORS_OF_THE_CHURCH"
	/// Common for Several Virgins
	case virginsSeveral = "VIRGINS__SEVERAL"
	/// Common for One Virgin
	case virginsOne = "VIRGINS__ONE"
	/// Common for Several Holy Men and Women
	case saintsAllSeveral = "SAINTS__ALL__SEVERAL"
	/// Common for One Holy Man or Woman
	case saintsAllOne = "SAINTS__ALL__ONE"
	/// Common for an Abbot
	case saintsAbbot = "SAINTS__ABBOT"
	/// Common for a Monk
	case saintMonk = "SAINT__MONK"
	/// Common for a Nun
	case saintsNun = "SAINTS__NUN"
	/// Common for Religious
	case saintsReligious = "SAINTS__RELIGIOUS"
	/// Common for Those Who Practiced Works of Mercy
	case saintsMercyWorks = "SAINTS__MERCY_WORKS"
	/// Common for Educators
	case saintsEducators = "SAINTS__EDUCATORS"
	/// Common for Holy Women
	case saintsHolyWomen = "SAINTS__HOLY_WOMEN"
}

/// Liturgical common information with localized name.
public struct CommonInfo: Codable, Equatable, Hashable, Sendable {
	/// The common key
	public let key: Common
	/// The localized name of the common
	public let name: String

	public init(key: Common, name: String) {
		self.key = key
		self.name = name
	}
}

/// The type of entity in the liturgical calendar.
/// Defines whether the entity represents a person, place, or event.
public enum EntityType: String, Codable, Equatable, Hashable, Sendable {
	/// A person (saint, blessed, or other individual)
	case person = "PERSON"
	/// A place (shrine, city, or geographical location)
	case place = "PLACE"
	/// An event (historical or liturgical occurrence)
	case event = "EVENT"
}

/// Canonization level indicating the official recognition status of a person.
/// Defines whether someone is beatified (Blessed) or canonized (Saint).
public enum CanonizationLevel: String, Codable, Equatable, Hashable, Sendable {
	/// Beatified person (Blessed) - first step toward sainthood
	case blessed = "BLESSED"
	/// Canonized person (Saint) - fully recognized as a saint
	case saint = "SAINT"
}

/// Titles and patronages associated with saints and blessed.
/// Represents the various ecclesiastical titles and patronages that can be assigned to entities.
public enum Title: String, Codable, Equatable, Hashable, Sendable {
	case abbess = "ABBESS"
	case abbot = "ABBOT"
	case apostle = "APOSTLE"
	case archangel = "ARCHANGEL"
	case bishop = "BISHOP"
	case deacon = "DEACON"
	case doctorOfTheChurch = "DOCTOR_OF_THE_CHURCH"
	case empress = "EMPRESS"
	case evangelist = "EVANGELIST"
	case firstBishop = "FIRST_BISHOP"
	case hermit = "HERMIT"
	case king = "KING"
	case martyr = "MARTYR"
	case missionary = "MISSIONARY"
	case monk = "MONK"
	case motherAndQueenOfChile = "MOTHER_AND_QUEEN_OF_CHILE"
	case parentsOfTheBlessedVirginMary = "PARENTS_OF_THE_BLESSED_VIRGIN_MARY"
	case pope = "POPE"
	case patriarch = "PATRIARCH"
	case pilgrim = "PILGRIM"
	case priest = "PRIEST"
	case prophet = "PROPHET"
	case protoMartyrOfOceania = "PROTO_MARTYR_OF_OCEANIA"
	case queen = "QUEEN"
	case queenOfPoland = "QUEEN_OF_POLAND"
	case religious = "RELIGIOUS"
	case slavicMissionary = "SLAVIC_MISSIONARY"
	case spouseOfTheBlessedVirginMary = "SPOUSE_OF_THE_BLESSED_VIRGIN_MARY"
	case theFirstMartyr = "THE_FIRST_MARTYR"
	case virgin = "VIRGIN"
	case copatronOfEurope = "COPATRON_OF_EUROPE"
	case copatronOfIreland = "COPATRON_OF_IRELAND"
	case copatronOfCanada = "COPATRON_OF_CANADA"
	case copatronessOfEurope = "COPATRONESS_OF_EUROPE"
	case copatronessOfFrance = "COPATRONESS_OF_FRANCE"
	case copatronessOfIreland = "COPATRONESS_OF_IRELAND"
	case copatronessOfItalyAndEurope = "COPATRONESS_OF_ITALY_AND_EUROPE"
	case copatronessOfThePhilippines = "COPATRONESS_OF_THE_PHILIPPINES"
	case patronOfCanada = "PATRON_OF_CANADA"
	case patronOfEngland = "PATRON_OF_ENGLAND"
	case patronOfEurope = "PATRON_OF_EUROPE"
	case patronOfFrance = "PATRON_OF_FRANCE"
	case patronOfIreland = "PATRON_OF_IRELAND"
	case patronOfItaly = "PATRON_OF_ITALY"
	case patronOfOceania = "PATRON_OF_OCEANIA"
	case patronOfPoland = "PATRON_OF_POLAND"
	case patronOfRussia = "PATRON_OF_RUSSIA"
	case patronOfScotland = "PATRON_OF_SCOTLAND"
	case patronOfSpain = "PATRON_OF_SPAIN"
	case patronOfTheCzechNation = "PATRON_OF_THE_CZECH_NATION"
	case patronOfTheDiocese = "PATRON_OF_THE_DIOCESE"
	case patronOfWales = "PATRON_OF_WALES"
	case patronessOfAlsace = "PATRONESS_OF_ALSACE"
	case patronessOfArgentina = "PATRONESS_OF_ARGENTINA"
	case patronessOfBrazil = "PATRONESS_OF_BRAZIL"
	case patronessOfHungary = "PATRONESS_OF_HUNGARY"
	case patronessOfPuertoRico = "PATRONESS_OF_PUERTO_RICO"
	case patronessOfSlovakia = "PATRONESS_OF_SLOVAKIA"
	case patronessOfTheAmericas = "PATRONESS_OF_THE_AMERICAS"
	case patronessOfThePhilippines = "PATRONESS_OF_THE_PHILIPPINES"
	case patronessOfTheProvinceOfQuebec = "PATRONESS_OF_THE_PROVINCE_OF_QUEBEC"
	case patronessOfTheUsa = "PATRONESS_OF_THE_USA"
	case patronOfTheClergyOfTheArchdioceseOfLyon = "PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON"
	case patronOfTheCityOfLyon = "PATRON_OF_THE_CITY_OF_LYON"
	case patronessOfCostaRica = "PATRONESS_OF_COSTA_RICA"
	case principalPatronOfTheDiocese = "PRINCIPAL_PATRON_OF_THE_DIOCESE"
	case secondPatronOfTheDiocese = "SECOND_PATRON_OF_THE_DIOCESE"
}

/// Sex of a person.
public enum Sex: String, Codable, Equatable, Hashable, Sendable {
	/// Male person
	case male = "MALE"
	/// Female person
	case female = "FEMALE"
}

public struct Entity: Codable, Equatable, Hashable, Sendable {
	/// The unique identifier of the entity
	public let id: EntityId?
	/// The type of the entity.
	/// 
	/// Defaults to `EntityType::Person`.
	public let type: EntityType?
	/// The full name of the entity.
	public let fullname: String?
	/// The short name of the entity, without the canonization level and titles.
	public let name: String?
	/// The canonization level of a person.
	public let canonization_level: CanonizationLevel?
	/// Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
	/// or an object describing date range, multiple possible date, or a century.
	public let date_of_canonization: SaintDateDef?
	/// Specify whether an approximate indicator should be added, when the date is displayed.
	/// For example in English: 'c. 201'.
	public let date_of_canonization_is_approximative: Bool?
	/// Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
	/// or an object describing date range, multiple possible date, or a century.
	public let date_of_beatification: SaintDateDef?
	/// Specify whether an approximate indicator should be added, when the date is displayed.
	/// For example in English: 'c. 201'.
	public let date_of_beatification_is_approximative: Bool?
	/// Specify if the canonization level should not be displayed.
	/// It's generally the case when the canonization are already included in the name.
	public let hide_canonization_level: Bool?
	/// Titles of the Saint or the Blessed
	public let titles: [Title]?
	/// Determine if the Saint or the Blessed is a male or a female.
	public let sex: Sex?
	/// Specify if the titles should not be displayed.
	/// It's generally the case when titles are already included in the name.
	public let hide_titles: Bool?
	/// Date of Dedication of a church, basilica, or cathedral (or other place of worship),
	/// as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
	/// or an object describing date range, multiple possible date, or a century.
	public let date_of_dedication: SaintDateDef?
	/// Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
	/// or an object describing date range, multiple possible date, or a century.
	public let date_of_birth: SaintDateDef?
	/// Specify whether an approximate indicator should be added, when the date is displayed.
	/// For example in English: 'c. 201'.
	public let date_of_birth_is_approximative: Bool?
	/// Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
	/// or an object describing date range, multiple possible date, or a century.
	public let date_of_death: SaintDateDef?
	/// Specify whether an approximate indicator should be added, when the date is displayed.
	/// For example in English: 'c. 201'.
	public let date_of_death_is_approximative: Bool?
	/// Number of person that this definition represent.
	/// It could be set as 'many' if the number is not defined.
	public let count: SaintCount?
	/// Sources for the information about this entity
	public let sources: [String]?
	/// Internal notes (not serialized).
	public let _todo: [String]?

	public init(id: EntityId?, type: EntityType?, fullname: String?, name: String?, canonization_level: CanonizationLevel?, date_of_canonization: SaintDateDef?, date_of_canonization_is_approximative: Bool?, date_of_beatification: SaintDateDef?, date_of_beatification_is_approximative: Bool?, hide_canonization_level: Bool?, titles: [Title]?, sex: Sex?, hide_titles: Bool?, date_of_dedication: SaintDateDef?, date_of_birth: SaintDateDef?, date_of_birth_is_approximative: Bool?, date_of_death: SaintDateDef?, date_of_death_is_approximative: Bool?, count: SaintCount?, sources: [String]?, _todo: [String]?) {
		self.id = id
		self.type = type
		self.fullname = fullname
		self.name = name
		self.canonization_level = canonization_level
		self.date_of_canonization = date_of_canonization
		self.date_of_canonization_is_approximative = date_of_canonization_is_approximative
		self.date_of_beatification = date_of_beatification
		self.date_of_beatification_is_approximative = date_of_beatification_is_approximative
		self.hide_canonization_level = hide_canonization_level
		self.titles = titles
		self.sex = sex
		self.hide_titles = hide_titles
		self.date_of_dedication = date_of_dedication
		self.date_of_birth = date_of_birth
		self.date_of_birth_is_approximative = date_of_birth_is_approximative
		self.date_of_death = date_of_death
		self.date_of_death_is_approximative = date_of_death_is_approximative
		self.count = count
		self.sources = sources
		self._todo = _todo
	}
}

/// Summary of a celebration for use in optional celebrations list.
/// Contains the essential fields from a LiturgicalDay that identify a celebration.
public struct CelebrationSummary: Codable, Equatable, Hashable, Sendable {
	/// The unique identifier of the liturgical day
	public let id: LiturgicalDayId
	/// The full name of the liturgical day
	public let fullname: String
	/// The liturgical precedence for this liturgical day
	public let precedence: Precedence
	/// The liturgical rank for this liturgical day
	public let rank: Rank
	/// The localized liturgical rank for this liturgical day
	public let rank_name: String
	/// The liturgical colors for this liturgical day
	public let colors: [ColorInfo]
	/// The common prayers/readings used for this celebration
	public let commons: [CommonInfo]
	/// The entities (Saints, Blessed, or Places) linked to this liturgical day
	public let entities: [Entity]
	/// The titles for this liturgical day
	public let titles: TitlesDef
	/// Holy days of obligation
	public let is_holy_day_of_obligation: Bool
	/// Indicates if this liturgical day is optional
	public let is_optional: Bool
	/// The ID of the calendar where this liturgical day is defined
	public let from_calendar_id: CalendarId

	public init(id: LiturgicalDayId, fullname: String, precedence: Precedence, rank: Rank, rank_name: String, colors: [ColorInfo], commons: [CommonInfo], entities: [Entity], titles: TitlesDef, is_holy_day_of_obligation: Bool, is_optional: Bool, from_calendar_id: CalendarId) {
		self.id = id
		self.fullname = fullname
		self.precedence = precedence
		self.rank = rank
		self.rank_name = rank_name
		self.colors = colors
		self.commons = commons
		self.entities = entities
		self.titles = titles
		self.is_holy_day_of_obligation = is_holy_day_of_obligation
		self.is_optional = is_optional
		self.from_calendar_id = from_calendar_id
	}
}

/// Christmas Time season localized names and descriptions.
public struct ChristmasTimeSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Christmas Time
	public let season: String?
	/// Day terminology during Christmas Time
	public let day: String?
	/// Octave terminology during Christmas Time
	public let octave: String?
	/// Before Epiphany terminology
	public let before_epiphany: String?
	/// Second Sunday after Christmas terminology
	public let second_sunday_after_christmas: String?
	/// After Epiphany terminology
	public let after_epiphany: String?

	public init(season: String?, day: String?, octave: String?, before_epiphany: String?, second_sunday_after_christmas: String?, after_epiphany: String?) {
		self.season = season
		self.day = day
		self.octave = octave
		self.before_epiphany = before_epiphany
		self.second_sunday_after_christmas = second_sunday_after_christmas
		self.after_epiphany = after_epiphany
	}
}

/// Compound title definition for combining multiple titles.
/// Allows adding titles to the beginning or end of an existing title list.
public struct CompoundTitle: Codable, Equatable, Hashable, Sendable {
	/// The title(s) to add to the end of the existing list of title(s)
	public let append: [Title]?
	/// The title(s) to add to the beginning of the existing list of title(s)
	public let prepend: [Title]?

	public init(append: [Title]?, prepend: [Title]?) {
		self.append = append
		self.prepend = prepend
	}
}

/// Liturgical cycle names in the locale language.
public struct CyclesMetadata: Codable, Equatable, Hashable, Sendable {
	/// Proper of Time cycle name
	public let proper_of_time: String?
	/// Proper of Saints cycle name
	public let proper_of_saints: String?
	/// Sunday Year A cycle name
	public let sunday_year_a: String?
	/// Sunday Year B cycle name
	public let sunday_year_b: String?
	/// Sunday Year C cycle name
	public let sunday_year_c: String?
	/// Weekday Year 1 cycle name
	public let weekday_year_1: String?
	/// Weekday Year 2 cycle name
	public let weekday_year_2: String?
	/// Psalter Week 1 cycle name
	public let psalter_week_1: String?
	/// Psalter Week 2 cycle name
	public let psalter_week_2: String?
	/// Psalter Week 3 cycle name
	public let psalter_week_3: String?
	/// Psalter Week 4 cycle name
	public let psalter_week_4: String?

	public init(proper_of_time: String?, proper_of_saints: String?, sunday_year_a: String?, sunday_year_b: String?, sunday_year_c: String?, weekday_year_1: String?, weekday_year_2: String?, psalter_week_1: String?, psalter_week_2: String?, psalter_week_3: String?, psalter_week_4: String?) {
		self.proper_of_time = proper_of_time
		self.proper_of_saints = proper_of_saints
		self.sunday_year_a = sunday_year_a
		self.sunday_year_b = sunday_year_b
		self.sunday_year_c = sunday_year_c
		self.weekday_year_1 = weekday_year_1
		self.weekday_year_2 = weekday_year_2
		self.psalter_week_1 = psalter_week_1
		self.psalter_week_2 = psalter_week_2
		self.psalter_week_3 = psalter_week_3
		self.psalter_week_4 = psalter_week_4
	}
}

/// Definition of a liturgical day with all its properties and configurations.
/// It represents a complete liturgical day definition that can be used
/// to generate calendar entries with proper precedence, colors, and entity associations.
public struct DayDefinition: Codable, Equatable, Hashable, Sendable {
	/// The date definition for this liturgical day
	public let date_def: DateDef?
	/// The date definition exceptions (overrides for specific circumstances)
	public let date_exceptions: DateDefExceptions?
	/// The precedence type of the liturgical day
	public let precedence: Precedence?
	/// The **Common** refers to a set of prayers, readings, and chants used for celebrating saints or
	/// feasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed
	/// Virgin Mary.
	public let commons_def: CommonsDef?
	/// Holy days of obligation are days on which the faithful are expected to attend Mass
	/// and engage in rest from work and recreation
	public let is_holy_day_of_obligation: Bool?
	/// Allow similar items that have the same rank and the same or lower precedence
	/// to coexist with this liturgical day without being overwritten
	public let allow_similar_rank_items: Bool?
	/// Specify if this liturgical day is optional within a specific liturgical calendar
	/// 
	/// UNLY #14:
	/// Memorials are either obligatory or optional; their observance is integrated into
	/// the celebration of the occurring weekday in accordance with the norms set forth in the
	/// General Instruction of the Roman Missal and of the Liturgy of the Hours
	/// 
	/// Note: also used for the dedication of consecrated churches, which is an optional solemnity
	/// that should not overwrite the default weekday.
	public let is_optional: Bool?
	/// The custom locale ID for this date definition in this calendar
	public let custom_locale_id: LocaleId?
	/// The entities (Saints, Blessed, or Places) linked from the Entity catalog
	public let entities: [EntityRef]?
	/// The combined titles of all entities linked to this date definition
	public let titles: TitlesDef?
	/// If this liturgical day must be removed from this calendar and from all parent calendars
	/// in the final calendar generated by romcal
	public let drop: Bool?
	/// The liturgical color(s) of the liturgical day.
	/// 
	/// **Deprecated:** Rely on the `titles` field of entities instead to determine the liturgical color(s).
	public let colors: ColorsDef?
	/// The masses definitions for this liturgical day
	public let masses: MassesDefinitions?

	public init(date_def: DateDef?, date_exceptions: DateDefExceptions?, precedence: Precedence?, commons_def: CommonsDef?, is_holy_day_of_obligation: Bool?, allow_similar_rank_items: Bool?, is_optional: Bool?, custom_locale_id: LocaleId?, entities: [EntityRef]?, titles: TitlesDef?, drop: Bool?, colors: ColorsDef?, masses: MassesDefinitions?) {
		self.date_def = date_def
		self.date_exceptions = date_exceptions
		self.precedence = precedence
		self.commons_def = commons_def
		self.is_holy_day_of_obligation = is_holy_day_of_obligation
		self.allow_similar_rank_items = allow_similar_rank_items
		self.is_optional = is_optional
		self.custom_locale_id = custom_locale_id
		self.entities = entities
		self.titles = titles
		self.drop = drop
		self.colors = colors
		self.masses = masses
	}
}

/// Easter Time season localized names and descriptions.
public struct EasterTimeSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Easter Time
	public let season: String?
	/// Weekday terminology during Easter Time
	public let weekday: String?
	/// Sunday terminology during Easter Time
	public let sunday: String?
	/// Octave terminology during Easter Time
	public let octave: String?

	public init(season: String?, weekday: String?, sunday: String?, octave: String?) {
		self.season = season
		self.weekday = weekday
		self.sunday = sunday
		self.octave = octave
	}
}

/// Custom entity definition that extends or overrides properties from the entity catalog.
/// Used when a liturgical day needs specific entity properties that differ from the base entity.
public struct EntityOverride: Codable, Equatable, Hashable, Sendable {
	/// The ID of the entity item (must reference an existing entity in the catalog)
	public let id: String
	/// The custom titles for this entity in the context of this liturgical day
	public let titles: TitlesDef?
	/// Whether to hide titles when displaying this entity (useful when titles are already included in the entity name)
	public let hide_titles: Bool?
	/// The number of persons this entity represents (useful for groups of martyrs or saints)
	public let count: SaintCount?

	public init(id: String, titles: TitlesDef?, hide_titles: Bool?, count: SaintCount?) {
		self.id = id
		self.titles = titles
		self.hide_titles = hide_titles
		self.count = count
	}
}

/// Lent season localized names and descriptions.
public struct LentSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Lent
	public let season: String?
	/// Weekday terminology during Lent
	public let weekday: String?
	/// Sunday terminology during Lent
	public let sunday: String?
	/// Day after Ash Wednesday terminology
	public let day_after_ash_wed: String?
	/// Holy Week day terminology
	public let holy_week_day: String?

	public init(season: String?, weekday: String?, sunday: String?, day_after_ash_wed: String?, holy_week_day: String?) {
		self.season = season
		self.weekday = weekday
		self.sunday = sunday
		self.day_after_ash_wed = day_after_ash_wed
		self.holy_week_day = holy_week_day
	}
}

/// Liturgical seasons of the Church year.
/// Represents the major periods that structure the liturgical calendar.
public enum Season: String, Codable, Equatable, Hashable, Sendable {
	/// Advent
	case advent = "ADVENT"
	/// Christmas Time
	case christmasTime = "CHRISTMAS_TIME"
	/// Lent
	case lent = "LENT"
	/// Paschal Triduum
	case paschalTriduum = "PASCHAL_TRIDUUM"
	/// Easter Time
	case easterTime = "EASTER_TIME"
	/// Ordinary Time
	case ordinaryTime = "ORDINARY_TIME"
}

/// Specific periods within liturgical seasons.
/// Defines sub-periods that have special liturgical characteristics or rules.
public enum Period: String, Codable, Equatable, Hashable, Sendable {
	/// The eight days following Christmas (December 25 - January 1)
	case christmasOctave = "CHRISTMAS_OCTAVE"
	/// Days before Epiphany (January 2 to the day before Epiphany)
	case daysBeforeEpiphany = "DAYS_BEFORE_EPIPHANY"
	/// Days from Epiphany to the Presentation (January 6 to the day before the Presentation of the Lord)
	case daysFromEpiphany = "DAYS_FROM_EPIPHANY"
	/// Period from Christmas to the Presentation of the Lord
	case christmasToPresentationOfTheLord = "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"
	/// Period from the Presentation to Holy Thursday
	case presentationOfTheLordToHolyThursday = "PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"
	/// Holy Week (Palm Sunday to Holy Saturday)
	case holyWeek = "HOLY_WEEK"
	/// Paschal Triduum (start from the Thursday of the Lord's Supper to the Easter Sunday Vespers)
	case paschalTriduum = "PASCHAL_TRIDUUM"
	/// The eight days following Easter Sunday
	case easterOctave = "EASTER_OCTAVE"
	/// Early Ordinary Time (after the Presentation of the Lord to the day before Ash Wednesday)
	case earlyOrdinaryTime = "EARLY_ORDINARY_TIME"
	/// Late Ordinary Time (after Pentecost to the day before the First Sunday of Advent)
	case lateOrdinaryTime = "LATE_ORDINARY_TIME"
}

/// Liturgical period information with localized name.
public struct PeriodInfo: Codable, Equatable, Hashable, Sendable {
	/// The period key
	public let key: Period
	/// The localized name of the period
	public let name: String

	public init(key: Period, name: String) {
		self.key = key
		self.name = name
	}
}

/// Times of Mass celebrations in the liturgical calendar.
/// Different Masses are celebrated at various times and occasions throughout the liturgical year.
public enum MassTime: String, Codable, Equatable, Hashable, Sendable {
	/// Easter Vigil - the most important Mass of the liturgical year, celebrated on Holy Saturday night
	case easterVigil = "easter_vigil"
	/// Previous Evening Mass - Mass celebrated the evening before a major feast
	case previousEveningMass = "previous_evening_mass"
	/// Night Mass - Mass celebrated during the night hours
	case nightMass = "night_mass"
	/// Mass at Dawn - Mass celebrated at dawn, particularly on Easter Sunday
	case massAtDawn = "mass_at_dawn"
	/// Morning Mass - Mass celebrated in the morning
	case morningMass = "morning_mass"
	/// Mass of the Passion - Mass focusing on Christ's passion, beginning with the procession with palms
	case massOfThePassion = "mass_of_the_passion"
	/// Celebration of the Passion - special celebration of Christ's passion
	case celebrationOfThePassion = "celebration_of_the_passion"
	/// Day Mass - regular Mass celebrated during the day
	case dayMass = "day_mass"
	/// Chrism Mass - Mass where holy oils are blessed, typically on Holy Thursday morning
	case chrismMass = "chrism_mass"
	/// Evening Mass of the Lord's Supper - Mass celebrated on Holy Thursday evening
	case eveningMassOfTheLordsSupper = "evening_mass_of_the_lords_supper"
}

/// Information about a mass celebration for a liturgical day.
/// Contains the type of mass and its localized name.
public struct MassInfo: Codable, Equatable, Hashable, Sendable {
	/// The type of mass (e.g., DayMass, EasterVigil, etc.)
	/// Serialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")
	public let type: MassTime
	/// The localized name of the mass type (translation key in snake_case)
	public let name: String

	public init(type: MassTime, name: String) {
		self.type = type
		self.name = name
	}
}

/// A three-year cycle for Sunday Mass readings (and some solemnities), designated by A, B, or C.
/// Each cycle begins on the First Sunday of Advent of the previous civil year and ends on Saturday
/// after the Christ the King Solemnity. The cycles follow each other in alphabetical order.
/// C year is always divisible by 3, A has remainder of 1, and B remainder of 2.
public enum SundayCycle: String, Codable, Equatable, Hashable, Sendable {
	/// Year A
	case yearA = "YEAR_A"
	/// Year B
	case yearB = "YEAR_B"
	/// Year C
	case yearC = "YEAR_C"
}

/// A two-year cycle for the weekday Mass readings (also called Cycle I and Cycle II).
/// Odd-numbered years are the Cycle I (year 1); even-numbered ones are the Cycle II (year 2).
public enum WeekdayCycle: String, Codable, Equatable, Hashable, Sendable {
	/// Year 1 (Cycle I)
	case year1 = "YEAR_1"
	/// Year 2 (Cycle II)
	case year2 = "YEAR_2"
}

/// [GILH §133] The four-week cycle of the psalter is coordinated with the liturgical year in such a way that
/// on the First Sunday of Advent, the First Sunday in Ordinary Time, the First Sunday of Lent,
/// and Easter Sunday the cycle is always begun again with Week 1 (others being omitted when necessary).
public enum PsalterWeekCycle: String, Codable, Equatable, Hashable, Sendable {
	/// Week 1
	case week1 = "WEEK_1"
	/// Week 2
	case week2 = "WEEK_2"
	/// Week 3
	case week3 = "WEEK_3"
	/// Week 4
	case week4 = "WEEK_4"
}

/// Common definition for simplified categorization.
/// Provides a simplified version of the Common enum for easier classification.
public enum CommonDefinition: String, Codable, Equatable, Hashable, Sendable {
	/// No common.
	case none = "NONE"
	/// Dedication anniversary (in the Church that was Dedicated).
	case dedicationAnniversaryInside = "DEDICATION_ANNIVERSARY__INSIDE"
	/// Dedication anniversary (outside the Church that was Dedicated).
	case dedicationAnniversaryOutside = "DEDICATION_ANNIVERSARY__OUTSIDE"
	/// Common of the Blessed Virgin Mary.
	case blessedVirginMary = "BLESSED_VIRGIN_MARY"
	/// Common for Martyrs.
	case martyrs = "MARTYRS"
	/// Common for Missionary Martyrs.
	case missionaryMartyrs = "MISSIONARY_MARTYRS"
	/// Common for Virgin Martyrs.
	case virginMartyrs = "VIRGIN_MARTYRS"
	/// Common for Holy Woman Martyrs.
	case womanMartyrs = "WOMAN_MARTYRS"
	/// Common for Pastors.
	case pastors = "PASTORS"
	/// Common for Popes.
	case popes = "POPES"
	/// Common for Bishops.
	case bishops = "BISHOPS"
	/// Common for Founders.
	case founders = "FOUNDERS"
	/// Common for Missionaries.
	case missionaries = "MISSIONARIES"
	/// Common for Doctors of the Church.
	case doctorsOfTheChurch = "DOCTORS_OF_THE_CHURCH"
	/// Common for Virgins.
	case virgins = "VIRGINS"
	/// Common for Holy Men and Women.
	case saints = "SAINTS"
	/// Common for Abbots.
	case abbots = "ABBOTS"
	/// Common for Monks.
	case monks = "MONKS"
	/// Common for Nuns.
	case nuns = "NUNS"
	/// Common for Religious.
	case religious = "RELIGIOUS"
	/// Common for Those Who Practiced Works of Mercy.
	case mercyWorkers = "MERCY_WORKERS"
	/// Common for Educators.
	case educators = "EDUCATORS"
	/// Common for Holy Women.
	case holyWomen = "HOLY_WOMEN"
}

/// Represents the differences between a liturgical day definition and its parent definition.
/// This is a lightweight structure that only contains fields that can be overridden.
public struct ParentOverride: Codable, Equatable, Hashable, Sendable {
	/// The ID of the calendar from which this override originates
	public let from_calendar_id: CalendarId
	/// The date definition if it was changed
	public let date_def: DateDef?
	/// The date exceptions if they were changed
	public let date_exceptions: [DateDefException]?
	/// The precedence if it was changed
	public let precedence: Precedence?
	/// The rank if it was changed
	public let rank: Rank?
	/// The colors if they were changed
	public let colors: [ColorInfo]?
	/// The titles if they were changed
	public let titles: TitlesDef?
	/// The commons definition if it was changed
	public let commons_def: [CommonDefinition]?
	/// The is_holy_day_of_obligation flag if it was changed
	public let is_holy_day_of_obligation: Bool?
	/// The is_optional flag if it was changed
	public let is_optional: Bool?
	/// The allow_similar_rank_items flag if it was changed
	public let allow_similar_rank_items: Bool?

	public init(from_calendar_id: CalendarId, date_def: DateDef?, date_exceptions: [DateDefException]?, precedence: Precedence?, rank: Rank?, colors: [ColorInfo]?, titles: TitlesDef?, commons_def: [CommonDefinition]?, is_holy_day_of_obligation: Bool?, is_optional: Bool?, allow_similar_rank_items: Bool?) {
		self.from_calendar_id = from_calendar_id
		self.date_def = date_def
		self.date_exceptions = date_exceptions
		self.precedence = precedence
		self.rank = rank
		self.colors = colors
		self.titles = titles
		self.commons_def = commons_def
		self.is_holy_day_of_obligation = is_holy_day_of_obligation
		self.is_optional = is_optional
		self.allow_similar_rank_items = allow_similar_rank_items
	}
}

/// A single day in the liturgical calendar with computed values and inheritance information.
public struct LiturgicalDay: Codable, Equatable, Hashable, Sendable {
	/// The unique identifier of the liturgical day
	public let id: LiturgicalDayId
	/// The full name of the liturgical day
	public let fullname: String
	/// The computed date of the liturgical day.
	public let date: String
	/// The date definition for this liturgical day.
	public let date_def: DateDef
	/// The date definition exceptions for this liturgical day.
	public let date_exceptions: [DateDefException]
	/// The liturgical precedence for this liturgical day.
	public let precedence: Precedence
	/// The liturgical rank for this liturgical day.
	public let rank: Rank
	/// The localized liturgical rank for this liturgical day.
	public let rank_name: String
	/// Allows similar items with the same rank and same or lower precedence
	/// to coexist without this liturgical day overwriting them.
	public let allow_similar_rank_items: Bool
	/// Holy days of obligation are days on which the faithful are expected to attend Mass,
	/// and engage in rest from work and recreation.
	public let is_holy_day_of_obligation: Bool
	/// Indicates if this liturgical day is optional within a specific liturgical calendar.
	public let is_optional: Bool
	/// The liturgical seasons to which this liturgical day belongs.
	public let season: Season?
	/// The liturgical season name.
	public let season_name: String?
	/// The liturgical periods to which this liturgical day belongs.
	public let periods: [PeriodInfo]
	/// The common prayers, readings, and chants used for celebrating saints or
	/// feasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed
	/// Virgin Mary.
	public let commons: [CommonInfo]
	/// The liturgical colors for this liturgical day.
	public let colors: [ColorInfo]
	/// The masses celebrated on this liturgical day.
	/// Most days have a single DayMass, but some have multiple masses
	/// (e.g., Christmas: PreviousEveningMass, NightMass, MassAtDawn, DayMass).
	/// Aliturgical days like Holy Saturday have an empty list.
	public let masses: [MassInfo]
	/// The titles for this liturgical day.
	public let titles: TitlesDef
	/// The entities (Saints, Blessed, or Places) linked to this liturgical day.
	public let entities: [Entity]
	/// The week number of the current liturgical season.
	/// Starts from `1`, except in the seasons of lent,
	/// the week of Ash Wednesday to the next Saturday is counted as `0`.
	public let week_of_season: UInt32?
	/// The day number within the current liturgical season.
	public let day_of_season: UInt32?
	/// The day of the week for this liturgical day.
	/// Returns a number from 0 (Sunday) to 6 (Saturday).
	public let day_of_week: DayOfWeek
	/// The nth occurrence of this day of the week within the current month.
	/// For example, the 3rd Sunday of the month would have nth_day_of_week_in_month = 3.
	public let nth_day_of_week_in_month: UInt8
	/// The first day of the current liturgical season for this liturgical day.
	public let start_of_season: String?
	/// The last day of the current liturgical season for this liturgical day.
	public let end_of_season: String?
	/// The first day of the current liturgical year for this liturgical day,
	/// i.e. the first Sunday of Advent.
	public let start_of_liturgical_year: String
	/// The last day of the current liturgical year for this liturgical day,
	/// i.e. the last Saturday of Ordinary Time, in the 34th week.
	public let end_of_liturgical_year: String
	/// The Sunday cycle to which this liturgical day belongs.
	public let sunday_cycle: SundayCycle
	/// The localized name of the Sunday cycle to which this liturgical day belongs.
	public let sunday_cycle_name: String
	/// The weekday cycle to which this liturgical day belongs.
	public let weekday_cycle: WeekdayCycle
	/// The localized name of the weekday cycle to which this liturgical day belongs.
	public let weekday_cycle_name: String
	/// The psalter week cycle to which this liturgical day belongs.
	public let psalter_week: PsalterWeekCycle
	/// The localized name of the psalter week cycle to which this liturgical day belongs.
	public let psalter_week_name: String
	/// The ID of the calendar where this liturgical day is defined.
	/// Indicates the source calendar in the inheritance chain.
	public let from_calendar_id: CalendarId
	/// Contains the differences between this liturgical day and its parent definitions.
	/// Each element in the array represents the diff from a parent calendar definition.
	/// The array is ordered from most general (e.g., general_roman) to most specific.
	public let parent_overrides: [ParentOverride]

	public init(id: LiturgicalDayId, fullname: String, date: String, date_def: DateDef, date_exceptions: [DateDefException], precedence: Precedence, rank: Rank, rank_name: String, allow_similar_rank_items: Bool, is_holy_day_of_obligation: Bool, is_optional: Bool, season: Season?, season_name: String?, periods: [PeriodInfo], commons: [CommonInfo], colors: [ColorInfo], masses: [MassInfo], titles: TitlesDef, entities: [Entity], week_of_season: UInt32?, day_of_season: UInt32?, day_of_week: DayOfWeek, nth_day_of_week_in_month: UInt8, start_of_season: String?, end_of_season: String?, start_of_liturgical_year: String, end_of_liturgical_year: String, sunday_cycle: SundayCycle, sunday_cycle_name: String, weekday_cycle: WeekdayCycle, weekday_cycle_name: String, psalter_week: PsalterWeekCycle, psalter_week_name: String, from_calendar_id: CalendarId, parent_overrides: [ParentOverride]) {
		self.id = id
		self.fullname = fullname
		self.date = date
		self.date_def = date_def
		self.date_exceptions = date_exceptions
		self.precedence = precedence
		self.rank = rank
		self.rank_name = rank_name
		self.allow_similar_rank_items = allow_similar_rank_items
		self.is_holy_day_of_obligation = is_holy_day_of_obligation
		self.is_optional = is_optional
		self.season = season
		self.season_name = season_name
		self.periods = periods
		self.commons = commons
		self.colors = colors
		self.masses = masses
		self.titles = titles
		self.entities = entities
		self.week_of_season = week_of_season
		self.day_of_season = day_of_season
		self.day_of_week = day_of_week
		self.nth_day_of_week_in_month = nth_day_of_week_in_month
		self.start_of_season = start_of_season
		self.end_of_season = end_of_season
		self.start_of_liturgical_year = start_of_liturgical_year
		self.end_of_liturgical_year = end_of_liturgical_year
		self.sunday_cycle = sunday_cycle
		self.sunday_cycle_name = sunday_cycle_name
		self.weekday_cycle = weekday_cycle
		self.weekday_cycle_name = weekday_cycle_name
		self.psalter_week = psalter_week
		self.psalter_week_name = psalter_week_name
		self.from_calendar_id = from_calendar_id
		self.parent_overrides = parent_overrides
	}
}

/// Liturgical color names in the locale language.
/// Provides localized names for each liturgical color.
public struct LocaleColors: Codable, Equatable, Hashable, Sendable {
	/// Black color name in the locale language
	public let black: String?
	/// Gold color name in the locale language
	public let gold: String?
	/// Green color name in the locale language
	public let green: String?
	/// Purple color name in the locale language
	public let purple: String?
	/// Red color name in the locale language
	public let red: String?
	/// Rose color name in the locale language
	public let rose: String?
	/// White color name in the locale language
	public let white: String?

	public init(black: String?, gold: String?, green: String?, purple: String?, red: String?, rose: String?, white: String?) {
		self.black = black
		self.gold = gold
		self.green = green
		self.purple = purple
		self.red = red
		self.rose = rose
		self.white = white
	}
}

/// A flat structure representing a single mass with its full liturgical context.
/// 
/// This is the main type for the mass-centric calendar view. It contains:
/// - Mass identification (type, name, civil/liturgical dates)
/// - Day-level context (season, cycles, periods)
/// - Primary celebration data (flattened from LiturgicalDay)
/// - Optional alternative celebrations
/// 
/// For evening masses (Easter Vigil, Previous Evening Mass), the `civil_date`
/// is shifted to the previous day while `liturgical_date` remains the original
/// liturgical celebration date.
public struct MassContext: Codable, Equatable, Hashable, Sendable {
	/// The type of mass (e.g., DayMass, EasterVigil, etc.)
	/// Serialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")
	public let mass_time: MassTime
	/// The localized name of the mass time (translation key in snake_case)
	public let mass_time_name: String
	/// The civil calendar date when this mass is celebrated (YYYY-MM-DD).
	/// For evening masses (EasterVigil, PreviousEveningMass), this is the day
	/// BEFORE the liturgical date.
	public let civil_date: String
	/// The liturgical date this mass belongs to (YYYY-MM-DD).
	/// This is the "theological" date of the celebration.
	public let liturgical_date: String
	/// The liturgical season
	public let season: Season?
	/// The localized season name
	public let season_name: String?
	/// The Sunday cycle (Year A, B, or C)
	public let sunday_cycle: SundayCycle
	/// The localized Sunday cycle name
	public let sunday_cycle_name: String
	/// The weekday cycle (Year 1 or 2)
	public let weekday_cycle: WeekdayCycle
	/// The localized weekday cycle name
	public let weekday_cycle_name: String
	/// The psalter week cycle (Week 1-4)
	public let psalter_week: PsalterWeekCycle
	/// The localized psalter week name
	public let psalter_week_name: String
	/// The week number within the liturgical season
	public let week_of_season: UInt32?
	/// The day number within the liturgical season
	public let day_of_season: UInt32?
	/// The day of the week (0=Sunday to 6=Saturday)
	public let day_of_week: DayOfWeek
	/// The liturgical periods this day belongs to
	public let periods: [PeriodInfo]
	/// The first day of the current liturgical season
	public let start_of_season: String?
	/// The last day of the current liturgical season
	public let end_of_season: String?
	/// The first day of the liturgical year (first Sunday of Advent)
	public let start_of_liturgical_year: String
	/// The last day of the liturgical year
	public let end_of_liturgical_year: String
	/// The unique identifier of the liturgical day
	public let id: LiturgicalDayId
	/// The full name of the liturgical day
	public let fullname: String
	/// The liturgical precedence
	public let precedence: Precedence
	/// The liturgical rank
	public let rank: Rank
	/// The localized liturgical rank name
	public let rank_name: String
	/// The liturgical colors
	public let colors: [ColorInfo]
	/// The common prayers/readings used
	public let commons: [CommonInfo]
	/// The entities (Saints, Blessed, or Places) linked to this day
	public let entities: [Entity]
	/// The titles for this liturgical day
	public let titles: TitlesDef
	/// Whether this is a holy day of obligation
	public let is_holy_day_of_obligation: Bool
	/// Whether this liturgical day is optional
	public let is_optional: Bool
	/// The ID of the calendar where this liturgical day is defined
	public let from_calendar_id: CalendarId
	/// Optional alternative celebrations (e.g., optional memorials)
	/// that can be celebrated instead of the primary celebration.
	public let optional_celebrations: [CelebrationSummary]

	public init(mass_time: MassTime, mass_time_name: String, civil_date: String, liturgical_date: String, season: Season?, season_name: String?, sunday_cycle: SundayCycle, sunday_cycle_name: String, weekday_cycle: WeekdayCycle, weekday_cycle_name: String, psalter_week: PsalterWeekCycle, psalter_week_name: String, week_of_season: UInt32?, day_of_season: UInt32?, day_of_week: DayOfWeek, periods: [PeriodInfo], start_of_season: String?, end_of_season: String?, start_of_liturgical_year: String, end_of_liturgical_year: String, id: LiturgicalDayId, fullname: String, precedence: Precedence, rank: Rank, rank_name: String, colors: [ColorInfo], commons: [CommonInfo], entities: [Entity], titles: TitlesDef, is_holy_day_of_obligation: Bool, is_optional: Bool, from_calendar_id: CalendarId, optional_celebrations: [CelebrationSummary]) {
		self.mass_time = mass_time
		self.mass_time_name = mass_time_name
		self.civil_date = civil_date
		self.liturgical_date = liturgical_date
		self.season = season
		self.season_name = season_name
		self.sunday_cycle = sunday_cycle
		self.sunday_cycle_name = sunday_cycle_name
		self.weekday_cycle = weekday_cycle
		self.weekday_cycle_name = weekday_cycle_name
		self.psalter_week = psalter_week
		self.psalter_week_name = psalter_week_name
		self.week_of_season = week_of_season
		self.day_of_season = day_of_season
		self.day_of_week = day_of_week
		self.periods = periods
		self.start_of_season = start_of_season
		self.end_of_season = end_of_season
		self.start_of_liturgical_year = start_of_liturgical_year
		self.end_of_liturgical_year = end_of_liturgical_year
		self.id = id
		self.fullname = fullname
		self.precedence = precedence
		self.rank = rank
		self.rank_name = rank_name
		self.colors = colors
		self.commons = commons
		self.entities = entities
		self.titles = titles
		self.is_holy_day_of_obligation = is_holy_day_of_obligation
		self.is_optional = is_optional
		self.from_calendar_id = from_calendar_id
		self.optional_celebrations = optional_celebrations
	}
}

/// Ordinary Time season localized names and descriptions.
public struct OrdinaryTimeSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Ordinary Time
	public let season: String?
	/// Weekday terminology during Ordinary Time
	public let weekday: String?
	/// Sunday terminology during Ordinary Time
	public let sunday: String?

	public init(season: String?, weekday: String?, sunday: String?) {
		self.season = season
		self.weekday = weekday
		self.sunday = sunday
	}
}

/// Paschal Triduum season localized names and descriptions.
public struct PaschalTriduumSeason: Codable, Equatable, Hashable, Sendable {
	/// General season name for Paschal Triduum
	public let season: String?

	public init(season: String?) {
		self.season = season
	}
}

/// Liturgical period names in the locale language.
public struct PeriodsMetadata: Codable, Equatable, Hashable, Sendable {
	/// Christmas Octave period name
	public let christmas_octave: String?
	/// Days before Epiphany period name
	public let days_before_epiphany: String?
	/// Days from Epiphany period name
	public let days_from_epiphany: String?
	/// Christmas to Presentation of the Lord period name
	public let christmas_to_presentation_of_the_lord: String?
	/// Presentation of the Lord to Holy Thursday period name
	public let presentation_of_the_lord_to_holy_thursday: String?
	/// Holy Week period name
	public let holy_week: String?
	/// Paschal Triduum period name
	public let paschal_triduum: String?
	/// Easter Octave period name
	public let easter_octave: String?
	/// Early Ordinary Time period name
	public let early_ordinary_time: String?
	/// Late Ordinary Time period name
	public let late_ordinary_time: String?

	public init(christmas_octave: String?, days_before_epiphany: String?, days_from_epiphany: String?, christmas_to_presentation_of_the_lord: String?, presentation_of_the_lord_to_holy_thursday: String?, holy_week: String?, paschal_triduum: String?, easter_octave: String?, early_ordinary_time: String?, late_ordinary_time: String?) {
		self.christmas_octave = christmas_octave
		self.days_before_epiphany = days_before_epiphany
		self.days_from_epiphany = days_from_epiphany
		self.christmas_to_presentation_of_the_lord = christmas_to_presentation_of_the_lord
		self.presentation_of_the_lord_to_holy_thursday = presentation_of_the_lord_to_holy_thursday
		self.holy_week = holy_week
		self.paschal_triduum = paschal_triduum
		self.easter_octave = easter_octave
		self.early_ordinary_time = early_ordinary_time
		self.late_ordinary_time = late_ordinary_time
	}
}

/// Liturgical rank names in the locale language.
public struct RanksMetadata: Codable, Equatable, Hashable, Sendable {
	/// Solemnity rank name
	public let solemnity: String?
	/// Sunday rank name
	public let sunday: String?
	/// Feast rank name
	public let feast: String?
	/// Memorial rank name
	public let memorial: String?
	/// Optional memorial rank name
	public let optional_memorial: String?
	/// Weekday rank name
	public let weekday: String?

	public init(solemnity: String?, sunday: String?, feast: String?, memorial: String?, optional_memorial: String?, weekday: String?) {
		self.solemnity = solemnity
		self.sunday = sunday
		self.feast = feast
		self.memorial = memorial
		self.optional_memorial = optional_memorial
		self.weekday = weekday
	}
}

/// Format for displaying ordinal numbers.
/// 
/// - `Letters`: Display ordinals as words (e.g., "first", "second", "premier", "deuxième")
/// - `Numeric`: Display ordinals as numbers with suffixes (e.g., "1st", "2nd", "1er", "2e")
public enum OrdinalFormat: String, Codable, Equatable, Hashable, Sendable {
	/// Ordinals displayed as words
	case letters
	/// Ordinals displayed as numbers with suffixes (default)
	case numeric
}

/// Liturgical season names and descriptions in the locale language.
/// Provides localized names for each liturgical season and their components.
public struct SeasonsMetadata: Codable, Equatable, Hashable, Sendable {
	/// Advent season names and descriptions
	public let advent: AdventSeason?
	/// Christmas Time season names and descriptions
	public let christmas_time: ChristmasTimeSeason?
	/// Ordinary Time season names and descriptions
	public let ordinary_time: OrdinaryTimeSeason?
	/// Lent season names and descriptions
	public let lent: LentSeason?
	/// Paschal Triduum season names and descriptions
	public let paschal_triduum: PaschalTriduumSeason?
	/// Easter Time season names and descriptions
	public let easter_time: EasterTimeSeason?

	public init(advent: AdventSeason?, christmas_time: ChristmasTimeSeason?, ordinary_time: OrdinaryTimeSeason?, lent: LentSeason?, paschal_triduum: PaschalTriduumSeason?, easter_time: EasterTimeSeason?) {
		self.advent = advent
		self.christmas_time = christmas_time
		self.ordinary_time = ordinary_time
		self.lent = lent
		self.paschal_triduum = paschal_triduum
		self.easter_time = easter_time
	}
}

/// Metadata for localized resources.
/// Contains all the localized strings and configurations for a specific locale.
public struct ResourcesMetadata: Codable, Equatable, Hashable, Sendable {
	/// Format for displaying ordinal numbers (defaults to Numeric if not specified)
	public let ordinal_format: OrdinalFormat?
	/// Ordinal numbers as words (first, second, third, etc.) in the locale language
	public let ordinals_letters: BTreeMap<String, String>?
	/// Ordinal numbers as numeric with suffix (1st, 2nd, 3rd, etc.) in the locale language
	public let ordinals_numeric: BTreeMap<String, String>?
	/// Weekday names (Sunday, Monday, etc.) in the locale language
	public let weekdays: BTreeMap<String, String>?
	/// Month names (January, February, etc.) in the locale language
	public let months: BTreeMap<String, String>?
	/// Liturgical color names in the locale language
	public let colors: LocaleColors?
	/// Liturgical season names and descriptions in the locale language
	public let seasons: SeasonsMetadata?
	/// Liturgical period names in the locale language
	public let periods: PeriodsMetadata?
	/// Liturgical rank names in the locale language
	public let ranks: RanksMetadata?
	/// Liturgical cycle names in the locale language
	public let cycles: CyclesMetadata?

	public init(ordinal_format: OrdinalFormat?, ordinals_letters: BTreeMap<String, String>?, ordinals_numeric: BTreeMap<String, String>?, weekdays: BTreeMap<String, String>?, months: BTreeMap<String, String>?, colors: LocaleColors?, seasons: SeasonsMetadata?, periods: PeriodsMetadata?, ranks: RanksMetadata?, cycles: CyclesMetadata?) {
		self.ordinal_format = ordinal_format
		self.ordinals_letters = ordinals_letters
		self.ordinals_numeric = ordinals_numeric
		self.weekdays = weekdays
		self.months = months
		self.colors = colors
		self.seasons = seasons
		self.periods = periods
		self.ranks = ranks
		self.cycles = cycles
	}
}

/// Resources definition
public struct Resources: Codable, Equatable, Hashable, Sendable {
	/// Locale code of the resources, in BCP-47 IETF tag format
	public let locale: LocaleId
	/// Metadata of the resources
	public let metadata: ResourcesMetadata?
	/// Entities of the resources: a person, a place, an event, etc.
	public let entities: BTreeMap<EntityId, Entity>?

	public init(locale: LocaleId, metadata: ResourcesMetadata?, entities: BTreeMap<EntityId, Entity>?) {
		self.locale = locale
		self.metadata = metadata
		self.entities = entities
	}
}

/// Acclamations used in liturgical celebrations.
/// Acclamations are short liturgical responses or exclamations used during Mass.
public enum Acclamation: String, Codable, Equatable, Hashable, Sendable {
	/// Alleluia - joyful acclamation used outside of Lent
	case alleluia = "ALLELUIA"
	/// Lent - acclamation used during Lenten season
	case lent = "LENT"
	/// Mixed - combination of different acclamation types
	case mixed = "MIXED"
	/// None - no acclamation
	case none = "NONE"
}

/// Books of the Bible using OSIS (Open Scripture Information Standard) identifiers.
/// OSIS provides standardized abbreviations for biblical books used in liturgical and biblical applications.
public enum BibleBook: String, Codable, Equatable, Hashable, Sendable {
	/// Genesis
	case gen = "Gen"
	/// Exodus
	case exod = "Exod"
	/// Leviticus
	case lev = "Lev"
	/// Numbers
	case num = "Num"
	/// Deuteronomy
	case deut = "Deut"
	/// Joshua
	case josh = "Josh"
	/// Judges
	case judg = "Judg"
	/// Ruth
	case ruth = "Ruth"
	/// 1 Samuel
	case firstSam = "1Sam"
	/// 2 Samuel
	case secondSam = "2Sam"
	/// 1 Kings
	case firstKgs = "1Kgs"
	/// 2 Kings
	case secondKgs = "2Kgs"
	/// 1 Chronicles
	case firstChr = "1Chr"
	/// 2 Chronicles
	case secondChr = "2Chr"
	/// Ezra
	case ezra = "Ezra"
	/// Nehemiah
	case neh = "Neh"
	/// Tobit
	case tob = "Tob"
	/// Judith
	case jdt = "Jdt"
	/// Esther
	case esth = "Esth"
	/// 1 Maccabees
	case firstMacc = "1Macc"
	/// 2 Maccabees
	case secondMacc = "2Macc"
	/// Job
	case job = "Job"
	/// Psalms
	case ps = "Ps"
	/// Proverbs
	case prov = "Prov"
	/// Ecclesiastes (Qohelet)
	case eccl = "Eccl"
	/// Song of Solomon (Canticle of Canticles)
	case song = "Song"
	/// Wisdom of Solomon
	case wis = "Wis"
	/// Sirach (Ecclesiasticus)
	case sir = "Sir"
	/// Isaiah
	case isa = "Isa"
	/// Jeremiah
	case jer = "Jer"
	/// Lamentations
	case lam = "Lam"
	/// Baruch
	case bar = "Bar"
	/// Letter of Jeremiah
	case epJer = "EpJer"
	/// Ezekiel
	case ezek = "Ezek"
	/// Daniel
	case dan = "Dan"
	/// Hosea
	case hos = "Hos"
	/// Joel
	case joel = "Joel"
	/// Amos
	case amos = "Amos"
	/// Obadiah
	case obad = "Obad"
	/// Jonah
	case jonah = "Jonah"
	/// Micah
	case mic = "Mic"
	/// Nahum
	case nah = "Nah"
	/// Habakkuk
	case hab = "Hab"
	/// Zephaniah
	case zeph = "Zeph"
	/// Haggai
	case hag = "Hag"
	/// Zechariah
	case zech = "Zech"
	/// Malachi
	case mal = "Mal"
	/// Matthew
	case matt = "Matt"
	/// Mark
	case mark = "Mark"
	/// Luke
	case luke = "Luke"
	/// John
	case john = "John"
	/// Acts
	case acts = "Acts"
	/// Romans
	case rom = "Rom"
	/// 1 Corinthians
	case firstCor = "1Cor"
	/// 2 Corinthians
	case secondCor = "2Cor"
	/// Galatians
	case gal = "Gal"
	/// Ephesians
	case eph = "Eph"
	/// Philippians
	case phil = "Phil"
	/// Colossians
	case col = "Col"
	/// 1 Thessalonians
	case firstThess = "1Thess"
	/// 2 Thessalonians
	case secondThess = "2Thess"
	/// 1 Timothy
	case firstTim = "1Tim"
	/// 2 Timothy
	case secondTim = "2Tim"
	/// Titus
	case titus = "Titus"
	/// Philemon
	case phlm = "Phlm"
	/// Hebrews
	case heb = "Heb"
	/// James
	case jas = "Jas"
	/// 1 Peter
	case firstPet = "1Pet"
	/// 2 Peter
	case secondPet = "2Pet"
	/// 1 John
	case firstJohn = "1John"
	/// 2 John
	case secondJohn = "2John"
	/// 3 John
	case thirdJohn = "3John"
	/// Jude
	case jude = "Jude"
	/// Revelation
	case rev = "Rev"
}

/// Calendar year context for date boundaries.
/// 
/// Determines how the calendar year is structured and which dates are included
/// in a given year's calendar output.
public enum CalendarContext: String, Codable, Equatable, Hashable, Sendable {
	/// Gregorian year (January 1 to December 31)
	case gregorian = "GREGORIAN"
	/// Liturgical year (first Sunday of Advent to the day before the first Sunday of Advent of the next year)
	case liturgical = "LITURGICAL"
}

/// Date function for calculating liturgical dates.
/// 
/// Represents movable feasts and special celebrations that require calculation
/// based on Easter or other variable dates.
public enum DateFn: String, Codable, Equatable, Hashable, Sendable {
	/// Monday after Pentecost.
	case maryMotherOfTheChurch = "MARY_MOTHER_OF_THE_CHURCH"
	/// Sunday between January 2 and 8 (or January 6 if not transferred).
	case epiphanySunday = "EPIPHANY_SUNDAY"
	/// February 2 (Candlemas).
	case presentationOfTheLord = "PRESENTATION_OF_THE_LORD"
	/// March 25 (may be transferred if in Holy Week or Easter Octave).
	case annunciation = "ANNUNCIATION"
	/// Sunday before Easter.
	case palmSunday = "PALM_SUNDAY"
	/// First Sunday after the Paschal Full Moon.
	case easterSunday = "EASTER_SUNDAY"
	/// Second Sunday of Easter.
	case divineMercySunday = "DIVINE_MERCY_SUNDAY"
	/// Saturday after the Second Sunday after Pentecost.
	case immaculateHeartOfMary = "IMMACULATE_HEART_OF_MARY"
	/// Seventh Sunday after Easter.
	case pentecostSunday = "PENTECOST_SUNDAY"
	/// Thursday or Sunday after Trinity Sunday.
	case corpusChristiSunday = "CORPUS_CHRISTI_SUNDAY"
	/// June 24.
	case nativityOfJohnTheBaptist = "NATIVITY_OF_JOHN_THE_BAPTIST"
	/// June 29.
	case peterAndPaulApostles = "PETER_AND_PAUL_APOSTLES"
	/// August 6.
	case transfiguration = "TRANSFIGURATION"
	/// August 15.
	case assumption = "ASSUMPTION"
	/// September 14.
	case exaltationOfTheHolyCross = "EXALTATION_OF_THE_HOLY_CROSS"
	/// November 1.
	case allSaints = "ALL_SAINTS"
	/// December 8.
	case immaculateConceptionOfMary = "IMMACULATE_CONCEPTION_OF_MARY"
}

/// Liturgical cycle for lectionary readings
/// Includes both actual cycles (Year A, B, C, etc.) and invariant content
public enum LiturgicalCycle: String, Codable, Equatable, Hashable, Sendable {
	/// Invariant content that applies to all cycles
	case invariant
	/// Year A of the Sunday cycle
	case yearA = "year_a"
	/// Year B of the Sunday cycle
	case yearB = "year_b"
	/// Year C of the Sunday cycle
	case yearC = "year_c"
	/// Combined years A and B of the Sunday cycle
	case yearAB = "year_a_b"
	/// Combined years A and C of the Sunday cycle
	case yearAC = "year_a_c"
	/// Combined years B and C of the Sunday cycle
	case yearBC = "year_b_c"
	/// Year 1 of the weekday cycle (Cycle I)
	case year1 = "year_1"
	/// Year 2 of the weekday cycle (Cycle II)
	case year2 = "year_2"
}

/// Parts that make up the Mass celebration.
/// Each part represents a specific element of the liturgical celebration.
public enum MassPart: String, Codable, Equatable, Hashable, Sendable {
	/// Messianic entry reading (during the procession with palms, before the Mass of the Passion)
	case messianicEntry = "messianic_entry"
	/// Entrance Antiphon - opening chant of the Mass
	case entranceAntiphon = "entrance_antiphon"
	/// Collect - opening prayer of the Mass
	case collect
	/// Reading 1 - first reading (usually from the Old Testament)
	case reading1 = "reading_1"
	/// Psalm - responsorial psalm
	case psalm
	/// Canticle - biblical canticle
	case canticle
	/// Reading 2 - second reading (usually from the New Testament)
	case reading2 = "reading_2"
	/// Psalm (Easter Vigil)
	case easterVigilPsalm2 = "easter_vigil_psalm_2"
	/// Reading 3 - third reading (Easter Vigil)
	case easterVigilReading3 = "easter_vigil_reading_3"
	/// Canticle 3 (Easter Vigil)
	case easterVigilCanticle3 = "easter_vigil_canticle_3"
	/// Reading 4 - fourth reading (Easter Vigil)
	case easterVigilReading4 = "easter_vigil_reading_4"
	/// Psalm 4 (Easter Vigil)
	case easterVigilPsalm4 = "easter_vigil_psalm_4"
	/// Reading 5 - fifth reading (Easter Vigil)
	case easterVigilReading5 = "easter_vigil_reading_5"
	/// Canticle 5 (Easter Vigil)
	case easterVigilCanticle5 = "easter_vigil_canticle_5"
	/// Reading 6 - sixth reading (Easter Vigil)
	case easterVigilReading6 = "easter_vigil_reading_6"
	/// Psalm 6 (Easter Vigil)
	case easterVigilPsalm6 = "easter_vigil_psalm_6"
	/// Reading 7 - seventh reading (Easter Vigil)
	case easterVigilReading7 = "easter_vigil_reading_7"
	/// Psalm 7 (Easter Vigil)
	case easterVigilPsalm7 = "easter_vigil_psalm_7"
	/// Epistle - reading from the epistles (Easter Vigil)
	case easterVigilEpistle = "easter_vigil_epistle"
	/// Sequence - special chant on certain feasts
	case sequence
	/// Alleluia - acclamation before the Gospel
	case alleluia
	/// Gospel - reading from the Gospels
	case gospel
	/// Prayer over the Offerings - prayer during the offertory
	case prayerOverTheOfferings = "prayer_over_the_offerings"
	/// Preface - introduction to the Eucharistic Prayer
	case preface
	/// Communion Antiphon - chant during communion
	case communionAntiphon = "communion_antiphon"
	/// Prayer after Communion - concluding prayer
	case prayerAfterCommunion = "prayer_after_communion"
	/// Solemn Blessing - special blessing on certain occasions
	case solemnBlessing = "solemn_blessing"
	/// Prayer over the People - blessing over the congregation
	case prayerOverThePeople = "prayer_over_the_people"
}

/// Combined Sunday cycle for cases where readings can apply to multiple years.
/// This allows for flexible configuration where the same readings can be used
/// across different combinations of Sunday cycles.
public enum SundayCycleCombined: String, Codable, Equatable, Hashable, Sendable {
	/// Years A and B combined
	case yearAB = "YEAR_A_B"
	/// Years A and C combined
	case yearAC = "YEAR_A_C"
	/// Years B and C combined
	case yearBC = "YEAR_B_C"
}
