service: romcal-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  # Optional: Each function instance below will have the same code, but they'll be segmented for metrics purposes.
  getCalendar:
    handler: index.handler
    events:
      - http: 'GET /calendar/{proxy+}'
  getLiturgicalCalendar:
    handler: index.handler
    events:
      - http: 'GET /liturgical-calendar/{proxy+}'
  getCalendars:
    handler: index.handler
    events:
      - http: 'GET /calendars'
  getLocales:
    handler: index.handler
    events:
      - http: 'GET /locales'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
