const LiturgicalSeasons = {
  "ADVENT": "ADVENT",
  "CHRISTMASTIDE": "CHRISTMASTIDE",
  "EARLY_ORDINARY_TIME": "EARLY_ORDINARY_TIME",
  "LATER_ORDINARY_TIME": "LATER_ORDINARY_TIME",
  "LENT": "LENT",
  "HOLY_WEEK": "HOLY_WEEK",
  "EASTER": "EASTER"
};

export default LiturgicalSeasons;
