use std::collections::HashSet;
use std::fs;
use std::process::Command;

// Constants for paths
const CALENDARS_DIR: &str = "../data/calendars";
const RESOURCES_DIR: &str = "../data/resources";
const OUTPUT_FILE: &str = "src/generated_constants.rs";

// Define simplified types for build script (without serde dependencies)
#[derive(Debug, Clone)]
struct CalendarInfo {
    id: String,
    parent_calendar_ids: Vec<String>,
}

#[derive(Debug, Clone)]
struct CalendarTreeNode {
    id: String,
    children: Vec<CalendarTreeNode>,
}

impl CalendarTreeNode {
    fn new(id: String) -> Self {
        Self {
            id,
            children: Vec::new(),
        }
    }

    fn add_child(&mut self, child: CalendarTreeNode) {
        self.children.push(child);
    }
}

fn build_calendar_tree(calendars: &[CalendarInfo]) -> CalendarTreeNode {
    // Create a map of calendar ID to CalendarInfo for quick lookup
    let calendar_map: std::collections::HashMap<String, &CalendarInfo> =
        calendars.iter().map(|cal| (cal.id.clone(), cal)).collect();

    // Find the root calendar (general_roman)
    let root_calendar = calendar_map
        .get("general_roman")
        .expect("general_roman calendar not found");

    // Build the tree recursively
    build_tree_recursive(root_calendar, calendars, &calendar_map)
}

fn build_tree_recursive(
    current: &CalendarInfo,
    all_calendars: &[CalendarInfo],
    _calendar_map: &std::collections::HashMap<String, &CalendarInfo>,
) -> CalendarTreeNode {
    let mut node = CalendarTreeNode::new(current.id.clone());

    // Find all calendars that have this calendar as their most specific parent
    // (i.e., the last element in their parent_calendar_ids list)
    for calendar in all_calendars {
        if let Some(last_parent) = calendar.parent_calendar_ids.last() {
            if last_parent == &current.id {
                let child_node = build_tree_recursive(calendar, all_calendars, _calendar_map);
                node.add_child(child_node);
            }
        }
    }

    // Sort children alphabetically by ID
    node.children.sort_by(|a, b| a.id.cmp(&b.id));

    node
}

fn generate_constants() {
    println!("cargo:info=Generating constants from JSON files...");

    // Collect calendar information (ID and parent relationships)
    let mut calendar_infos = Vec::new();
    collect_calendar_infos_recursively(CALENDARS_DIR, &mut calendar_infos);

    // Collect locales from JSON "locale" property
    let mut locales = HashSet::new();
    collect_locale_codes_recursively(RESOURCES_DIR, &mut locales);

    // Extract calendar IDs and sort them
    let mut calendar_ids: Vec<String> = calendar_infos.iter().map(|info| info.id.clone()).collect();
    calendar_ids.sort();

    // Convert locales to sorted vector
    let mut locales: Vec<String> = locales.into_iter().collect();
    locales.sort();

    // Build calendar tree
    let calendar_tree = build_calendar_tree(&calendar_infos);

    // Generate the constants file
    let calendar_constants = calendar_ids
        .iter()
        .map(|id| format!("    \"{}\",", id))
        .collect::<Vec<_>>()
        .join("\n");

    let locale_constants = locales
        .iter()
        .map(|locale| format!("    \"{}\",", locale))
        .collect::<Vec<_>>()
        .join("\n");

    // Generate calendar tree constant
    let calendar_tree_constant = generate_calendar_tree_constant(&calendar_tree);

    let mut content = String::new();
    content.push_str("//! Auto-generated constants - Do not modify manually\n");
    content.push_str("//! This file is generated by build.rs\n\n");

    content.push_str("/// List of all calendar IDs\n");
    content.push_str("///\n");
    content.push_str("/// This constant contains all calendar IDs\n");
    content.push_str("/// in the romcal project, sorted alphabetically.\n");
    content.push_str("pub const CALENDAR_IDS: &[&str] = &[\n");
    content.push_str(&calendar_constants);
    content.push_str("\n\n];\n\n");

    content.push_str("/// List of all locale codes\n");
    content.push_str("///\n");
    content.push_str("/// This constant contains all locale codes\n");
    content.push_str("/// in the romcal project, sorted alphabetically.\n");
    content.push_str("pub const LOCALE_CODES: &[&str] = &[\n");
    content.push_str(&locale_constants);
    content.push_str("\n\n];\n\n");

    content.push_str("/// Calendar tree structure as JSON\n");
    content.push_str("///\n");
    content.push_str("/// This constant contains the hierarchical structure\n");
    content.push_str("/// of all calendars in the romcal project as a JSON string.\n");
    content.push_str("pub const CALENDAR_TREE_JSON: &str = r#\"");
    content.push_str(&calendar_tree_constant);
    content.push_str("\"#;\n");

    fs::write(OUTPUT_FILE, content).expect("Failed to write constants file");

    // Format the generated file with rustfmt
    format_generated_file(OUTPUT_FILE);

    println!(
        "cargo:info=Constants generated successfully: {} calendars, {} locales",
        calendar_ids.len(),
        locales.len()
    );
}

fn collect_calendar_infos_recursively(dir: &str, infos: &mut Vec<CalendarInfo>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // Recursively search subdirectories
                if let Some(dir_str) = path.to_str() {
                    collect_calendar_infos_recursively(dir_str, infos);
                }
            } else if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if name.ends_with(".json") {
                    if let Ok(content) = fs::read_to_string(&path) {
                        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                            if let Some(id) = json.get("id").and_then(|v| v.as_str()) {
                                let mut parent_calendar_ids = json
                                    .get("parent_calendar_ids")
                                    .and_then(|v| v.as_array())
                                    .map(|arr| {
                                        arr.iter()
                                            .filter_map(|v| v.as_str())
                                            .map(|s| s.to_string())
                                            .collect::<Vec<String>>()
                                    })
                                    .unwrap_or_default();

                                // Add "general_roman" as first parent systematically, except if the current calendar is already general_roman
                                if id != "general_roman" {
                                    parent_calendar_ids.insert(0, "general_roman".to_string());
                                }

                                infos.push(CalendarInfo {
                                    id: id.to_string(),
                                    parent_calendar_ids,
                                });
                            }
                        }
                    }
                }
            }
        }
    }
}

fn collect_locale_codes_recursively(dir: &str, locales: &mut HashSet<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // Recursively search subdirectories
                if let Some(dir_str) = path.to_str() {
                    collect_locale_codes_recursively(dir_str, locales);
                }
            } else if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if name.ends_with(".json") {
                    if let Ok(content) = fs::read_to_string(&path) {
                        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                            if let Some(locale) = json.get("locale").and_then(|v| v.as_str()) {
                                locales.insert(locale.to_string());
                            }
                        }
                    }
                }
            }
        }
    }
}

fn generate_calendar_tree_constant(tree: &CalendarTreeNode) -> String {
    generate_tree_node_json(tree)
}

fn generate_tree_node_json(node: &CalendarTreeNode) -> String {
    if node.children.is_empty() {
        format!(r#"{{"id":"{}","children":[]}}"#, node.id)
    } else {
        let children_json = node
            .children
            .iter()
            .map(generate_tree_node_json)
            .collect::<Vec<_>>()
            .join(",");

        format!(r#"{{"id":"{}","children":[{}]}}"#, node.id, children_json)
    }
}

fn format_generated_file(file_path: &str) {
    println!("cargo:info=Formatting generated file with rustfmt...");

    let output = Command::new("rustfmt").arg(file_path).output();

    match output {
        Ok(output) => {
            if output.status.success() {
                println!("cargo:info=File formatted with rustfmt");
            } else {
                println!(
                    "cargo:warning=Warning: rustfmt failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                );
            }
        }
        Err(_) => {
            println!("cargo:warning=Warning: rustfmt not found, skipping formatting");
        }
    }
}

fn main() {
    generate_constants();
    println!("cargo:rerun-if-changed={}", CALENDARS_DIR);
    println!("cargo:rerun-if-changed={}", RESOURCES_DIR);
}
