export type AllTypes = Definition | Precedence;

export type Definition = {
    $schema?:          null | string;
    days_definitions?: DayDefinition[];
    /**
     * The unique identifier of the entity
     */
    id?: string;
    /**
     * Metadata of the resources
     */
    metadata?:            ResourcesMetadata | null;
    parent_calendar_ids?: string[];
    particular_config?:   ParticularConfig | null;
    /**
     * Entities of the resources: a person, a place, an event, etc.
     */
    entities?: EntityDefinition[] | null;
    /**
     * Locale code of the resources, in BCP-47 IETF tag format
     */
    locale?: string;
    /**
     * In addition to this liturgical day, allow similar items that have the same rank,
     * and the same or lower precedence,
     * so the current liturgical day will not overwrite another defined item.
     */
    allow_similar_rank_items?: boolean | null;
    /**
     * The liturgical color(s) of the liturgical day.
     * @deprecated
     */
    colors?: ColorsDef;
    /**
     * The **Common** refers to a set of prayers, readings, and chants used for celebrating
     * saints or
     * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the
     * Blessed
     * Virgin Mary.
     */
    commons_def?: CommonsDef;
    /**
     * Specify a custom locale ID for this date definition, in this calendar.
     */
    custom_locale_id?: null | string;
    /**
     * Date definition
     */
    date_def?: DateDefClass | null;
    /**
     * Date definition exception
     */
    date_exceptions?: DateExceptions;
    /**
     * If this liturgical day must be removed from this calendar and from all those it inherits
     * (the parent calendars), on the final calendar generated by romcal.
     */
    drop?: boolean | null;
    /**
     * Holy days of obligation are days on which the faithful are expected to attend Mass,
     * and engage in rest from work and recreation.
     */
    is_holy_day_of_obligation?: boolean | null;
    /**
     * Specify is this LiturgicalDay is optional within a specific liturgical calendar.
     *
     * UNLY #14:
     * Memorials are either obligatory or optional; their observance is integrated into
     * the celebration of the occurring weekday in accordance with the norms set forth in the
     * General Instruction of the Roman Missal and of the Liturgy of the Hours
     *
     * Note: also used for the dedication of consecrated churches, which is an optional
     * solemnity
     * that should not overwrite the default weekday.
     */
    is_optional?: boolean | null;
    /**
     * Link one or multiple Saints, Blessed, or any other celebrations from the Martyrology
     * catalog.
     */
    martyrology?: MartyrologyItemPointer[] | null;
    /**
     * The precedence type of the liturgical day.
     */
    precedence?: Precedence | null;
    /**
     * Combined titles of each Saints linked to this date definition.
     *
     * Titles of the Saint or the Blessed
     */
    titles?: TitlesDef;
    /**
     * Internal notes
     * @private
     */
    _todo?: string[] | null;
    /**
     * The canonization level of a person.
     */
    canonization_level?: CanonizationLevel | null;
    /**
     * Number of person that this definition represent.
     * It could be set as 'many' if the number is not defined.
     */
    count?: CountUnion;
    /**
     * Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD'
     * format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_beatification?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_beatification_is_approximative?: boolean | null;
    /**
     * Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_birth?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_birth_is_approximative?: boolean | null;
    /**
     * Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_canonization?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_canonization_is_approximative?: boolean | null;
    /**
     * Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_death?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_death_is_approximative?: boolean | null;
    /**
     * Date of Dedication of a church, basilica, or cathedral (or other place of worship),
     * as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_dedication?: DateOfBeatificationUnion;
    /**
     * The full name of the entity.
     */
    fullname?: null | string;
    /**
     * Specify if the canonization level should not be displayed.
     * It's generally the case when the canonization are already included in the name.
     */
    hide_canonization_level?: boolean | null;
    /**
     * Specify if the titles should not be displayed.
     * It's generally the case when titles are already included in the name.
     */
    hide_titles?: boolean | null;
    /**
     * The short name of the entity, without the canonization level and titles.
     */
    name?: null | string;
    /**
     * Determine if the Saint or the Blessed is a male or a female.
     */
    sex?: Sex | null;
    /**
     * Sources for the information about this entity
     */
    sources?: string[] | null;
    /**
     * The type of the entity.
     * @default EntityType.Person
     */
    type?: EntityType | null;
}

export enum CanonizationLevel {
    Blessed = "BLESSED",
    Saint = "SAINT",
}

/**
 * The liturgical color(s) of the liturgical day.
 * @deprecated
 */
export type ColorsDef = Color[] | Color | null;

/**
 * Liturgical colors used in the celebration of Mass and other liturgical services
 */
export enum Color {
    Black = "BLACK",
    Gold = "GOLD",
    Green = "GREEN",
    Purple = "PURPLE",
    Red = "RED",
    Rose = "ROSE",
    White = "WHITE",
}

/**
 * The **Common** refers to a set of prayers, readings, and chants used for celebrating
 * saints or
 * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the
 * Blessed
 * Virgin Mary.
 */
export type CommonsDef = CommonDefinition[] | CommonDefinition | null;

/**
 * Common definition for simplified categorization
 */
export enum CommonDefinition {
    Abbots = "ABBOTS",
    Bishops = "BISHOPS",
    BlessedVirginMary = "BLESSED_VIRGIN_MARY",
    DedicationAnniversaryInside = "DEDICATION_ANNIVERSARY__INSIDE",
    DedicationAnniversaryOutside = "DEDICATION_ANNIVERSARY__OUTSIDE",
    DoctorsOfTheChurch = "DOCTORS_OF_THE_CHURCH",
    Educators = "EDUCATORS",
    Founders = "FOUNDERS",
    HolyWomen = "HOLY_WOMEN",
    Martyrs = "MARTYRS",
    MercyWorkers = "MERCY_WORKERS",
    Missionaries = "MISSIONARIES",
    MissionaryMartyrs = "MISSIONARY_MARTYRS",
    Monks = "MONKS",
    None = "NONE",
    Nuns = "NUNS",
    Pastors = "PASTORS",
    Popes = "POPES",
    Religious = "RELIGIOUS",
    Saints = "SAINTS",
    VirginMartyrs = "VIRGIN_MARTYRS",
    Virgins = "VIRGINS",
    WomanMartyrs = "WOMAN_MARTYRS",
}

export type CountUnion = CountEnum | number | null;

export enum CountEnum {
    Many = "MANY",
}

/**
 * Simple month/day
 *
 * Date function (Easter, Epiphany, etc.)
 *
 * Nth weekday of month
 *
 * Last weekday of month
 */
export type DateDefClass = {
    date?:                      number;
    day_offset?:                number | null;
    month?:                     number;
    date_fn?:                   DateFn;
    day_of_week?:               number;
    nth_week_in_month?:         number;
    last_day_of_week_in_month?: number;
}

/**
 * Date function for calculating liturgical dates
 */
export enum DateFn {
    AllSaints = "ALL_SAINTS",
    Annunciation = "ANNUNCIATION",
    Assumption = "ASSUMPTION",
    CorpusChristiSunday = "CORPUS_CHRISTI_SUNDAY",
    DivineMercySunday = "DIVINE_MERCY_SUNDAY",
    EasterSunday = "EASTER_SUNDAY",
    EpiphanySunday = "EPIPHANY_SUNDAY",
    ExaltationOfTheHolyCross = "EXALTATION_OF_THE_HOLY_CROSS",
    ImmaculateConceptionOfMary = "IMMACULATE_CONCEPTION_OF_MARY",
    ImmaculateHeartOfMary = "IMMACULATE_HEART_OF_MARY",
    MaryMotherOfTheChurch = "MARY_MOTHER_OF_THE_CHURCH",
    NativityOfJohnTheBaptist = "NATIVITY_OF_JOHN_THE_BAPTIST",
    PalmSunday = "PALM_SUNDAY",
    PentecostSunday = "PENTECOST_SUNDAY",
    PeterAndPaulApostles = "PETER_AND_PAUL_APOSTLES",
    PresentationOfTheLord = "PRESENTATION_OF_THE_LORD",
    Transfiguration = "TRANSFIGURATION",
}

/**
 * Date definition exception
 */
export type DateExceptions = DateDefException[] | DateDefException | null;

/**
 * The liturgical day date exception
 * Represents a condition and the date to set when that condition is met
 */
export type DateDefException = {
    /**
     * Date to set when condition is met
     */
    then: DateDefExtended;
    /**
     * Condition that triggers the exception
     */
    when: ExceptionCondition;
}

/**
 * Date to set when condition is met
 *
 * Simple month/day
 *
 * Date function (Easter, Epiphany, etc.)
 *
 * Nth weekday of month
 *
 * Last weekday of month
 */
export type DateDefExtended = {
    date?:                      number;
    day_offset?:                number | null;
    month?:                     number;
    date_fn?:                   DateFn;
    day_of_week?:               number;
    nth_week_in_month?:         number;
    last_day_of_week_in_month?: number;
}

/**
 * Condition that triggers the exception
 *
 * Exception conditions that can trigger a date change
 *
 * If date is between two dates
 *
 * If date is same as another date
 *
 * If date is a specific day of week
 */
export type ExceptionCondition = {
    from?:        DateDef;
    inclusive?:   boolean;
    to?:          DateDef;
    date?:        DateDef;
    day_of_week?: number;
}

/**
 * Simple month/day
 *
 * Date function (Easter, Epiphany, etc.)
 *
 * Nth weekday of month
 *
 * Last weekday of month
 */
export type DateDef = {
    date?:                      number;
    day_offset?:                number | null;
    month?:                     number;
    date_fn?:                   DateFn;
    day_of_week?:               number;
    nth_week_in_month?:         number;
    last_day_of_week_in_month?: number;
}

export type DateOfBeatificationUnion = SaintDateDef | number | null | string;

export type SaintDateDef = {
    between?: SaintDate[];
    or?:      SaintDate[];
    century?: number;
}

export type SaintDate = number | string;

export type DayDefinition = {
    /**
     * In addition to this liturgical day, allow similar items that have the same rank,
     * and the same or lower precedence,
     * so the current liturgical day will not overwrite another defined item.
     */
    allow_similar_rank_items?: boolean | null;
    /**
     * The liturgical color(s) of the liturgical day.
     * @deprecated
     */
    colors?: ColorsDef;
    /**
     * The **Common** refers to a set of prayers, readings, and chants used for celebrating
     * saints or
     * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the
     * Blessed
     * Virgin Mary.
     */
    commons_def?: CommonsDef;
    /**
     * Specify a custom locale ID for this date definition, in this calendar.
     */
    custom_locale_id?: null | string;
    /**
     * Date definition
     */
    date_def?: DateDefClass | null;
    /**
     * Date definition exception
     */
    date_exceptions?: DateExceptions;
    /**
     * If this liturgical day must be removed from this calendar and from all those it inherits
     * (the parent calendars), on the final calendar generated by romcal.
     */
    drop?: boolean | null;
    id:    string;
    /**
     * Holy days of obligation are days on which the faithful are expected to attend Mass,
     * and engage in rest from work and recreation.
     */
    is_holy_day_of_obligation?: boolean | null;
    /**
     * Specify is this LiturgicalDay is optional within a specific liturgical calendar.
     *
     * UNLY #14:
     * Memorials are either obligatory or optional; their observance is integrated into
     * the celebration of the occurring weekday in accordance with the norms set forth in the
     * General Instruction of the Roman Missal and of the Liturgy of the Hours
     *
     * Note: also used for the dedication of consecrated churches, which is an optional
     * solemnity
     * that should not overwrite the default weekday.
     */
    is_optional?: boolean | null;
    /**
     * Link one or multiple Saints, Blessed, or any other celebrations from the Martyrology
     * catalog.
     */
    martyrology?: MartyrologyItemPointer[] | null;
    /**
     * The precedence type of the liturgical day.
     */
    precedence?: Precedence | null;
    /**
     * Combined titles of each Saints linked to this date definition.
     */
    titles?: TitlesDef;
}

export type MartyrologyItemPointer = MartyrologyItemRedefined | string;

export type MartyrologyItemRedefined = {
    /**
     * Specify the number of persons this martyrology item is representing.
     */
    count?: CountUnion;
    /**
     * Specify if titles should not be displayed. This can occur when a title is already
     * included in
     * the name of the martyrology item.
     */
    hide_titles?: boolean | null;
    /**
     * The ID of the martyrology item.
     */
    id: string;
    /**
     * The redefined titles of the martyrology item.
     */
    titles?: TitlesDef;
}

export type TitlesDef = Title[] | CompoundTitle | null;

/**
 * Titles and patronages associated with saints and blessed
 */
export enum Title {
    Abbess = "ABBESS",
    Abbot = "ABBOT",
    Apostle = "APOSTLE",
    Archangel = "ARCHANGEL",
    Bishop = "BISHOP",
    CopatronOfCanada = "COPATRON_OF_CANADA",
    CopatronOfEurope = "COPATRON_OF_EUROPE",
    CopatronOfIreland = "COPATRON_OF_IRELAND",
    CopatronessOfEurope = "COPATRONESS_OF_EUROPE",
    CopatronessOfFrance = "COPATRONESS_OF_FRANCE",
    CopatronessOfIreland = "COPATRONESS_OF_IRELAND",
    CopatronessOfItalyAndEurope = "COPATRONESS_OF_ITALY_AND_EUROPE",
    CopatronessOfThePhilippines = "COPATRONESS_OF_THE_PHILIPPINES",
    Deacon = "DEACON",
    DoctorOfTheChurch = "DOCTOR_OF_THE_CHURCH",
    Empress = "EMPRESS",
    Evangelist = "EVANGELIST",
    FirstBishop = "FIRST_BISHOP",
    Hermit = "HERMIT",
    King = "KING",
    Martyr = "MARTYR",
    Missionary = "MISSIONARY",
    Monk = "MONK",
    MotherAndQueenOfChile = "MOTHER_AND_QUEEN_OF_CHILE",
    ParentsOfTheBlessedVirginMary = "PARENTS_OF_THE_BLESSED_VIRGIN_MARY",
    Patriarch = "PATRIARCH",
    PatronOfCanada = "PATRON_OF_CANADA",
    PatronOfEngland = "PATRON_OF_ENGLAND",
    PatronOfEurope = "PATRON_OF_EUROPE",
    PatronOfFrance = "PATRON_OF_FRANCE",
    PatronOfIreland = "PATRON_OF_IRELAND",
    PatronOfItaly = "PATRON_OF_ITALY",
    PatronOfOceania = "PATRON_OF_OCEANIA",
    PatronOfPoland = "PATRON_OF_POLAND",
    PatronOfRussia = "PATRON_OF_RUSSIA",
    PatronOfScotland = "PATRON_OF_SCOTLAND",
    PatronOfSpain = "PATRON_OF_SPAIN",
    PatronOfTheCityOfLyon = "PATRON_OF_THE_CITY_OF_LYON",
    PatronOfTheClergyOfTheArchdioceseOfLyon = "PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON",
    PatronOfTheCzechNation = "PATRON_OF_THE_CZECH_NATION",
    PatronOfTheDiocese = "PATRON_OF_THE_DIOCESE",
    PatronOfWales = "PATRON_OF_WALES",
    PatronessOfAlsace = "PATRONESS_OF_ALSACE",
    PatronessOfArgentina = "PATRONESS_OF_ARGENTINA",
    PatronessOfBrazil = "PATRONESS_OF_BRAZIL",
    PatronessOfCostaRica = "PATRONESS_OF_COSTA_RICA",
    PatronessOfHungary = "PATRONESS_OF_HUNGARY",
    PatronessOfPuertoRico = "PATRONESS_OF_PUERTO_RICO",
    PatronessOfSlovakia = "PATRONESS_OF_SLOVAKIA",
    PatronessOfTheAmericas = "PATRONESS_OF_THE_AMERICAS",
    PatronessOfThePhilippines = "PATRONESS_OF_THE_PHILIPPINES",
    PatronessOfTheProvinceOfQuebec = "PATRONESS_OF_THE_PROVINCE_OF_QUEBEC",
    PatronessOfTheUsa = "PATRONESS_OF_THE_USA",
    Pilgrim = "PILGRIM",
    Pope = "POPE",
    Priest = "PRIEST",
    PrincipalPatronOfTheDiocese = "PRINCIPAL_PATRON_OF_THE_DIOCESE",
    Prophet = "PROPHET",
    ProtoMartyrOfOceania = "PROTO_MARTYR_OF_OCEANIA",
    Queen = "QUEEN",
    QueenOfPoland = "QUEEN_OF_POLAND",
    Religious = "RELIGIOUS",
    SecondPatronOfTheDiocese = "SECOND_PATRON_OF_THE_DIOCESE",
    SlavicMissionary = "SLAVIC_MISSIONARY",
    SpouseOfTheBlessedVirginMary = "SPOUSE_OF_THE_BLESSED_VIRGIN_MARY",
    TheFirstMartyr = "THE_FIRST_MARTYR",
    Virgin = "VIRGIN",
}

export type CompoundTitle = {
    /**
     * Add title(s) to the end of the existing list of title(s).
     */
    append?: Title[] | null;
    /**
     * Add title(s) to the beginning of the existing list of title(s).
     */
    prepend?: Title[] | null;
}

/**
 * Liturgical precedence levels for determining which celebration takes priority
 */
export enum Precedence {
    AshWednesday2 = "ASH_WEDNESDAY_2",
    CommemorationOfAllTheFaithfulDeparted3 = "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3",
    GeneralFeast7 = "GENERAL_FEAST_7",
    GeneralLordFeast5 = "GENERAL_LORD_FEAST_5",
    GeneralMemorial10 = "GENERAL_MEMORIAL_10",
    GeneralSolemnity3 = "GENERAL_SOLEMNITY_3",
    OptionalMemorial12 = "OPTIONAL_MEMORIAL_12",
    PrivilegedSunday2 = "PRIVILEGED_SUNDAY_2",
    PrivilegedWeekday9 = "PRIVILEGED_WEEKDAY_9",
    ProperFeast8F = "PROPER_FEAST_8F",
    ProperFeastDedicationOfTheCathedralChurch8B = "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B",
    ProperFeastPrincipalPatronOfADiocese8A = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A",
    ProperFeastPrincipalPatronOfARegion8C = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C",
    ProperFeastTitleOrFounderOrPrimaryPatronOfAReligiousOrg8D = "PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D",
    ProperFeastToAnIndividualChurch8E = "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E",
    ProperMemorial11B = "PROPER_MEMORIAL_11B",
    ProperMemorialSecondPatron11A = "PROPER_MEMORIAL__SECOND_PATRON_11A",
    ProperOfTimeSolemnity2 = "PROPER_OF_TIME_SOLEMNITY_2",
    ProperSolemnityDedicationOfTheOwnChurch4B = "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B",
    ProperSolemnityPrincipalPatron4A = "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A",
    ProperSolemnityTitleOfTheOwnChurch4C = "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C",
    ProperSolemnityTitleOrFounderOrPrimaryPatronOfAReligiousOrg4D = "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D",
    Triduum1 = "TRIDUUM_1",
    UnprivilegedSunday6 = "UNPRIVILEGED_SUNDAY_6",
    Weekday13 = "WEEKDAY_13",
    WeekdayOfEasterOctave2 = "WEEKDAY_OF_EASTER_OCTAVE_2",
    WeekdayOfHolyWeek2 = "WEEKDAY_OF_HOLY_WEEK_2",
}

export type EntityDefinition = {
    /**
     * Internal notes
     * @private
     */
    _todo?: string[] | null;
    /**
     * The canonization level of a person.
     */
    canonization_level?: CanonizationLevel | null;
    /**
     * Number of person that this definition represent.
     * It could be set as 'many' if the number is not defined.
     */
    count?: CountUnion;
    /**
     * Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD'
     * format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_beatification?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_beatification_is_approximative?: boolean | null;
    /**
     * Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_birth?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_birth_is_approximative?: boolean | null;
    /**
     * Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_canonization?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_canonization_is_approximative?: boolean | null;
    /**
     * Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_death?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_death_is_approximative?: boolean | null;
    /**
     * Date of Dedication of a church, basilica, or cathedral (or other place of worship),
     * as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_dedication?: DateOfBeatificationUnion;
    /**
     * The full name of the entity.
     */
    fullname?: null | string;
    /**
     * Specify if the canonization level should not be displayed.
     * It's generally the case when the canonization are already included in the name.
     */
    hide_canonization_level?: boolean | null;
    /**
     * Specify if the titles should not be displayed.
     * It's generally the case when titles are already included in the name.
     */
    hide_titles?: boolean | null;
    /**
     * The unique identifier of the entity
     */
    id: string;
    /**
     * The short name of the entity, without the canonization level and titles.
     */
    name?: null | string;
    /**
     * Determine if the Saint or the Blessed is a male or a female.
     */
    sex?: Sex | null;
    /**
     * Sources for the information about this entity
     */
    sources?: string[] | null;
    /**
     * Titles of the Saint or the Blessed
     */
    titles?: Title[] | null;
    /**
     * The type of the entity.
     * @default EntityType.Person
     */
    type?: EntityType | null;
}

export enum Sex {
    Female = "FEMALE",
    Male = "MALE",
}

export enum EntityType {
    Event = "EVENT",
    Person = "PERSON",
    Place = "PLACE",
}

export type ResourcesMetadata = {
    jurisdiction?: CalendarJurisdiction;
    type?:         CalendarType;
    colors?:       LocaleColors | null;
    cycles?:       CyclesMetadata | null;
    months?:       { [key: string]: string } | null;
    ordinals?:     { [key: string]: string } | null;
    periods?:      PeriodsMetadata | null;
    ranks?:        RanksMetadata | null;
    seasons?:      SeasonsMetadata | null;
    weekdays?:     { [key: string]: string } | null;
}

export type LocaleColors = {
    black?:  null | string;
    gold?:   null | string;
    green?:  null | string;
    purple?: null | string;
    red?:    null | string;
    rose?:   null | string;
    white?:  null | string;
}

export type CyclesMetadata = {
    proper_of_saints?: null | string;
    proper_of_time?:   null | string;
    psalter_week_1?:   null | string;
    psalter_week_2?:   null | string;
    psalter_week_3?:   null | string;
    psalter_week_4?:   null | string;
    sunday_year_a?:    null | string;
    sunday_year_b?:    null | string;
    sunday_year_c?:    null | string;
    weekday_year_1?:   null | string;
    weekday_year_2?:   null | string;
}

export enum CalendarJurisdiction {
    Civil = "CIVIL",
    Ecclesiastical = "ECCLESIASTICAL",
}

export type PeriodsMetadata = {
    epiphany?:  null | string;
    holy_week?: null | string;
}

export type RanksMetadata = {
    feast?:             null | string;
    memorial?:          null | string;
    optional_memorial?: null | string;
    solemnity?:         null | string;
    sunday?:            null | string;
    weekday?:           null | string;
}

export type SeasonsMetadata = {
    advent?:          AdventSeason | null;
    christmas_time?:  ChristmasTimeSeason | null;
    easter_time?:     EasterTimeSeason | null;
    lent?:            LentSeason | null;
    ordinary_time?:   OrdinaryTimeSeason | null;
    paschal_triduum?: PaschalTriduumSeason | null;
}

export type AdventSeason = {
    privileged_weekday?: null | string;
    season?:             null | string;
    sunday?:             null | string;
    weekday?:            null | string;
}

export type ChristmasTimeSeason = {
    after_epiphany?:                null | string;
    before_epiphany?:               null | string;
    day?:                           null | string;
    octave?:                        null | string;
    season?:                        null | string;
    second_sunday_after_christmas?: null | string;
}

export type EasterTimeSeason = {
    octave?:  null | string;
    season?:  null | string;
    sunday?:  null | string;
    weekday?: null | string;
}

export type LentSeason = {
    day_after_ash_wed?: null | string;
    holy_week_day?:     null | string;
    season?:            null | string;
    sunday?:            null | string;
    weekday?:           null | string;
}

export type OrdinaryTimeSeason = {
    season?:  null | string;
    sunday?:  null | string;
    weekday?: null | string;
}

export type PaschalTriduumSeason = {
    season?: null | string;
}

export enum CalendarType {
    Archdiocese = "ARCHDIOCESE",
    City = "CITY",
    Country = "COUNTRY",
    Diocese = "DIOCESE",
    GeneralCommunity = "GENERAL_COMMUNITY",
    GeneralRoman = "GENERAL_ROMAN",
    LocalCommunity = "LOCAL_COMMUNITY",
    Other = "OTHER",
    Parish = "PARISH",
    Region = "REGION",
    RegionalCommunity = "REGIONAL_COMMUNITY",
}

export type ParticularConfig = {
    /**
     * Configuration options specific to this calendar.
     * These settings can override or extend the default Romcal configuration or any parent
     * calendar
     * configuration.
     */
    ascension_on_sunday?:      boolean | null;
    corpus_christi_on_sunday?: boolean | null;
    easter_calculation_type?:  EasterCalculationType | null;
    epiphany_on_sunday?:       boolean | null;
}

/**
 * Gregorian calculation (default)
 *
 * Julian calculation converted to Gregorian
 */
export enum EasterCalculationType {
    Gregorian = "GREGORIAN",
    Julian = "JULIAN",
}
