/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RomcalTypes = CalendarDefinition | ResourcesDefinition | DayDefinition | EntityDefinition | Precedence;
export type ColorsDef = Colors | Colors[];
export type CommonsDef = CommonDefinition | CommonDefinition[];
export type DateDef =
  | {
      date: number;
      day_offset?: number | null;
      month: MonthIndex;
    }
  | {
      date_fn: DateFn;
      day_offset?: number | null;
    }
  | {
      day_of_week: DayOfWeek;
      day_offset?: number | null;
      month: MonthIndex;
      nth_week_in_month: number;
    }
  | {
      day_offset?: number | null;
      last_day_of_week_in_month: DayOfWeek;
      month: MonthIndex;
    };
/**
 * Month index (1-12) with automatic validation
 */
export type MonthIndex = number;
/**
 * Day of week (0-6, where 0=Sunday) with automatic validation
 */
export type DayOfWeek = number;
export type MartyrologyItemPointer = string | MartyrologyItemRedefined;
export type SaintCount = number | null;
export type TitlesDef = Title[] | CompoundTitle;
export type SaintDateDef =
  | SaintDate
  | {
      /**
       * @minItems 2
       * @maxItems 2
       */
      between: [SaintDate, SaintDate];
    }
  | {
      or: SaintDate[];
    }
  | {
      century: number;
    };
export type SaintDate = number | string;

export interface CalendarDefinition {
  $schema?: string | null;
  days_definitions: DayDefinition[];
  id: string;
  metadata: CalendarMetadata;
  parent_calendar_ids: string[];
  particular_config?: ParticularConfig | null;
}
export interface DayDefinition {
  /**
   * In addition to this liturgical day, allow similar items that have the same rank,
   * and the same or lower precedence,
   * so the current liturgical day will not overwrite another defined item.
   */
  allow_similar_rank_items?: boolean | null;
  /**
   * The liturgical color(s) of the liturgical day.
   * @deprecated
   */
  colors?: ColorsDef | null;
  /**
   * The **Common** refers to a set of prayers, readings, and chants used for celebrating saints or
   * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed
   * Virgin Mary.
   */
  commons_def?: CommonsDef | null;
  /**
   * Specify a custom locale ID for this date definition, in this calendar.
   */
  custom_locale_id?: string | null;
  /**
   * Date definition
   */
  date_def?: DateDef | null;
  /**
   * Date definition exception
   */
  date_exceptions?: DateDefException | DateDefException[] | null;
  /**
   * If this liturgical day must be removed from this calendar and from all those it inherits
   * (the parent calendars), on the final calendar generated by romcal.
   */
  drop?: boolean | null;
  id: string;
  /**
   * Holy days of obligation are days on which the faithful are expected to attend Mass,
   * and engage in rest from work and recreation.
   */
  is_holy_day_of_obligation?: boolean | null;
  /**
   * Specify is this LiturgicalDay is optional within a specific liturgical calendar.
   *
   * UNLY #14:
   * Memorials are either obligatory or optional; their observance is integrated into
   * the celebration of the occurring weekday in accordance with the norms set forth in the
   * General Instruction of the Roman Missal and of the Liturgy of the Hours
   *
   * Note: also used for the dedication of consecrated churches, which is an optional solemnity
   * that should not overwrite the default weekday.
   */
  is_optional?: boolean | null;
  /**
   * Link one or multiple Saints, Blessed, or any other celebrations from the Martyrology catalog.
   */
  martyrology?: MartyrologyItemPointer[] | null;
  /**
   * The precedence type of the liturgical day.
   */
  precedence?: Precedence | null;
  /**
   * Combined titles of each Saints linked to this date definition.
   */
  titles?: TitlesDef | null;
}
/**
 * The liturgical day date exception
 * Represents a condition and the date to set when that condition is met
 */
export interface DateDefException {
  /**
   * Date to set when condition is met
   */
  then: DateDef | DateDefWithOffset;
  /**
   * Condition that triggers the exception
   */
  when:
    | {
        from: DateDef;
        inclusive: boolean;
        to: DateDef;
      }
    | {
        date: DateDef;
      }
    | {
        day_of_week: DayOfWeek;
      };
}
export interface DateDefWithOffset {
  day_offset: number;
}
export interface MartyrologyItemRedefined {
  /**
   * Specify the number of persons this martyrology item is representing.
   */
  count?: SaintCount | null;
  /**
   * Specify if titles should not be displayed. This can occur when a title is already included in
   * the name of the martyrology item.
   */
  hide_titles?: boolean | null;
  /**
   * The ID of the martyrology item.
   */
  id: string;
  /**
   * The redefined titles of the martyrology item.
   */
  titles?: TitlesDef | null;
}
export interface CompoundTitle {
  /**
   * Add title(s) to the end of the existing list of title(s).
   */
  append?: Title[] | null;
  /**
   * Add title(s) to the beginning of the existing list of title(s).
   */
  prepend?: Title[] | null;
}
export interface CalendarMetadata {
  jurisdiction: CalendarJurisdiction;
  type: CalendarType;
}
export interface ParticularConfig {
  /**
   * Configuration options specific to this calendar.
   * These settings can override or extend the default Romcal configuration or any parent calendar
   * configuration.
   */
  ascension_on_sunday?: boolean | null;
  corpus_christi_on_sunday?: boolean | null;
  easter_calculation_type?: EasterCalculationType | null;
  epiphany_on_sunday?: boolean | null;
}
export interface ResourcesDefinition {
  $schema?: string | null;
  /**
   * Entities of the resources: a person, a place, an event, etc.
   */
  entities?: EntityDefinition[] | null;
  /**
   * Locale code of the resources, in BCP-47 IETF tag format
   */
  locale: string;
  /**
   * Metadata of the resources
   */
  metadata?: ResourcesMetadata | null;
}
export interface EntityDefinition {
  /**
   * Internal notes
   * @private
   */
  _todo?: string[] | null;
  /**
   * The canonization level of a person.
   */
  canonization_level?: CanonizationLevel | null;
  /**
   * Number of person that this definition represent.
   * It could be set as 'many' if the number is not defined.
   */
  count?: SaintCount | null;
  /**
   * Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_beatification?: SaintDateDef | null;
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_beatification_is_approximative?: boolean | null;
  /**
   * Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_birth?: SaintDateDef | null;
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_birth_is_approximative?: boolean | null;
  /**
   * Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_canonization?: SaintDateDef | null;
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_canonization_is_approximative?: boolean | null;
  /**
   * Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_death?: SaintDateDef | null;
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_death_is_approximative?: boolean | null;
  /**
   * Date of Dedication of a church, basilica, or cathedral (or other place of worship),
   * as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_dedication?: SaintDateDef | null;
  /**
   * The full name of the entity.
   */
  fullname?: string | null;
  /**
   * Specify if the canonization level should not be displayed.
   * It's generally the case when the canonization are already included in the name.
   */
  hide_canonization_level?: boolean | null;
  /**
   * Specify if the titles should not be displayed.
   * It's generally the case when titles are already included in the name.
   */
  hide_titles?: boolean | null;
  /**
   * The unique identifier of the entity
   */
  id: string;
  /**
   * The short name of the entity, without the canonization level and titles.
   */
  name?: string | null;
  /**
   * Determine if the Saint or the Blessed is a male or a female.
   */
  sex?: Sex | null;
  /**
   * Sources for the information about this entity
   */
  sources?: string[] | null;
  /**
   * Titles of the Saint or the Blessed
   */
  titles?: Title[] | null;
  /**
   * The type of the entity.
   * @default EntityType.Person
   */
  type?: EntityType | null;
}
export interface ResourcesMetadata {
  colors?: LocaleColors | null;
  cycles?: CyclesMetadata | null;
  months?: {
    [k: string]: string;
  } | null;
  ordinals?: {
    [k: string]: string;
  } | null;
  periods?: PeriodsMetadata | null;
  ranks?: RanksMetadata | null;
  seasons?: SeasonsMetadata | null;
  weekdays?: {
    [k: string]: string;
  } | null;
}
export interface LocaleColors {
  black?: string | null;
  gold?: string | null;
  green?: string | null;
  purple?: string | null;
  red?: string | null;
  rose?: string | null;
  white?: string | null;
}
export interface CyclesMetadata {
  proper_of_saints?: string | null;
  proper_of_time?: string | null;
  psalter_week_1?: string | null;
  psalter_week_2?: string | null;
  psalter_week_3?: string | null;
  psalter_week_4?: string | null;
  sunday_year_a?: string | null;
  sunday_year_b?: string | null;
  sunday_year_c?: string | null;
  weekday_year_1?: string | null;
  weekday_year_2?: string | null;
}
export interface PeriodsMetadata {
  epiphany?: string | null;
  holy_week?: string | null;
}
export interface RanksMetadata {
  feast?: string | null;
  memorial?: string | null;
  optional_memorial?: string | null;
  solemnity?: string | null;
  sunday?: string | null;
  weekday?: string | null;
}
export interface SeasonsMetadata {
  advent?: AdventSeason | null;
  christmas_time?: ChristmasTimeSeason | null;
  easter_time?: EasterTimeSeason | null;
  lent?: LentSeason | null;
  ordinary_time?: OrdinaryTimeSeason | null;
  paschal_triduum?: PaschalTriduumSeason | null;
}
export interface AdventSeason {
  privileged_weekday?: string | null;
  season?: string | null;
  sunday?: string | null;
  weekday?: string | null;
}
export interface ChristmasTimeSeason {
  after_epiphany?: string | null;
  before_epiphany?: string | null;
  day?: string | null;
  octave?: string | null;
  season?: string | null;
  second_sunday_after_christmas?: string | null;
}
export interface EasterTimeSeason {
  octave?: string | null;
  season?: string | null;
  sunday?: string | null;
  weekday?: string | null;
}
export interface LentSeason {
  day_after_ash_wed?: string | null;
  holy_week_day?: string | null;
  season?: string | null;
  sunday?: string | null;
  weekday?: string | null;
}
export interface OrdinaryTimeSeason {
  season?: string | null;
  sunday?: string | null;
  weekday?: string | null;
}
export interface PaschalTriduumSeason {
  season?: string | null;
}

export enum Colors {
  RED = "RED",
  ROSE = "ROSE",
  PURPLE = "PURPLE",
  GREEN = "GREEN",
  WHITE = "WHITE",
  GOLD = "GOLD",
  BLACK = "BLACK"
}
export enum CommonDefinition {
  NONE = "NONE",
  DEDICATION_ANNIVERSARY__INSIDE = "DEDICATION_ANNIVERSARY__INSIDE",
  DEDICATION_ANNIVERSARY__OUTSIDE = "DEDICATION_ANNIVERSARY__OUTSIDE",
  BLESSED_VIRGIN_MARY = "BLESSED_VIRGIN_MARY",
  MARTYRS = "MARTYRS",
  MISSIONARY_MARTYRS = "MISSIONARY_MARTYRS",
  VIRGIN_MARTYRS = "VIRGIN_MARTYRS",
  WOMAN_MARTYRS = "WOMAN_MARTYRS",
  PASTORS = "PASTORS",
  POPES = "POPES",
  BISHOPS = "BISHOPS",
  FOUNDERS = "FOUNDERS",
  MISSIONARIES = "MISSIONARIES",
  DOCTORS_OF_THE_CHURCH = "DOCTORS_OF_THE_CHURCH",
  VIRGINS = "VIRGINS",
  SAINTS = "SAINTS",
  ABBOTS = "ABBOTS",
  MONKS = "MONKS",
  NUNS = "NUNS",
  RELIGIOUS = "RELIGIOUS",
  MERCY_WORKERS = "MERCY_WORKERS",
  EDUCATORS = "EDUCATORS",
  HOLY_WOMEN = "HOLY_WOMEN"
}
export enum DateFn {
  MARY_MOTHER_OF_THE_CHURCH = "MARY_MOTHER_OF_THE_CHURCH",
  EPIPHANY_SUNDAY = "EPIPHANY_SUNDAY",
  PRESENTATION_OF_THE_LORD = "PRESENTATION_OF_THE_LORD",
  ANNUNCIATION = "ANNUNCIATION",
  PALM_SUNDAY = "PALM_SUNDAY",
  EASTER_SUNDAY = "EASTER_SUNDAY",
  DIVINE_MERCY_SUNDAY = "DIVINE_MERCY_SUNDAY",
  IMMACULATE_HEART_OF_MARY = "IMMACULATE_HEART_OF_MARY",
  PENTECOST_SUNDAY = "PENTECOST_SUNDAY",
  CORPUS_CHRISTI_SUNDAY = "CORPUS_CHRISTI_SUNDAY",
  NATIVITY_OF_JOHN_THE_BAPTIST = "NATIVITY_OF_JOHN_THE_BAPTIST",
  PETER_AND_PAUL_APOSTLES = "PETER_AND_PAUL_APOSTLES",
  TRANSFIGURATION = "TRANSFIGURATION",
  ASSUMPTION = "ASSUMPTION",
  EXALTATION_OF_THE_HOLY_CROSS = "EXALTATION_OF_THE_HOLY_CROSS",
  ALL_SAINTS = "ALL_SAINTS",
  IMMACULATE_CONCEPTION_OF_MARY = "IMMACULATE_CONCEPTION_OF_MARY"
}
export enum Title {
  ABBESS = "ABBESS",
  ABBOT = "ABBOT",
  APOSTLE = "APOSTLE",
  ARCHANGEL = "ARCHANGEL",
  BISHOP = "BISHOP",
  DEACON = "DEACON",
  DOCTOR_OF_THE_CHURCH = "DOCTOR_OF_THE_CHURCH",
  EMPRESS = "EMPRESS",
  EVANGELIST = "EVANGELIST",
  FIRST_BISHOP = "FIRST_BISHOP",
  HERMIT = "HERMIT",
  KING = "KING",
  MARTYR = "MARTYR",
  MISSIONARY = "MISSIONARY",
  MONK = "MONK",
  MOTHER_AND_QUEEN_OF_CHILE = "MOTHER_AND_QUEEN_OF_CHILE",
  PARENTS_OF_THE_BLESSED_VIRGIN_MARY = "PARENTS_OF_THE_BLESSED_VIRGIN_MARY",
  POPE = "POPE",
  PATRIARCH = "PATRIARCH",
  PILGRIM = "PILGRIM",
  PRIEST = "PRIEST",
  PROPHET = "PROPHET",
  PROTO_MARTYR_OF_OCEANIA = "PROTO_MARTYR_OF_OCEANIA",
  QUEEN = "QUEEN",
  QUEEN_OF_POLAND = "QUEEN_OF_POLAND",
  RELIGIOUS = "RELIGIOUS",
  SLAVIC_MISSIONARY = "SLAVIC_MISSIONARY",
  SPOUSE_OF_THE_BLESSED_VIRGIN_MARY = "SPOUSE_OF_THE_BLESSED_VIRGIN_MARY",
  THE_FIRST_MARTYR = "THE_FIRST_MARTYR",
  VIRGIN = "VIRGIN",
  COPATRON_OF_EUROPE = "COPATRON_OF_EUROPE",
  COPATRON_OF_IRELAND = "COPATRON_OF_IRELAND",
  COPATRON_OF_CANADA = "COPATRON_OF_CANADA",
  COPATRONESS_OF_EUROPE = "COPATRONESS_OF_EUROPE",
  COPATRONESS_OF_FRANCE = "COPATRONESS_OF_FRANCE",
  COPATRONESS_OF_IRELAND = "COPATRONESS_OF_IRELAND",
  COPATRONESS_OF_ITALY_AND_EUROPE = "COPATRONESS_OF_ITALY_AND_EUROPE",
  COPATRONESS_OF_THE_PHILIPPINES = "COPATRONESS_OF_THE_PHILIPPINES",
  PATRON_OF_CANADA = "PATRON_OF_CANADA",
  PATRON_OF_ENGLAND = "PATRON_OF_ENGLAND",
  PATRON_OF_EUROPE = "PATRON_OF_EUROPE",
  PATRON_OF_FRANCE = "PATRON_OF_FRANCE",
  PATRON_OF_IRELAND = "PATRON_OF_IRELAND",
  PATRON_OF_ITALY = "PATRON_OF_ITALY",
  PATRON_OF_OCEANIA = "PATRON_OF_OCEANIA",
  PATRON_OF_POLAND = "PATRON_OF_POLAND",
  PATRON_OF_RUSSIA = "PATRON_OF_RUSSIA",
  PATRON_OF_SCOTLAND = "PATRON_OF_SCOTLAND",
  PATRON_OF_SPAIN = "PATRON_OF_SPAIN",
  PATRON_OF_THE_CZECH_NATION = "PATRON_OF_THE_CZECH_NATION",
  PATRON_OF_THE_DIOCESE = "PATRON_OF_THE_DIOCESE",
  PATRON_OF_WALES = "PATRON_OF_WALES",
  PATRONESS_OF_ALSACE = "PATRONESS_OF_ALSACE",
  PATRONESS_OF_ARGENTINA = "PATRONESS_OF_ARGENTINA",
  PATRONESS_OF_BRAZIL = "PATRONESS_OF_BRAZIL",
  PATRONESS_OF_HUNGARY = "PATRONESS_OF_HUNGARY",
  PATRONESS_OF_PUERTO_RICO = "PATRONESS_OF_PUERTO_RICO",
  PATRONESS_OF_SLOVAKIA = "PATRONESS_OF_SLOVAKIA",
  PATRONESS_OF_THE_AMERICAS = "PATRONESS_OF_THE_AMERICAS",
  PATRONESS_OF_THE_PHILIPPINES = "PATRONESS_OF_THE_PHILIPPINES",
  PATRONESS_OF_THE_PROVINCE_OF_QUEBEC = "PATRONESS_OF_THE_PROVINCE_OF_QUEBEC",
  PATRONESS_OF_THE_USA = "PATRONESS_OF_THE_USA",
  PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON = "PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON",
  PATRON_OF_THE_CITY_OF_LYON = "PATRON_OF_THE_CITY_OF_LYON",
  PATRONESS_OF_COSTA_RICA = "PATRONESS_OF_COSTA_RICA",
  PRINCIPAL_PATRON_OF_THE_DIOCESE = "PRINCIPAL_PATRON_OF_THE_DIOCESE",
  SECOND_PATRON_OF_THE_DIOCESE = "SECOND_PATRON_OF_THE_DIOCESE"
}
export enum Precedence {
  TRIDUUM_1 = "TRIDUUM_1",
  PROPER_OF_TIME_SOLEMNITY_2 = "PROPER_OF_TIME_SOLEMNITY_2",
  PRIVILEGED_SUNDAY_2 = "PRIVILEGED_SUNDAY_2",
  ASH_WEDNESDAY_2 = "ASH_WEDNESDAY_2",
  WEEKDAY_OF_HOLY_WEEK_2 = "WEEKDAY_OF_HOLY_WEEK_2",
  WEEKDAY_OF_EASTER_OCTAVE_2 = "WEEKDAY_OF_EASTER_OCTAVE_2",
  GENERAL_SOLEMNITY_3 = "GENERAL_SOLEMNITY_3",
  COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3 = "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3",
  PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A = "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A",
  PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B = "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B",
  PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C = "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C",
  PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D = "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D",
  GENERAL_LORD_FEAST_5 = "GENERAL_LORD_FEAST_5",
  UNPRIVILEGED_SUNDAY_6 = "UNPRIVILEGED_SUNDAY_6",
  GENERAL_FEAST_7 = "GENERAL_FEAST_7",
  PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A",
  PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B = "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B",
  PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C",
  PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D = "PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D",
  PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E = "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E",
  PROPER_FEAST_8F = "PROPER_FEAST_8F",
  PRIVILEGED_WEEKDAY_9 = "PRIVILEGED_WEEKDAY_9",
  GENERAL_MEMORIAL_10 = "GENERAL_MEMORIAL_10",
  PROPER_MEMORIAL__SECOND_PATRON_11A = "PROPER_MEMORIAL__SECOND_PATRON_11A",
  PROPER_MEMORIAL_11B = "PROPER_MEMORIAL_11B",
  OPTIONAL_MEMORIAL_12 = "OPTIONAL_MEMORIAL_12",
  WEEKDAY_13 = "WEEKDAY_13"
}
export enum CalendarJurisdiction {
  ECCLESIASTICAL = "ECCLESIASTICAL",
  CIVIL = "CIVIL"
}
export enum CalendarType {
  GENERAL_ROMAN = "GENERAL_ROMAN",
  REGION = "REGION",
  COUNTRY = "COUNTRY",
  ARCHDIOCESE = "ARCHDIOCESE",
  DIOCESE = "DIOCESE",
  CITY = "CITY",
  PARISH = "PARISH",
  GENERAL_COMMUNITY = "GENERAL_COMMUNITY",
  REGIONAL_COMMUNITY = "REGIONAL_COMMUNITY",
  LOCAL_COMMUNITY = "LOCAL_COMMUNITY",
  OTHER = "OTHER"
}
export enum EasterCalculationType {
  GREGORIAN = "GREGORIAN",
  JULIAN = "JULIAN"
}
export enum CanonizationLevel {
  BLESSED = "BLESSED",
  SAINT = "SAINT"
}
export enum Sex {
  MALE = "MALE",
  FEMALE = "FEMALE"
}
export enum EntityType {
  PERSON = "PERSON",
  PLACE = "PLACE",
  EVENT = "EVENT"
}
