import { createUnplugin } from 'unplugin';
import type { RomcalPluginOptions, RomcalBundle } from './types.js';
import { generateBundle } from './bundle.js';

const VIRTUAL_MODULE_PREFIX = '\0romcal:';
const DEFAULT_MODULE_ID = 'virtual:romcal';

export const unplugin = createUnplugin<RomcalPluginOptions>((options) => {
  const moduleId = options?.moduleId ?? DEFAULT_MODULE_ID;

  // Cache the optimized bundle (avoid recalculating on each HMR)
  let cachedBundle: string | null = null;
  let cachedOptionsKey: string | null = null;

  return {
    name: '@romcal/unplugin',

    resolveId(id: string) {
      if (id === moduleId) {
        return `${VIRTUAL_MODULE_PREFIX}${id}`;
      }
      return null;
    },

    async load(id: string) {
      if (!id.startsWith(VIRTUAL_MODULE_PREFIX)) {
        return null;
      }

      // Check cache
      const optionsKey = JSON.stringify(options);
      if (cachedBundle && cachedOptionsKey === optionsKey) {
        return cachedBundle;
      }

      try {
        const bundle = await generateBundle(options);

        const code = `// Generated by @romcal/unplugin
// Calendar: ${bundle.calendar}, Locale: ${bundle.locale}
const bundle = ${JSON.stringify(bundle)};
export default bundle;
`;

        // Cache result
        cachedBundle = code;
        cachedOptionsKey = optionsKey;

        return code;
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`[@romcal/unplugin] Failed to generate bundle: ${message}`);
      }
    },

    // Invalidate cache in watch/dev mode
    watchChange() {
      cachedBundle = null;
      cachedOptionsKey = null;
    },
  };
});

export default unplugin;
export type { RomcalPluginOptions, RomcalBundle };
