#!/usr/bin/env tsx
/// <reference types="node" />

/**
 * Post-processing script for ts-rs generated TypeScript files.
 *
 * ts-rs doesn't generate imports for types referenced in custom type overrides
 * (e.g., `#[ts(type = "Record<LiturgicalCycle, MassContent>")]`).
 *
 * This script uses TypeScript's compiler (tsc) to detect missing type references
 * and automatically adds the required imports. It runs in a loop to handle
 * dependency chains where fixing one file reveals errors in another.
 */

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = join(__dirname, '..')
const TYPES_DIR = join(ROOT_DIR, 'src', 'types')

// Parse TypeScript "Cannot find name" errors:
// - TS2304: Cannot find name 'X'.
// - TS2552: Cannot find name 'X'. Did you mean 'Y'?
const errorPattern =
  /src\/types\/(\w+)\.ts\(\d+,\d+\): error TS2(?:304|552): Cannot find name '(\w+)'/g

let totalFixed = 0
let iteration = 0
const maxIterations = 10 // Safety limit

while (iteration < maxIterations) {
  iteration++

  // Run tsc and capture errors
  const output = execSync('npx tsc --noEmit 2>&1 || true', {
    encoding: 'utf-8',
    cwd: ROOT_DIR,
  })

  // Collect errors by file
  const fixes = new Map<string, Set<string>>()

  for (const match of output.matchAll(errorPattern)) {
    const [, fileName, typeName] = match
    if (!fixes.has(fileName)) {
      fixes.set(fileName, new Set())
    }
    fixes.get(fileName)!.add(typeName)
  }

  // No more errors to fix
  if (fixes.size === 0) {
    break
  }

  // Apply fixes
  for (const [fileName, types] of fixes) {
    const filePath = join(TYPES_DIR, `${fileName}.ts`)
    let content = readFileSync(filePath, 'utf-8')

    const imports = [...types]
      .sort()
      .map((t) => `import type { ${t} } from "./${t}.js";`)
      .join('\n')

    // Insert imports after the ts-rs header comment
    const headerMatch = content.match(/^\/\/ This file was generated by \[ts-rs\].*\n/)
    if (headerMatch) {
      const insertPos = headerMatch[0].length
      content = content.slice(0, insertPos) + imports + '\n' + content.slice(insertPos)
    } else {
      content = imports + '\n' + content
    }

    writeFileSync(filePath, content)
    console.log(`Fixed imports in ${fileName}.ts: ${[...types].join(', ')}`)
    totalFixed++
  }
}

if (totalFixed > 0) {
  console.log(`\nFixed ${totalFixed} file(s) with missing imports.`)
} else {
  console.log('All imports are correct.')
}
