#!/usr/bin/env node

/**
 * Post-processing script for ts-rs generated TypeScript files.
 *
 * ts-rs doesn't generate imports for types referenced in custom type overrides
 * (e.g., `#[ts(type = "Record<LiturgicalCycle, MassContent>")]`).
 *
 * This script scans all generated type files, detects missing imports,
 * and adds them automatically.
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TYPES_DIR = join(__dirname, "..", "src", "types");

// Built-in TypeScript types that should not be imported
const BUILTIN_TYPES = new Set([
  "Record",
  "Partial",
  "Required",
  "Readonly",
  "Pick",
  "Omit",
  "Exclude",
  "Extract",
  "NonNullable",
  "Parameters",
  "ReturnType",
  "Array",
  "Map",
  "Set",
  "Promise",
  "Date",
  "RegExp",
  "Error",
  "String",
  "Number",
  "Boolean",
  "Object",
  "Function",
  "Symbol",
  "BigInt",
]);

// Build a map of known types from generated files
const knownTypes = new Map();
for (const file of readdirSync(TYPES_DIR)) {
  if (!file.endsWith(".ts") || file === "index.ts") continue;
  const typeName = file.replace(".ts", "");
  knownTypes.set(typeName, file);
}

let fixedCount = 0;

// Process each generated file
for (const file of readdirSync(TYPES_DIR)) {
  if (!file.endsWith(".ts") || file === "index.ts") continue;

  const filePath = join(TYPES_DIR, file);
  const currentTypeName = file.replace(".ts", "");
  let content = readFileSync(filePath, "utf-8");

  // Find existing imports (with or without .js extension)
  const existingImports = new Set(
    [...content.matchAll(/import\s+(?:type\s+)?.*from\s+["']\.\/(\w+)(?:\.js)?["']/g)].map(
      (m) => m[1]
    )
  );

  // Find all PascalCase identifiers that could be type references
  const typePattern = /\b([A-Z][a-zA-Z0-9]*)\b/g;
  const usedTypes = new Set();

  for (const match of content.matchAll(typePattern)) {
    const typeName = match[1];
    // Skip if:
    // - It's the current file's type (self-reference in export)
    // - It's a built-in TypeScript type
    // - It's already imported
    // - It's not a known generated type
    if (
      typeName === currentTypeName ||
      BUILTIN_TYPES.has(typeName) ||
      existingImports.has(typeName) ||
      !knownTypes.has(typeName)
    ) {
      continue;
    }
    usedTypes.add(typeName);
  }

  // Add missing imports
  if (usedTypes.size > 0) {
    const sortedTypes = [...usedTypes].sort();
    const imports = sortedTypes
      .map((t) => `import type { ${t} } from "./${t}.js";`)
      .join("\n");

    // Insert imports after the ts-rs header comment
    const headerMatch = content.match(
      /^\/\/ This file was generated by \[ts-rs\].*\n/
    );
    if (headerMatch) {
      const insertPos = headerMatch[0].length;
      content =
        content.slice(0, insertPos) + imports + "\n" + content.slice(insertPos);
    } else {
      content = imports + "\n" + content;
    }

    writeFileSync(filePath, content);
    console.log(`Fixed imports in ${file}: ${sortedTypes.join(", ")}`);
    fixedCount++;
  }
}

if (fixedCount > 0) {
  console.log(`\nFixed ${fixedCount} file(s) with missing imports.`);
} else {
  console.log("All imports are correct.");
}
