export type AllTypes = {
    $schema?:          null | string;
    days_definitions?: DayDefinition[];
    id?:               string;
    /**
     * Metadata of the resources
     */
    metadata?:            ResourcesMetadata | null;
    parent_calendar_ids?: string[];
    particular_config?:   ParticularConfig | null;
    /**
     * Entities of the resources: a person, a place, an event, etc.
     */
    entities?: Entity[] | null;
    /**
     * Locale code of the resources, in BCP-47 IETF tag format
     */
    locale?: string;
}

/**
 * Definition of a liturgical day with all its properties and configurations.
 * It represents a complete liturgical day definition that can be used
 * to generate calendar entries with proper precedence, colors, and entity associations.
 */
export type DayDefinition = {
    /**
     * Allow similar items that have the same rank and the same or lower precedence
     * to coexist with this liturgical day without being overwritten
     */
    allow_similar_rank_items?: boolean | null;
    /**
     * The liturgical color(s) of the liturgical day
     * @deprecated
     */
    colors?: ColorsUnion;
    /**
     * The **Common** refers to a set of prayers, readings, and chants used for celebrating
     * saints or
     * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the
     * Blessed
     * Virgin Mary.
     */
    commons_def?: CommonsDef;
    /**
     * The custom locale ID for this date definition in this calendar
     */
    custom_locale_id?: null | string;
    /**
     * The date definition for this liturgical day
     */
    date_def?: DateDefClass | null;
    /**
     * The date definition exceptions (overrides for specific circumstances)
     */
    date_exceptions?: DateDefExceptions;
    /**
     * If this liturgical day must be removed from this calendar and from all parent calendars
     * in the final calendar generated by romcal
     */
    drop?: boolean | null;
    /**
     * The entities (Saints, Blessed, or Places) linked from the Entity catalog
     */
    entities?: EntityPointer[] | null;
    /**
     * The unique identifier of the day definition
     */
    id: string;
    /**
     * Holy days of obligation are days on which the faithful are expected to attend Mass
     * and engage in rest from work and recreation
     */
    is_holy_day_of_obligation?: boolean | null;
    /**
     * Specify if this liturgical day is optional within a specific liturgical calendar
     *
     * UNLY #14:
     * Memorials are either obligatory or optional; their observance is integrated into
     * the celebration of the occurring weekday in accordance with the norms set forth in the
     * General Instruction of the Roman Missal and of the Liturgy of the Hours
     *
     * Note: also used for the dedication of consecrated churches, which is an optional
     * solemnity
     * that should not overwrite the default weekday.
     */
    is_optional?: boolean | null;
    /**
     * The precedence type of the liturgical day
     */
    precedence?: Precedence | null;
    /**
     * The combined titles of all entities linked to this date definition
     */
    titles?: TitlesDef;
}

/**
 * The liturgical color(s) of the liturgical day
 * @deprecated
 */
export type ColorsUnion = Color[] | Color | null;

/**
 * Liturgical colors used in the celebration of Mass and other liturgical services.
 * Each color has specific liturgical significance and is used during particular seasons or
 * celebrations.
 *
 * Red - used for martyrs, Pentecost, and Palm Sunday
 *
 * Rose - used on Gaudete Sunday (3rd Advent) and Laetare Sunday (4th Lent)
 *
 * Purple - used during Advent and Lent
 *
 * Green - used during Ordinary Time
 *
 * White - used for Christmas, Easter, and most feasts
 *
 * Gold - used for solemn celebrations and special occasions
 *
 * Black - used for funerals and All Souls' Day
 */
export enum Color {
    Black = "BLACK",
    Gold = "GOLD",
    Green = "GREEN",
    Purple = "PURPLE",
    Red = "RED",
    Rose = "ROSE",
    White = "WHITE",
}

/**
 * The **Common** refers to a set of prayers, readings, and chants used for celebrating
 * saints or
 * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the
 * Blessed
 * Virgin Mary.
 */
export type CommonsDef = CommonDefinition[] | CommonDefinition | null;

/**
 * Common definition for simplified categorization.
 * Provides a simplified version of the Common enum for easier classification.
 */
export enum CommonDefinition {
    Abbots = "ABBOTS",
    Bishops = "BISHOPS",
    BlessedVirginMary = "BLESSED_VIRGIN_MARY",
    DedicationAnniversaryInside = "DEDICATION_ANNIVERSARY__INSIDE",
    DedicationAnniversaryOutside = "DEDICATION_ANNIVERSARY__OUTSIDE",
    DoctorsOfTheChurch = "DOCTORS_OF_THE_CHURCH",
    Educators = "EDUCATORS",
    Founders = "FOUNDERS",
    HolyWomen = "HOLY_WOMEN",
    Martyrs = "MARTYRS",
    MercyWorkers = "MERCY_WORKERS",
    Missionaries = "MISSIONARIES",
    MissionaryMartyrs = "MISSIONARY_MARTYRS",
    Monks = "MONKS",
    None = "NONE",
    Nuns = "NUNS",
    Pastors = "PASTORS",
    Popes = "POPES",
    Religious = "RELIGIOUS",
    Saints = "SAINTS",
    VirginMartyrs = "VIRGIN_MARTYRS",
    Virgins = "VIRGINS",
    WomanMartyrs = "WOMAN_MARTYRS",
}

/**
 * Simple month/day specification
 *
 * Date function calculation (Easter, Epiphany, etc.)
 *
 * Nth weekday of a specific month
 *
 * Last weekday of a specific month
 */
export type DateDefClass = {
    /**
     * The day of the month (1-31)
     */
    date?: number;
    /**
     * Optional day offset for adjustments
     */
    day_offset?: number | null;
    /**
     * The month (1-12)
     */
    month?: number;
    /**
     * The date function to calculate the base date
     */
    date_fn?: DateFn;
    /**
     * The day of the week (0=Sunday, 1=Monday, etc.)
     */
    day_of_week?: number;
    /**
     * Which occurrence of the weekday (1st, 2nd, 3rd, etc.)
     */
    nth_week_in_month?: number;
    /**
     * The day of the week to find the last occurrence of
     */
    last_day_of_week_in_month?: number;
}

/**
 * The date function to calculate the base date
 *
 * Date function for calculating liturgical dates.
 * Represents movable feasts and special celebrations that require calculation.
 */
export enum DateFn {
    AllSaints = "ALL_SAINTS",
    Annunciation = "ANNUNCIATION",
    Assumption = "ASSUMPTION",
    CorpusChristiSunday = "CORPUS_CHRISTI_SUNDAY",
    DivineMercySunday = "DIVINE_MERCY_SUNDAY",
    EasterSunday = "EASTER_SUNDAY",
    EpiphanySunday = "EPIPHANY_SUNDAY",
    ExaltationOfTheHolyCross = "EXALTATION_OF_THE_HOLY_CROSS",
    ImmaculateConceptionOfMary = "IMMACULATE_CONCEPTION_OF_MARY",
    ImmaculateHeartOfMary = "IMMACULATE_HEART_OF_MARY",
    MaryMotherOfTheChurch = "MARY_MOTHER_OF_THE_CHURCH",
    NativityOfJohnTheBaptist = "NATIVITY_OF_JOHN_THE_BAPTIST",
    PalmSunday = "PALM_SUNDAY",
    PentecostSunday = "PENTECOST_SUNDAY",
    PeterAndPaulApostles = "PETER_AND_PAUL_APOSTLES",
    PresentationOfTheLord = "PRESENTATION_OF_THE_LORD",
    Transfiguration = "TRANSFIGURATION",
}

/**
 * The date definition exceptions (overrides for specific circumstances)
 */
export type DateDefExceptions = DateDefException[] | DateDefException | null;

/**
 * Single date exception
 *
 * The liturgical day date exception.
 * Represents a condition and the date to set when that condition is met.
 *
 * Multiple date exceptions
 */
export type DateDefException = {
    /**
     * The date to set when the condition is met
     */
    then: DateDefExtended;
    /**
     * The condition that triggers the exception
     */
    when: ExceptionCondition;
}

/**
 * The date to set when the condition is met
 *
 * Extended date definition supporting both regular dates and offset dates.
 * Provides flexibility for date calculations with optional adjustments.
 *
 * Simple month/day specification
 *
 * Date function calculation (Easter, Epiphany, etc.)
 *
 * Nth weekday of a specific month
 *
 * Last weekday of a specific month
 *
 * Date definition with offset
 *
 * Date definition with offset for adjustments.
 * Used when a date needs to be shifted by a specific number of days.
 */
export type DateDefExtended = {
    /**
     * The day of the month (1-31)
     */
    date?: number;
    /**
     * Optional day offset for adjustments
     *
     * The number of days to offset the date
     */
    day_offset?: number | null;
    /**
     * The month (1-12)
     */
    month?: number;
    /**
     * The date function to calculate the base date
     */
    date_fn?: DateFn;
    /**
     * The day of the week (0=Sunday, 1=Monday, etc.)
     */
    day_of_week?: number;
    /**
     * Which occurrence of the weekday (1st, 2nd, 3rd, etc.)
     */
    nth_week_in_month?: number;
    /**
     * The day of the week to find the last occurrence of
     */
    last_day_of_week_in_month?: number;
}

/**
 * The condition that triggers the exception
 *
 * Exception conditions that can trigger a date change.
 * Defines various conditions under which a date exception applies.
 *
 * If the date is between two specified dates
 *
 * If the date is the same as another specified date
 *
 * If the date falls on a specific day of the week
 */
export type ExceptionCondition = {
    /**
     * The start date of the range
     */
    from?: DateDef;
    /**
     * Whether the range is inclusive of the start date and the end date
     */
    inclusive?: boolean;
    /**
     * The end date of the range
     */
    to?: DateDef;
    /**
     * The date to compare against
     */
    date?: DateDef;
    /**
     * The day of the week to match
     */
    day_of_week?: number;
}

/**
 * Date definition supporting various date calculation methods.
 * Provides flexible ways to specify liturgical dates using different approaches.
 *
 * Regular date definition
 *
 * The start date of the range
 *
 * The end date of the range
 *
 * The date to compare against
 *
 * Simple month/day specification
 *
 * Date function calculation (Easter, Epiphany, etc.)
 *
 * Nth weekday of a specific month
 *
 * Last weekday of a specific month
 */
export type DateDef = {
    /**
     * The day of the month (1-31)
     */
    date?: number;
    /**
     * Optional day offset for adjustments
     */
    day_offset?: number | null;
    /**
     * The month (1-12)
     */
    month?: number;
    /**
     * The date function to calculate the base date
     */
    date_fn?: DateFn;
    /**
     * The day of the week (0=Sunday, 1=Monday, etc.)
     */
    day_of_week?: number;
    /**
     * Which occurrence of the weekday (1st, 2nd, 3rd, etc.)
     */
    nth_week_in_month?: number;
    /**
     * The day of the week to find the last occurrence of
     */
    last_day_of_week_in_month?: number;
}

/**
 * A pointer to an entity in the entity catalog.
 * Can either reference an existing entity by ID or define a custom entity with additional
 * properties.
 */
export type EntityPointer = EntityOverride | string;

/**
 * Custom entity definition with additional properties specific to a liturgical day
 *
 * Custom entity definition that extends or overrides properties from the entity catalog.
 * Used when a liturgical day needs specific entity properties that differ from the base
 * entity.
 */
export type EntityOverride = {
    /**
     * The number of persons this entity represents (useful for groups of martyrs or saints)
     */
    count?: CountUnion;
    /**
     * Whether to hide titles when displaying this entity (useful when titles are already
     * included in the entity name)
     */
    hide_titles?: boolean | null;
    /**
     * The ID of the entity item (must reference an existing entity in the catalog)
     */
    id: string;
    /**
     * The custom titles for this entity in the context of this liturgical day
     */
    titles?: TitlesDef;
}

export type CountUnion = CountEnum | number | null;

export enum CountEnum {
    Many = "MANY",
}

export type TitlesDef = Title[] | CompoundTitle | null;

/**
 * Simple list of titles
 *
 * Titles and patronages associated with saints and blessed.
 * Represents the various ecclesiastical titles and patronages that can be assigned to
 * entities.
 */
export enum Title {
    Abbess = "ABBESS",
    Abbot = "ABBOT",
    Apostle = "APOSTLE",
    Archangel = "ARCHANGEL",
    Bishop = "BISHOP",
    CopatronOfCanada = "COPATRON_OF_CANADA",
    CopatronOfEurope = "COPATRON_OF_EUROPE",
    CopatronOfIreland = "COPATRON_OF_IRELAND",
    CopatronessOfEurope = "COPATRONESS_OF_EUROPE",
    CopatronessOfFrance = "COPATRONESS_OF_FRANCE",
    CopatronessOfIreland = "COPATRONESS_OF_IRELAND",
    CopatronessOfItalyAndEurope = "COPATRONESS_OF_ITALY_AND_EUROPE",
    CopatronessOfThePhilippines = "COPATRONESS_OF_THE_PHILIPPINES",
    Deacon = "DEACON",
    DoctorOfTheChurch = "DOCTOR_OF_THE_CHURCH",
    Empress = "EMPRESS",
    Evangelist = "EVANGELIST",
    FirstBishop = "FIRST_BISHOP",
    Hermit = "HERMIT",
    King = "KING",
    Martyr = "MARTYR",
    Missionary = "MISSIONARY",
    Monk = "MONK",
    MotherAndQueenOfChile = "MOTHER_AND_QUEEN_OF_CHILE",
    ParentsOfTheBlessedVirginMary = "PARENTS_OF_THE_BLESSED_VIRGIN_MARY",
    Patriarch = "PATRIARCH",
    PatronOfCanada = "PATRON_OF_CANADA",
    PatronOfEngland = "PATRON_OF_ENGLAND",
    PatronOfEurope = "PATRON_OF_EUROPE",
    PatronOfFrance = "PATRON_OF_FRANCE",
    PatronOfIreland = "PATRON_OF_IRELAND",
    PatronOfItaly = "PATRON_OF_ITALY",
    PatronOfOceania = "PATRON_OF_OCEANIA",
    PatronOfPoland = "PATRON_OF_POLAND",
    PatronOfRussia = "PATRON_OF_RUSSIA",
    PatronOfScotland = "PATRON_OF_SCOTLAND",
    PatronOfSpain = "PATRON_OF_SPAIN",
    PatronOfTheCityOfLyon = "PATRON_OF_THE_CITY_OF_LYON",
    PatronOfTheClergyOfTheArchdioceseOfLyon = "PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON",
    PatronOfTheCzechNation = "PATRON_OF_THE_CZECH_NATION",
    PatronOfTheDiocese = "PATRON_OF_THE_DIOCESE",
    PatronOfWales = "PATRON_OF_WALES",
    PatronessOfAlsace = "PATRONESS_OF_ALSACE",
    PatronessOfArgentina = "PATRONESS_OF_ARGENTINA",
    PatronessOfBrazil = "PATRONESS_OF_BRAZIL",
    PatronessOfCostaRica = "PATRONESS_OF_COSTA_RICA",
    PatronessOfHungary = "PATRONESS_OF_HUNGARY",
    PatronessOfPuertoRico = "PATRONESS_OF_PUERTO_RICO",
    PatronessOfSlovakia = "PATRONESS_OF_SLOVAKIA",
    PatronessOfTheAmericas = "PATRONESS_OF_THE_AMERICAS",
    PatronessOfThePhilippines = "PATRONESS_OF_THE_PHILIPPINES",
    PatronessOfTheProvinceOfQuebec = "PATRONESS_OF_THE_PROVINCE_OF_QUEBEC",
    PatronessOfTheUsa = "PATRONESS_OF_THE_USA",
    Pilgrim = "PILGRIM",
    Pope = "POPE",
    Priest = "PRIEST",
    PrincipalPatronOfTheDiocese = "PRINCIPAL_PATRON_OF_THE_DIOCESE",
    Prophet = "PROPHET",
    ProtoMartyrOfOceania = "PROTO_MARTYR_OF_OCEANIA",
    Queen = "QUEEN",
    QueenOfPoland = "QUEEN_OF_POLAND",
    Religious = "RELIGIOUS",
    SecondPatronOfTheDiocese = "SECOND_PATRON_OF_THE_DIOCESE",
    SlavicMissionary = "SLAVIC_MISSIONARY",
    SpouseOfTheBlessedVirginMary = "SPOUSE_OF_THE_BLESSED_VIRGIN_MARY",
    TheFirstMartyr = "THE_FIRST_MARTYR",
    Virgin = "VIRGIN",
}

/**
 * Compound title definition with append/prepend operations
 *
 * Compound title definition for combining multiple titles.
 * Allows adding titles to the beginning or end of an existing title list.
 */
export type CompoundTitle = {
    /**
     * The title(s) to add to the end of the existing list of title(s)
     */
    append?: Title[] | null;
    /**
     * The title(s) to add to the beginning of the existing list of title(s)
     */
    prepend?: Title[] | null;
}

/**
 * Liturgical precedence levels for determining which celebration takes priority.
 * Defines the hierarchical order of liturgical celebrations according to UNLY norms.
 */
export enum Precedence {
    AshWednesday2 = "ASH_WEDNESDAY_2",
    CommemorationOfAllTheFaithfulDeparted3 = "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3",
    GeneralFeast7 = "GENERAL_FEAST_7",
    GeneralLordFeast5 = "GENERAL_LORD_FEAST_5",
    GeneralMemorial10 = "GENERAL_MEMORIAL_10",
    GeneralSolemnity3 = "GENERAL_SOLEMNITY_3",
    OptionalMemorial12 = "OPTIONAL_MEMORIAL_12",
    PrivilegedSunday2 = "PRIVILEGED_SUNDAY_2",
    PrivilegedWeekday9 = "PRIVILEGED_WEEKDAY_9",
    ProperFeast8F = "PROPER_FEAST_8F",
    ProperFeastDedicationOfTheCathedralChurch8B = "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B",
    ProperFeastPrincipalPatronOfADiocese8A = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A",
    ProperFeastPrincipalPatronOfARegion8C = "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C",
    ProperFeastTitleOrFounderOrPrimaryPatronOfAReligiousOrg8D = "PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D",
    ProperFeastToAnIndividualChurch8E = "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E",
    ProperMemorial11B = "PROPER_MEMORIAL_11B",
    ProperMemorialSecondPatron11A = "PROPER_MEMORIAL__SECOND_PATRON_11A",
    ProperOfTimeSolemnity2 = "PROPER_OF_TIME_SOLEMNITY_2",
    ProperSolemnityDedicationOfTheOwnChurch4B = "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B",
    ProperSolemnityPrincipalPatron4A = "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A",
    ProperSolemnityTitleOfTheOwnChurch4C = "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C",
    ProperSolemnityTitleOrFounderOrPrimaryPatronOfAReligiousOrg4D = "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D",
    Triduum1 = "TRIDUUM_1",
    UnprivilegedSunday6 = "UNPRIVILEGED_SUNDAY_6",
    Weekday13 = "WEEKDAY_13",
    WeekdayOfEasterOctave2 = "WEEKDAY_OF_EASTER_OCTAVE_2",
    WeekdayOfHolyWeek2 = "WEEKDAY_OF_HOLY_WEEK_2",
}

export type Entity = {
    /**
     * Internal notes
     * @private
     */
    _todo?: string[] | null;
    /**
     * The canonization level of a person.
     */
    canonization_level?: CanonizationLevel | null;
    /**
     * Number of person that this definition represent.
     * It could be set as 'many' if the number is not defined.
     */
    count?: CountUnion;
    /**
     * Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD'
     * format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_beatification?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_beatification_is_approximative?: boolean | null;
    /**
     * Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_birth?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_birth_is_approximative?: boolean | null;
    /**
     * Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_canonization?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_canonization_is_approximative?: boolean | null;
    /**
     * Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_death?: DateOfBeatificationUnion;
    /**
     * Specify whether an approximate indicator should be added, when the date is displayed.
     * For example in English: 'c. 201'.
     */
    date_of_death_is_approximative?: boolean | null;
    /**
     * Date of Dedication of a church, basilica, or cathedral (or other place of worship),
     * as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
     * or an object describing date range, multiple possible date, or a century.
     */
    date_of_dedication?: DateOfBeatificationUnion;
    /**
     * The full name of the entity.
     */
    fullname?: null | string;
    /**
     * Specify if the canonization level should not be displayed.
     * It's generally the case when the canonization are already included in the name.
     */
    hide_canonization_level?: boolean | null;
    /**
     * Specify if the titles should not be displayed.
     * It's generally the case when titles are already included in the name.
     */
    hide_titles?: boolean | null;
    /**
     * The unique identifier of the entity
     */
    id: string;
    /**
     * The short name of the entity, without the canonization level and titles.
     */
    name?: null | string;
    /**
     * Determine if the Saint or the Blessed is a male or a female.
     */
    sex?: Sex | null;
    /**
     * Sources for the information about this entity
     */
    sources?: string[] | null;
    /**
     * Titles of the Saint or the Blessed
     */
    titles?: Title[] | null;
    /**
     * The type of the entity.
     * @default EntityType.Person
     */
    type?: EntityType | null;
}

/**
 * Beatified person (Blessed) - first step toward sainthood
 *
 * Canonized person (Saint) - fully recognized as a saint
 */
export enum CanonizationLevel {
    Blessed = "BLESSED",
    Saint = "SAINT",
}

export type DateOfBeatificationUnion = SaintDateDef | number | null | string;

/**
 * Date range between two dates
 *
 * Multiple alternative dates (any one of them)
 *
 * Century specification (e.g., 12 for 12th century)
 */
export type SaintDateDef = {
    /**
     * The date range (start and end dates)
     */
    between?: SaintDate[];
    /**
     * The list of alternative dates
     */
    or?: SaintDate[];
    /**
     * The century number
     */
    century?: number;
}

/**
 * Single date specification
 *
 * Saint date representation with different precision levels.
 * Supports year-only, year-month, or full date specifications.
 */
export type SaintDate = number | string;

/**
 * Male person
 *
 * Female person
 */
export enum Sex {
    Female = "FEMALE",
    Male = "MALE",
}

/**
 * A person (saint, blessed, or other individual)
 *
 * A place (shrine, city, or geographical location)
 *
 * An event (historical or liturgical occurrence)
 */
export enum EntityType {
    Event = "EVENT",
    Person = "PERSON",
    Place = "PLACE",
}

/**
 * Metadata for a calendar.
 * Contains essential information about the calendar's type and jurisdiction.
 *
 * Metadata for localized resources.
 * Contains all the localized strings and configurations for a specific locale.
 */
export type ResourcesMetadata = {
    /**
     * The jurisdiction of the calendar
     */
    jurisdiction?: CalendarJurisdiction;
    /**
     * The type of the calendar
     */
    type?: CalendarType;
    /**
     * Liturgical color names in the locale language
     */
    colors?: LocaleColors | null;
    /**
     * Liturgical cycle names in the locale language
     */
    cycles?: CyclesMetadata | null;
    /**
     * Month names (January, February, etc.) in the locale language
     */
    months?: { [key: string]: string } | null;
    /**
     * Ordinal numbers (1st, 2nd, 3rd, etc.) in the locale language
     */
    ordinals?: { [key: string]: string } | null;
    /**
     * Liturgical period names in the locale language
     */
    periods?: PeriodsMetadata | null;
    /**
     * Liturgical rank names in the locale language
     */
    ranks?: RanksMetadata | null;
    /**
     * Liturgical season names and descriptions in the locale language
     */
    seasons?: SeasonsMetadata | null;
    /**
     * Weekday names (Sunday, Monday, etc.) in the locale language
     */
    weekdays?: { [key: string]: string } | null;
}

/**
 * Liturgical color names in the locale language.
 * Provides localized names for each liturgical color.
 */
export type LocaleColors = {
    /**
     * Black color name in the locale language
     */
    black?: null | string;
    /**
     * Gold color name in the locale language
     */
    gold?: null | string;
    /**
     * Green color name in the locale language
     */
    green?: null | string;
    /**
     * Purple color name in the locale language
     */
    purple?: null | string;
    /**
     * Red color name in the locale language
     */
    red?: null | string;
    /**
     * Rose color name in the locale language
     */
    rose?: null | string;
    /**
     * White color name in the locale language
     */
    white?: null | string;
}

/**
 * Liturgical cycle names in the locale language.
 */
export type CyclesMetadata = {
    /**
     * Proper of Saints cycle name
     */
    proper_of_saints?: null | string;
    /**
     * Proper of Time cycle name
     */
    proper_of_time?: null | string;
    /**
     * Psalter Week 1 cycle name
     */
    psalter_week_1?: null | string;
    /**
     * Psalter Week 2 cycle name
     */
    psalter_week_2?: null | string;
    /**
     * Psalter Week 3 cycle name
     */
    psalter_week_3?: null | string;
    /**
     * Psalter Week 4 cycle name
     */
    psalter_week_4?: null | string;
    /**
     * Sunday Year A cycle name
     */
    sunday_year_a?: null | string;
    /**
     * Sunday Year B cycle name
     */
    sunday_year_b?: null | string;
    /**
     * Sunday Year C cycle name
     */
    sunday_year_c?: null | string;
    /**
     * Weekday Year 1 cycle name
     */
    weekday_year_1?: null | string;
    /**
     * Weekday Year 2 cycle name
     */
    weekday_year_2?: null | string;
}

/**
 * The jurisdiction of the calendar
 *
 * The jurisdiction of the calendar.
 * Determines whether the calendar follows ecclesiastical or civil authority.
 *
 * Calendar under ecclesiastical authority (Church)
 *
 * Calendar under civil authority (State)
 */
export enum CalendarJurisdiction {
    Civil = "CIVIL",
    Ecclesiastical = "ECCLESIASTICAL",
}

/**
 * Liturgical period names in the locale language.
 */
export type PeriodsMetadata = {
    /**
     * Epiphany period name
     */
    epiphany?: null | string;
    /**
     * Holy Week period name
     */
    holy_week?: null | string;
}

/**
 * Liturgical rank names in the locale language.
 */
export type RanksMetadata = {
    /**
     * Feast rank name
     */
    feast?: null | string;
    /**
     * Memorial rank name
     */
    memorial?: null | string;
    /**
     * Optional memorial rank name
     */
    optional_memorial?: null | string;
    /**
     * Solemnity rank name
     */
    solemnity?: null | string;
    /**
     * Sunday rank name
     */
    sunday?: null | string;
    /**
     * Weekday rank name
     */
    weekday?: null | string;
}

/**
 * Liturgical season names and descriptions in the locale language.
 * Provides localized names for each liturgical season and their components.
 */
export type SeasonsMetadata = {
    /**
     * Advent season names and descriptions
     */
    advent?: AdventSeason | null;
    /**
     * Christmas Time season names and descriptions
     */
    christmas_time?: ChristmasTimeSeason | null;
    /**
     * Easter Time season names and descriptions
     */
    easter_time?: EasterTimeSeason | null;
    /**
     * Lent season names and descriptions
     */
    lent?: LentSeason | null;
    /**
     * Ordinary Time season names and descriptions
     */
    ordinary_time?: OrdinaryTimeSeason | null;
    /**
     * Paschal Triduum season names and descriptions
     */
    paschal_triduum?: PaschalTriduumSeason | null;
}

/**
 * Advent season localized names and descriptions.
 * Provides specific terminology for the Advent season in the locale language.
 */
export type AdventSeason = {
    /**
     * Privileged weekday terminology during Advent
     */
    privileged_weekday?: null | string;
    /**
     * General season name for Advent
     */
    season?: null | string;
    /**
     * Sunday terminology during Advent
     */
    sunday?: null | string;
    /**
     * Weekday terminology during Advent
     */
    weekday?: null | string;
}

/**
 * Christmas Time season localized names and descriptions.
 */
export type ChristmasTimeSeason = {
    /**
     * After Epiphany terminology
     */
    after_epiphany?: null | string;
    /**
     * Before Epiphany terminology
     */
    before_epiphany?: null | string;
    /**
     * Day terminology during Christmas Time
     */
    day?: null | string;
    /**
     * Octave terminology during Christmas Time
     */
    octave?: null | string;
    /**
     * General season name for Christmas Time
     */
    season?: null | string;
    /**
     * Second Sunday after Christmas terminology
     */
    second_sunday_after_christmas?: null | string;
}

/**
 * Easter Time season localized names and descriptions.
 */
export type EasterTimeSeason = {
    /**
     * Octave terminology during Easter Time
     */
    octave?: null | string;
    /**
     * General season name for Easter Time
     */
    season?: null | string;
    /**
     * Sunday terminology during Easter Time
     */
    sunday?: null | string;
    /**
     * Weekday terminology during Easter Time
     */
    weekday?: null | string;
}

/**
 * Lent season localized names and descriptions.
 */
export type LentSeason = {
    /**
     * Day after Ash Wednesday terminology
     */
    day_after_ash_wed?: null | string;
    /**
     * Holy Week day terminology
     */
    holy_week_day?: null | string;
    /**
     * General season name for Lent
     */
    season?: null | string;
    /**
     * Sunday terminology during Lent
     */
    sunday?: null | string;
    /**
     * Weekday terminology during Lent
     */
    weekday?: null | string;
}

/**
 * Ordinary Time season localized names and descriptions.
 */
export type OrdinaryTimeSeason = {
    /**
     * General season name for Ordinary Time
     */
    season?: null | string;
    /**
     * Sunday terminology during Ordinary Time
     */
    sunday?: null | string;
    /**
     * Weekday terminology during Ordinary Time
     */
    weekday?: null | string;
}

/**
 * Paschal Triduum season localized names and descriptions.
 */
export type PaschalTriduumSeason = {
    /**
     * General season name for Paschal Triduum
     */
    season?: null | string;
}

/**
 * The type of the calendar
 *
 * The type of the calendar.
 * Defines the scope and authority level of the liturgical calendar.
 *
 * General Roman Calendar (universal)
 *
 * Regional calendar (multiple countries)
 *
 * National calendar (single country)
 *
 * Archdiocesan calendar
 *
 * Diocesan calendar
 *
 * City calendar
 *
 * Parish calendar
 *
 * General religious community calendar
 *
 * Regional religious community calendar
 *
 * Local religious community calendar
 *
 * Other specialized calendar
 */
export enum CalendarType {
    Archdiocese = "ARCHDIOCESE",
    City = "CITY",
    Country = "COUNTRY",
    Diocese = "DIOCESE",
    GeneralCommunity = "GENERAL_COMMUNITY",
    GeneralRoman = "GENERAL_ROMAN",
    LocalCommunity = "LOCAL_COMMUNITY",
    Other = "OTHER",
    Parish = "PARISH",
    Region = "REGION",
    RegionalCommunity = "REGIONAL_COMMUNITY",
}

/**
 * Configuration options specific to this calendar.
 * These settings can override or extend the default Romcal configuration or any parent
 * calendar
 * configuration.
 */
export type ParticularConfig = {
    /**
     * Ascension is celebrated on a Sunday
     */
    ascension_on_sunday?: boolean | null;
    /**
     * Corpus Christi is celebrated on a Sunday
     */
    corpus_christi_on_sunday?: boolean | null;
    /**
     * The type of Easter calculation
     */
    easter_calculation_type?: EasterCalculationType | null;
    /**
     * Epiphany is celebrated on a Sunday
     */
    epiphany_on_sunday?: boolean | null;
}

/**
 * Gregorian calculation (default)
 *
 * Julian calculation converted to Gregorian
 */
export enum EasterCalculationType {
    Gregorian = "GREGORIAN",
    Julian = "JULIAN",
}
