#!/bin/bash

# Script to generate constants from JSON files
# This script scans all calendar and locale JSON files and generates Rust constants

DATA_DIR="../data"
OUTPUT_FILE="src/generated_constants.rs"

echo "Generating constants from JSON files..."

# Initialize arrays
CALENDAR_IDS=()
LOCALES=()

# Scan all calendar files - ID is the filename without extension
echo "Scanning calendar files..."
while IFS= read -r -d '' file; do
    # Extract filename without path and extension
    basename=$(basename "$file" .json)
    CALENDAR_IDS+=("$basename")
done < <(find "$DATA_DIR/calendars" -name "*.json" -type f -print0)

# Scan locales - only direct subdirectories of /resources (no sub-subdirectories)
echo "Scanning locales..."
if [ -d "$DATA_DIR/resources" ]; then
    for locale_dir in "$DATA_DIR/resources"/*; do
        if [ -d "$locale_dir" ]; then
            locale=$(basename "$locale_dir")
            LOCALES+=("$locale")
        fi
    done
fi

# Sort arrays
IFS=$'\n' CALENDAR_IDS=($(sort <<<"${CALENDAR_IDS[*]}"))
IFS=$'\n' LOCALES=($(sort <<<"${LOCALES[*]}"))

# Generate the constants file
echo "Generating constants file..."

cat > "$OUTPUT_FILE" << EOF
//! Auto-generated constants - Do not modify manually
//! This file is generated by the generate_constants.sh script

/// List of all calendar IDs
///
/// This constant contains all calendar IDs
/// in the romcal project, sorted alphabetically.
pub const CALENDAR_IDS: &[&str] = &[
EOF

# Add calendar IDs
for id in "${CALENDAR_IDS[@]}"; do
    echo "    \"$id\"," >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << EOF
];

/// List of all locale codes
///
/// This constant contains all locale codes
/// in the romcal project, sorted alphabetically.
pub const LOCALE_CODES: &[&str] = &[
EOF

# Add locales
for locale in "${LOCALES[@]}"; do
    echo "    \"$locale\"," >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << EOF
];
EOF

echo "Constants generated successfully:"
echo "  - ${#CALENDAR_IDS[@]} calendars found"
echo "  - ${#LOCALES[@]} locales found"
echo "  - File written: $OUTPUT_FILE"

# Format the generated file with rustfmt
echo "Formatting generated file with rustfmt..."
if command -v rustfmt &> /dev/null; then
    rustfmt "$OUTPUT_FILE"
    echo "  - File formatted with rustfmt"
else
    echo "  - Warning: rustfmt not found, skipping formatting"
fi
