# generated by datamodel-codegen:
#   filename:  all_types.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class CalendarType(Enum):
    """
    The type of the calendar.
    Defines the scope and authority level of the liturgical calendar.
    """

    GENERAL_ROMAN = 'GENERAL_ROMAN'
    REGION = 'REGION'
    COUNTRY = 'COUNTRY'
    ARCHDIOCESE = 'ARCHDIOCESE'
    DIOCESE = 'DIOCESE'
    CITY = 'CITY'
    PARISH = 'PARISH'
    GENERAL_COMMUNITY = 'GENERAL_COMMUNITY'
    REGIONAL_COMMUNITY = 'REGIONAL_COMMUNITY'
    LOCAL_COMMUNITY = 'LOCAL_COMMUNITY'
    OTHER = 'OTHER'


class CalendarJurisdiction(Enum):
    """
    The jurisdiction of the calendar.
    Determines whether the calendar follows ecclesiastical or civil authority.
    """

    ECCLESIASTICAL = 'ECCLESIASTICAL'
    CIVIL = 'CIVIL'


class EasterCalculationType(Enum):
    """
    Easter date calculation method.

    Determines which algorithm to use for calculating the date of Easter Sunday,
    which is the basis for most movable feasts in the liturgical calendar.
    """

    GREGORIAN = 'GREGORIAN'
    JULIAN = 'JULIAN'


class MonthIndex(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='Month index (1-12) with automatic validation\n\nThis type ensures that only valid month values are accepted during\ndeserialization. The value 1 represents January, 2 represents February, etc.',
            ge=0,
            le=255,
            title='MonthIndex',
        ),
    ]


class DateFn(Enum):
    """
    Date function for calculating liturgical dates.

    Represents movable feasts and special celebrations that require calculation
    based on Easter or other variable dates.
    """

    MARY_MOTHER_OF_THE_CHURCH = 'MARY_MOTHER_OF_THE_CHURCH'
    EPIPHANY_SUNDAY = 'EPIPHANY_SUNDAY'
    PRESENTATION_OF_THE_LORD = 'PRESENTATION_OF_THE_LORD'
    ANNUNCIATION = 'ANNUNCIATION'
    PALM_SUNDAY = 'PALM_SUNDAY'
    EASTER_SUNDAY = 'EASTER_SUNDAY'
    DIVINE_MERCY_SUNDAY = 'DIVINE_MERCY_SUNDAY'
    IMMACULATE_HEART_OF_MARY = 'IMMACULATE_HEART_OF_MARY'
    PENTECOST_SUNDAY = 'PENTECOST_SUNDAY'
    CORPUS_CHRISTI_SUNDAY = 'CORPUS_CHRISTI_SUNDAY'
    NATIVITY_OF_JOHN_THE_BAPTIST = 'NATIVITY_OF_JOHN_THE_BAPTIST'
    PETER_AND_PAUL_APOSTLES = 'PETER_AND_PAUL_APOSTLES'
    TRANSFIGURATION = 'TRANSFIGURATION'
    ASSUMPTION = 'ASSUMPTION'
    EXALTATION_OF_THE_HOLY_CROSS = 'EXALTATION_OF_THE_HOLY_CROSS'
    ALL_SAINTS = 'ALL_SAINTS'
    IMMACULATE_CONCEPTION_OF_MARY = 'IMMACULATE_CONCEPTION_OF_MARY'


class DayOfWeek(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='Day of week (0-6, where 0=Sunday) with automatic validation\n\nThis type ensures that only valid day-of-week values are accepted during\ndeserialization. The value 0 represents Sunday, 1 represents Monday, etc.',
            ge=0,
            le=255,
            title='DayOfWeek',
        ),
    ]


class ExceptionCondition3(BaseModel):
    """
    If the date falls on a specific day of the week
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    day_of_week: Annotated[DayOfWeek, Field(description='The day of the week to match')]


class DateDefWithOffset(BaseModel):
    """
    Date definition with offset for adjustments.
    Used when a date needs to be shifted by a specific number of days.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    day_offset: Annotated[
        int, Field(description='The number of days to offset the date')
    ]


class Precedence(Enum):
    """
    Liturgical precedence levels for determining which celebration takes priority.
    Defines the hierarchical order of liturgical celebrations according to UNLY norms.
    """

    TRIDUUM_1 = 'TRIDUUM_1'
    PROPER_OF_TIME_SOLEMNITY_2 = 'PROPER_OF_TIME_SOLEMNITY_2'
    PRIVILEGED_SUNDAY_2 = 'PRIVILEGED_SUNDAY_2'
    ASH_WEDNESDAY_2 = 'ASH_WEDNESDAY_2'
    WEEKDAY_OF_HOLY_WEEK_2 = 'WEEKDAY_OF_HOLY_WEEK_2'
    WEEKDAY_OF_EASTER_OCTAVE_2 = 'WEEKDAY_OF_EASTER_OCTAVE_2'
    GENERAL_SOLEMNITY_3 = 'GENERAL_SOLEMNITY_3'
    COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3 = (
        'COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3'
    )
    PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A = 'PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A'
    PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B = (
        'PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B'
    )
    PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C = (
        'PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C'
    )
    PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D = (
        'PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D'
    )
    GENERAL_LORD_FEAST_5 = 'GENERAL_LORD_FEAST_5'
    UNPRIVILEGED_SUNDAY_6 = 'UNPRIVILEGED_SUNDAY_6'
    GENERAL_FEAST_7 = 'GENERAL_FEAST_7'
    PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A = (
        'PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A'
    )
    PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B = (
        'PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B'
    )
    PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C = (
        'PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C'
    )
    PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D = (
        'PROPER_FEAST__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D'
    )
    PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E = (
        'PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E'
    )
    PROPER_FEAST_8F = 'PROPER_FEAST_8F'
    PRIVILEGED_WEEKDAY_9 = 'PRIVILEGED_WEEKDAY_9'
    GENERAL_MEMORIAL_10 = 'GENERAL_MEMORIAL_10'
    PROPER_MEMORIAL__SECOND_PATRON_11A = 'PROPER_MEMORIAL__SECOND_PATRON_11A'
    PROPER_MEMORIAL_11B = 'PROPER_MEMORIAL_11B'
    OPTIONAL_MEMORIAL_12 = 'OPTIONAL_MEMORIAL_12'
    WEEKDAY_13 = 'WEEKDAY_13'


class CommonDefinition(Enum):
    """
    Common definition for simplified categorization.
    Provides a simplified version of the Common enum for easier classification.
    """

    NONE = 'NONE'
    DEDICATION_ANNIVERSARY__INSIDE = 'DEDICATION_ANNIVERSARY__INSIDE'
    DEDICATION_ANNIVERSARY__OUTSIDE = 'DEDICATION_ANNIVERSARY__OUTSIDE'
    BLESSED_VIRGIN_MARY = 'BLESSED_VIRGIN_MARY'
    MARTYRS = 'MARTYRS'
    MISSIONARY_MARTYRS = 'MISSIONARY_MARTYRS'
    VIRGIN_MARTYRS = 'VIRGIN_MARTYRS'
    WOMAN_MARTYRS = 'WOMAN_MARTYRS'
    PASTORS = 'PASTORS'
    POPES = 'POPES'
    BISHOPS = 'BISHOPS'
    FOUNDERS = 'FOUNDERS'
    MISSIONARIES = 'MISSIONARIES'
    DOCTORS_OF_THE_CHURCH = 'DOCTORS_OF_THE_CHURCH'
    VIRGINS = 'VIRGINS'
    SAINTS = 'SAINTS'
    ABBOTS = 'ABBOTS'
    MONKS = 'MONKS'
    NUNS = 'NUNS'
    RELIGIOUS = 'RELIGIOUS'
    MERCY_WORKERS = 'MERCY_WORKERS'
    EDUCATORS = 'EDUCATORS'
    HOLY_WOMEN = 'HOLY_WOMEN'


class Title(Enum):
    """
    Titles and patronages associated with saints and blessed.
    Represents the various ecclesiastical titles and patronages that can be assigned to entities.
    """

    ABBESS = 'ABBESS'
    ABBOT = 'ABBOT'
    APOSTLE = 'APOSTLE'
    ARCHANGEL = 'ARCHANGEL'
    BISHOP = 'BISHOP'
    DEACON = 'DEACON'
    DOCTOR_OF_THE_CHURCH = 'DOCTOR_OF_THE_CHURCH'
    EMPRESS = 'EMPRESS'
    EVANGELIST = 'EVANGELIST'
    FIRST_BISHOP = 'FIRST_BISHOP'
    HERMIT = 'HERMIT'
    KING = 'KING'
    MARTYR = 'MARTYR'
    MISSIONARY = 'MISSIONARY'
    MONK = 'MONK'
    MOTHER_AND_QUEEN_OF_CHILE = 'MOTHER_AND_QUEEN_OF_CHILE'
    PARENTS_OF_THE_BLESSED_VIRGIN_MARY = 'PARENTS_OF_THE_BLESSED_VIRGIN_MARY'
    POPE = 'POPE'
    PATRIARCH = 'PATRIARCH'
    PILGRIM = 'PILGRIM'
    PRIEST = 'PRIEST'
    PROPHET = 'PROPHET'
    PROTO_MARTYR_OF_OCEANIA = 'PROTO_MARTYR_OF_OCEANIA'
    QUEEN = 'QUEEN'
    QUEEN_OF_POLAND = 'QUEEN_OF_POLAND'
    RELIGIOUS = 'RELIGIOUS'
    SLAVIC_MISSIONARY = 'SLAVIC_MISSIONARY'
    SPOUSE_OF_THE_BLESSED_VIRGIN_MARY = 'SPOUSE_OF_THE_BLESSED_VIRGIN_MARY'
    THE_FIRST_MARTYR = 'THE_FIRST_MARTYR'
    VIRGIN = 'VIRGIN'
    COPATRON_OF_EUROPE = 'COPATRON_OF_EUROPE'
    COPATRON_OF_IRELAND = 'COPATRON_OF_IRELAND'
    COPATRON_OF_CANADA = 'COPATRON_OF_CANADA'
    COPATRONESS_OF_EUROPE = 'COPATRONESS_OF_EUROPE'
    COPATRONESS_OF_FRANCE = 'COPATRONESS_OF_FRANCE'
    COPATRONESS_OF_IRELAND = 'COPATRONESS_OF_IRELAND'
    COPATRONESS_OF_ITALY_AND_EUROPE = 'COPATRONESS_OF_ITALY_AND_EUROPE'
    COPATRONESS_OF_THE_PHILIPPINES = 'COPATRONESS_OF_THE_PHILIPPINES'
    PATRON_OF_CANADA = 'PATRON_OF_CANADA'
    PATRON_OF_ENGLAND = 'PATRON_OF_ENGLAND'
    PATRON_OF_EUROPE = 'PATRON_OF_EUROPE'
    PATRON_OF_FRANCE = 'PATRON_OF_FRANCE'
    PATRON_OF_IRELAND = 'PATRON_OF_IRELAND'
    PATRON_OF_ITALY = 'PATRON_OF_ITALY'
    PATRON_OF_OCEANIA = 'PATRON_OF_OCEANIA'
    PATRON_OF_POLAND = 'PATRON_OF_POLAND'
    PATRON_OF_RUSSIA = 'PATRON_OF_RUSSIA'
    PATRON_OF_SCOTLAND = 'PATRON_OF_SCOTLAND'
    PATRON_OF_SPAIN = 'PATRON_OF_SPAIN'
    PATRON_OF_THE_CZECH_NATION = 'PATRON_OF_THE_CZECH_NATION'
    PATRON_OF_THE_DIOCESE = 'PATRON_OF_THE_DIOCESE'
    PATRON_OF_WALES = 'PATRON_OF_WALES'
    PATRONESS_OF_ALSACE = 'PATRONESS_OF_ALSACE'
    PATRONESS_OF_ARGENTINA = 'PATRONESS_OF_ARGENTINA'
    PATRONESS_OF_BRAZIL = 'PATRONESS_OF_BRAZIL'
    PATRONESS_OF_HUNGARY = 'PATRONESS_OF_HUNGARY'
    PATRONESS_OF_PUERTO_RICO = 'PATRONESS_OF_PUERTO_RICO'
    PATRONESS_OF_SLOVAKIA = 'PATRONESS_OF_SLOVAKIA'
    PATRONESS_OF_THE_AMERICAS = 'PATRONESS_OF_THE_AMERICAS'
    PATRONESS_OF_THE_PHILIPPINES = 'PATRONESS_OF_THE_PHILIPPINES'
    PATRONESS_OF_THE_PROVINCE_OF_QUEBEC = 'PATRONESS_OF_THE_PROVINCE_OF_QUEBEC'
    PATRONESS_OF_THE_USA = 'PATRONESS_OF_THE_USA'
    PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON = (
        'PATRON_OF_THE_CLERGY_OF_THE_ARCHDIOCESE_OF_LYON'
    )
    PATRON_OF_THE_CITY_OF_LYON = 'PATRON_OF_THE_CITY_OF_LYON'
    PATRONESS_OF_COSTA_RICA = 'PATRONESS_OF_COSTA_RICA'
    PRINCIPAL_PATRON_OF_THE_DIOCESE = 'PRINCIPAL_PATRON_OF_THE_DIOCESE'
    SECOND_PATRON_OF_THE_DIOCESE = 'SECOND_PATRON_OF_THE_DIOCESE'


class CompoundTitle(BaseModel):
    """
    Compound title definition for combining multiple titles.
    Allows adding titles to the beginning or end of an existing title list.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    append: Annotated[
        list[Title] | None,
        Field(
            description='The title(s) to add to the end of the existing list of title(s)'
        ),
    ] = None
    prepend: Annotated[
        list[Title] | None,
        Field(
            description='The title(s) to add to the beginning of the existing list of title(s)'
        ),
    ] = None


class SaintCount1(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='Represents the number of saints for an entity or a group of entities.\n\nCan be either a specific number (u32) or "MANY" to indicate\nan indeterminate number of saints.\n\n# Serialization\n- `Number(n)` serializes as integer `n`\n- `Many` serializes as string `"MANY"`\n\n# Deserialization\n- Integers are converted to `Number(u32)`\n- String `"MANY"` is converted to `Many`\n- All other types generate an error',
            ge=0,
            title='SaintCount',
        ),
    ]


class SaintCount(RootModel[SaintCount1 | str | None]):
    root: Annotated[
        SaintCount1 | str | None,
        Field(
            description='Represents the number of saints for an entity or a group of entities.\n\nCan be either a specific number (u32) or "MANY" to indicate\nan indeterminate number of saints.\n\n# Serialization\n- `Number(n)` serializes as integer `n`\n- `Many` serializes as string `"MANY"`\n\n# Deserialization\n- Integers are converted to `Number(u32)`\n- String `"MANY"` is converted to `Many`\n- All other types generate an error',
            title='SaintCount',
        ),
    ]


class Color(Enum):
    """
    Liturgical colors used in the celebration of Mass and other liturgical services.
    Each color has specific liturgical significance and is used during particular seasons or celebrations.
    """

    RED = 'RED'
    ROSE = 'ROSE'
    PURPLE = 'PURPLE'
    GREEN = 'GREEN'
    WHITE = 'WHITE'
    GOLD = 'GOLD'
    BLACK = 'BLACK'


class MassContent(BaseModel):
    """
    Content of a mass for a specific liturgical cycle
    Maps mass parts (readings, psalms, prayers, antiphons, etc.) to their texts
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    alleluia: Annotated[
        str | None, Field(description='Alleluia - acclamation before the Gospel')
    ] = None
    canticle: Annotated[
        str | None, Field(description='Canticle - biblical canticle')
    ] = None
    collect: Annotated[
        str | None, Field(description='Collect - opening prayer of the Mass')
    ] = None
    communion_antiphon: Annotated[
        str | None, Field(description='Communion Antiphon - chant during communion')
    ] = None
    easter_vigil_canticle_3: Annotated[
        str | None, Field(description='Canticle 3 (Easter Vigil)')
    ] = None
    easter_vigil_canticle_5: Annotated[
        str | None, Field(description='Canticle 5 (Easter Vigil)')
    ] = None
    easter_vigil_epistle: Annotated[
        str | None,
        Field(description='Epistle - reading from the epistles (Easter Vigil)'),
    ] = None
    easter_vigil_psalm_2: Annotated[
        str | None, Field(description='Psalm 2 (Easter Vigil)')
    ] = None
    easter_vigil_psalm_4: Annotated[
        str | None, Field(description='Psalm 4 (Easter Vigil)')
    ] = None
    easter_vigil_psalm_6: Annotated[
        str | None, Field(description='Psalm 6 (Easter Vigil)')
    ] = None
    easter_vigil_psalm_7: Annotated[
        str | None, Field(description='Psalm 7 (Easter Vigil)')
    ] = None
    easter_vigil_reading_3: Annotated[
        str | None, Field(description='Reading 3 - third reading (Easter Vigil)')
    ] = None
    easter_vigil_reading_4: Annotated[
        str | None, Field(description='Reading 4 - fourth reading (Easter Vigil)')
    ] = None
    easter_vigil_reading_5: Annotated[
        str | None, Field(description='Reading 5 - fifth reading (Easter Vigil)')
    ] = None
    easter_vigil_reading_6: Annotated[
        str | None, Field(description='Reading 6 - sixth reading (Easter Vigil)')
    ] = None
    easter_vigil_reading_7: Annotated[
        str | None, Field(description='Reading 7 - seventh reading (Easter Vigil)')
    ] = None
    entrance_antiphon: Annotated[
        str | None, Field(description='Entrance Antiphon - opening chant of the Mass')
    ] = None
    gospel: Annotated[
        str | None, Field(description='Gospel - reading from the Gospels')
    ] = None
    messianic_entry: Annotated[
        str | None,
        Field(
            description='Messianic entry reading (during the procession with palms, before the Mass of the Passion)'
        ),
    ] = None
    prayer_after_communion: Annotated[
        str | None, Field(description='Prayer after Communion - concluding prayer')
    ] = None
    prayer_over_the_offerings: Annotated[
        str | None,
        Field(description='Prayer over the Offerings - prayer during the offertory'),
    ] = None
    prayer_over_the_people: Annotated[
        str | None,
        Field(description='Prayer over the People - blessing over the congregation'),
    ] = None
    preface: Annotated[
        str | None,
        Field(description='Preface - introduction to the Eucharistic Prayer'),
    ] = None
    psalm: Annotated[str | None, Field(description='Psalm - responsorial psalm')] = None
    reading_1: Annotated[
        str | None,
        Field(description='Reading 1 - first reading (usually from the Old Testament)'),
    ] = None
    reading_2: Annotated[
        str | None,
        Field(
            description='Reading 2 - second reading (usually from the New Testament)'
        ),
    ] = None
    sequence: Annotated[
        str | None, Field(description='Sequence - special chant on certain feasts')
    ] = None
    solemn_blessing: Annotated[
        str | None,
        Field(description='Solemn Blessing - special blessing on certain occasions'),
    ] = None


class OrdinalFormat(Enum):
    """
    Format for displaying ordinal numbers.

    - `Letters`: Display ordinals as words (e.g., "first", "second", "premier", "deuxième")
    - `Numeric`: Display ordinals as numbers with suffixes (e.g., "1st", "2nd", "1er", "2e")
    """

    letters = 'letters'
    numeric = 'numeric'


class LocaleColors(BaseModel):
    """
    Liturgical color names in the locale language.
    Provides localized names for each liturgical color.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    black: Annotated[
        str | None, Field(description='Black color name in the locale language')
    ] = None
    gold: Annotated[
        str | None, Field(description='Gold color name in the locale language')
    ] = None
    green: Annotated[
        str | None, Field(description='Green color name in the locale language')
    ] = None
    purple: Annotated[
        str | None, Field(description='Purple color name in the locale language')
    ] = None
    red: Annotated[
        str | None, Field(description='Red color name in the locale language')
    ] = None
    rose: Annotated[
        str | None, Field(description='Rose color name in the locale language')
    ] = None
    white: Annotated[
        str | None, Field(description='White color name in the locale language')
    ] = None


class AdventSeason(BaseModel):
    """
    Advent season localized names and descriptions.
    Provides specific terminology for the Advent season in the locale language.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[
        str | None, Field(description='General season name for Advent')
    ] = None
    weekday: Annotated[
        str | None, Field(description='Weekday terminology during Advent')
    ] = None
    sunday: Annotated[
        str | None, Field(description='Sunday terminology during Advent')
    ] = None
    privileged_weekday: Annotated[
        str | None, Field(description='Privileged weekday terminology during Advent')
    ] = None


class ChristmasTimeSeason(BaseModel):
    """
    Christmas Time season localized names and descriptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[
        str | None, Field(description='General season name for Christmas Time')
    ] = None
    day: Annotated[
        str | None, Field(description='Day terminology during Christmas Time')
    ] = None
    octave: Annotated[
        str | None, Field(description='Octave terminology during Christmas Time')
    ] = None
    before_epiphany: Annotated[
        str | None, Field(description='Before Epiphany terminology')
    ] = None
    second_sunday_after_christmas: Annotated[
        str | None, Field(description='Second Sunday after Christmas terminology')
    ] = None
    after_epiphany: Annotated[
        str | None, Field(description='After Epiphany terminology')
    ] = None


class OrdinaryTimeSeason(BaseModel):
    """
    Ordinary Time season localized names and descriptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[
        str | None, Field(description='General season name for Ordinary Time')
    ] = None
    weekday: Annotated[
        str | None, Field(description='Weekday terminology during Ordinary Time')
    ] = None
    sunday: Annotated[
        str | None, Field(description='Sunday terminology during Ordinary Time')
    ] = None


class LentSeason(BaseModel):
    """
    Lent season localized names and descriptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[str | None, Field(description='General season name for Lent')] = (
        None
    )
    weekday: Annotated[
        str | None, Field(description='Weekday terminology during Lent')
    ] = None
    sunday: Annotated[
        str | None, Field(description='Sunday terminology during Lent')
    ] = None
    day_after_ash_wed: Annotated[
        str | None, Field(description='Day after Ash Wednesday terminology')
    ] = None
    holy_week_day: Annotated[
        str | None, Field(description='Holy Week day terminology')
    ] = None


class PaschalTriduumSeason(BaseModel):
    """
    Paschal Triduum season localized names and descriptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[
        str | None, Field(description='General season name for Paschal Triduum')
    ] = None


class EasterTimeSeason(BaseModel):
    """
    Easter Time season localized names and descriptions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    season: Annotated[
        str | None, Field(description='General season name for Easter Time')
    ] = None
    weekday: Annotated[
        str | None, Field(description='Weekday terminology during Easter Time')
    ] = None
    sunday: Annotated[
        str | None, Field(description='Sunday terminology during Easter Time')
    ] = None
    octave: Annotated[
        str | None, Field(description='Octave terminology during Easter Time')
    ] = None


class PeriodsMetadata(BaseModel):
    """
    Liturgical period names in the locale language.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    christmas_octave: Annotated[
        str | None, Field(description='Christmas Octave period name')
    ] = None
    days_before_epiphany: Annotated[
        str | None, Field(description='Days before Epiphany period name')
    ] = None
    days_from_epiphany: Annotated[
        str | None, Field(description='Days from Epiphany period name')
    ] = None
    christmas_to_presentation_of_the_lord: Annotated[
        str | None,
        Field(description='Christmas to Presentation of the Lord period name'),
    ] = None
    presentation_of_the_lord_to_holy_thursday: Annotated[
        str | None,
        Field(description='Presentation of the Lord to Holy Thursday period name'),
    ] = None
    holy_week: Annotated[str | None, Field(description='Holy Week period name')] = None
    paschal_triduum: Annotated[
        str | None, Field(description='Paschal Triduum period name')
    ] = None
    easter_octave: Annotated[
        str | None, Field(description='Easter Octave period name')
    ] = None
    early_ordinary_time: Annotated[
        str | None, Field(description='Early Ordinary Time period name')
    ] = None
    late_ordinary_time: Annotated[
        str | None, Field(description='Late Ordinary Time period name')
    ] = None


class RanksMetadata(BaseModel):
    """
    Liturgical rank names in the locale language.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    solemnity: Annotated[str | None, Field(description='Solemnity rank name')] = None
    sunday: Annotated[str | None, Field(description='Sunday rank name')] = None
    feast: Annotated[str | None, Field(description='Feast rank name')] = None
    memorial: Annotated[str | None, Field(description='Memorial rank name')] = None
    optional_memorial: Annotated[
        str | None, Field(description='Optional memorial rank name')
    ] = None
    weekday: Annotated[str | None, Field(description='Weekday rank name')] = None


class CyclesMetadata(BaseModel):
    """
    Liturgical cycle names in the locale language.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    proper_of_time: Annotated[
        str | None, Field(description='Proper of Time cycle name')
    ] = None
    proper_of_saints: Annotated[
        str | None, Field(description='Proper of Saints cycle name')
    ] = None
    sunday_year_a: Annotated[
        str | None, Field(description='Sunday Year A cycle name')
    ] = None
    sunday_year_b: Annotated[
        str | None, Field(description='Sunday Year B cycle name')
    ] = None
    sunday_year_c: Annotated[
        str | None, Field(description='Sunday Year C cycle name')
    ] = None
    weekday_year_1: Annotated[
        str | None, Field(description='Weekday Year 1 cycle name')
    ] = None
    weekday_year_2: Annotated[
        str | None, Field(description='Weekday Year 2 cycle name')
    ] = None
    psalter_week_1: Annotated[
        str | None, Field(description='Psalter Week 1 cycle name')
    ] = None
    psalter_week_2: Annotated[
        str | None, Field(description='Psalter Week 2 cycle name')
    ] = None
    psalter_week_3: Annotated[
        str | None, Field(description='Psalter Week 3 cycle name')
    ] = None
    psalter_week_4: Annotated[
        str | None, Field(description='Psalter Week 4 cycle name')
    ] = None


class EntityType(Enum):
    """
    The type of entity in the liturgical calendar.
    Defines whether the entity represents a person, place, or event.
    """

    PERSON = 'PERSON'
    PLACE = 'PLACE'
    EVENT = 'EVENT'


class CanonizationLevel(Enum):
    """
    Canonization level indicating the official recognition status of a person.
    Defines whether someone is beatified (Blessed) or canonized (Saint).
    """

    BLESSED = 'BLESSED'
    SAINT = 'SAINT'


class SaintDateDef3(BaseModel):
    """
    Century specification (e.g., 12 for 12th century)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    century: Annotated[int, Field(description='The century number', ge=0)]


class SaintDate1(RootModel[int]):
    root: Annotated[int, Field(description='Year only (e.g., 1234)', ge=0)]


class SaintDate(RootModel[SaintDate1 | str]):
    root: Annotated[
        SaintDate1 | str,
        Field(
            description='Saint date representation with different precision levels.\nSupports year-only, year-month, or full date specifications.'
        ),
    ]


class Sex(Enum):
    """
    Sex of a person.
    """

    MALE = 'MALE'
    FEMALE = 'FEMALE'


class Rank(Enum):
    """
    Liturgical rank indicating the importance and celebration style of a liturgical day
    """

    SOLEMNITY = 'SOLEMNITY'
    SUNDAY = 'SUNDAY'
    FEAST = 'FEAST'
    MEMORIAL = 'MEMORIAL'
    OPTIONAL_MEMORIAL = 'OPTIONAL_MEMORIAL'
    WEEKDAY = 'WEEKDAY'


class Season(Enum):
    """
    Liturgical seasons of the Church year.
    Represents the major periods that structure the liturgical calendar.
    """

    ADVENT = 'ADVENT'
    CHRISTMAS_TIME = 'CHRISTMAS_TIME'
    LENT = 'LENT'
    PASCHAL_TRIDUUM = 'PASCHAL_TRIDUUM'
    EASTER_TIME = 'EASTER_TIME'
    ORDINARY_TIME = 'ORDINARY_TIME'


class Period(Enum):
    """
    Specific periods within liturgical seasons.
    Defines sub-periods that have special liturgical characteristics or rules.
    """

    CHRISTMAS_OCTAVE = 'CHRISTMAS_OCTAVE'
    DAYS_BEFORE_EPIPHANY = 'DAYS_BEFORE_EPIPHANY'
    DAYS_FROM_EPIPHANY = 'DAYS_FROM_EPIPHANY'
    CHRISTMAS_TO_PRESENTATION_OF_THE_LORD = 'CHRISTMAS_TO_PRESENTATION_OF_THE_LORD'
    PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY = (
        'PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY'
    )
    HOLY_WEEK = 'HOLY_WEEK'
    PASCHAL_TRIDUUM = 'PASCHAL_TRIDUUM'
    EASTER_OCTAVE = 'EASTER_OCTAVE'
    EARLY_ORDINARY_TIME = 'EARLY_ORDINARY_TIME'
    LATE_ORDINARY_TIME = 'LATE_ORDINARY_TIME'


class Common(Enum):
    """
    Common prayers and readings for different categories of saints and celebrations.
    Provides standardized liturgical texts for various types of commemorations.
    """

    NONE = 'NONE'
    DEDICATION_ANNIVERSARY__INSIDE = 'DEDICATION_ANNIVERSARY__INSIDE'
    DEDICATION_ANNIVERSARY__OUTSIDE = 'DEDICATION_ANNIVERSARY__OUTSIDE'
    BLESSED_VIRGIN_MARY__ORDINARY_TIME = 'BLESSED_VIRGIN_MARY__ORDINARY_TIME'
    BLESSED_VIRGIN_MARY__ADVENT = 'BLESSED_VIRGIN_MARY__ADVENT'
    BLESSED_VIRGIN_MARY__CHRISTMAS = 'BLESSED_VIRGIN_MARY__CHRISTMAS'
    BLESSED_VIRGIN_MARY__EASTER = 'BLESSED_VIRGIN_MARY__EASTER'
    MARTYRS__OUTSIDE_EASTER__SEVERAL = 'MARTYRS__OUTSIDE_EASTER__SEVERAL'
    MARTYRS__OUTSIDE_EASTER__ONE = 'MARTYRS__OUTSIDE_EASTER__ONE'
    MARTYRS__EASTER__SEVERAL = 'MARTYRS__EASTER__SEVERAL'
    MARTYRS__EASTER__ONE = 'MARTYRS__EASTER__ONE'
    MARTYRS__MISSIONARY__SEVERAL = 'MARTYRS__MISSIONARY__SEVERAL'
    MARTYRS__MISSIONARY__ONE = 'MARTYRS__MISSIONARY__ONE'
    MARTYRS__VIRGIN = 'MARTYRS__VIRGIN'
    MARTYRS__WOMAN = 'MARTYRS__WOMAN'
    PASTORS__POPE_OR_BISHOP = 'PASTORS__POPE_OR_BISHOP'
    PASTORS__BISHOP = 'PASTORS__BISHOP'
    PASTORS__SEVERAL = 'PASTORS__SEVERAL'
    PASTORS__ONE = 'PASTORS__ONE'
    PASTORS__FOUNDER__ONE = 'PASTORS__FOUNDER__ONE'
    PASTORS__FOUNDER__SEVERAL = 'PASTORS__FOUNDER__SEVERAL'
    PASTORS__MISSIONARY = 'PASTORS__MISSIONARY'
    DOCTORS_OF_THE_CHURCH = 'DOCTORS_OF_THE_CHURCH'
    VIRGINS__SEVERAL = 'VIRGINS__SEVERAL'
    VIRGINS__ONE = 'VIRGINS__ONE'
    SAINTS__ALL__SEVERAL = 'SAINTS__ALL__SEVERAL'
    SAINTS__ALL__ONE = 'SAINTS__ALL__ONE'
    SAINTS__ABBOT = 'SAINTS__ABBOT'
    SAINT__MONK = 'SAINT__MONK'
    SAINTS__NUN = 'SAINTS__NUN'
    SAINTS__RELIGIOUS = 'SAINTS__RELIGIOUS'
    SAINTS__MERCY_WORKS = 'SAINTS__MERCY_WORKS'
    SAINTS__EDUCATORS = 'SAINTS__EDUCATORS'
    SAINTS__HOLY_WOMEN = 'SAINTS__HOLY_WOMEN'


class ColorInfo(BaseModel):
    """
    Liturgical color information with localized name.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: Annotated[Color, Field(description='The color key')]
    name: Annotated[str, Field(description='The localized name of the color')]


class MassTime(Enum):
    """
    Times of Mass celebrations in the liturgical calendar.
    Different Masses are celebrated at various times and occasions throughout the liturgical year.
    """

    easter_vigil = 'easter_vigil'
    previous_evening_mass = 'previous_evening_mass'
    night_mass = 'night_mass'
    mass_at_dawn = 'mass_at_dawn'
    morning_mass = 'morning_mass'
    mass_of_the_passion = 'mass_of_the_passion'
    celebration_of_the_passion = 'celebration_of_the_passion'
    day_mass = 'day_mass'
    chrism_mass = 'chrism_mass'
    evening_mass_of_the_lords_supper = 'evening_mass_of_the_lords_supper'


class SundayCycle(Enum):
    """
    A three-year cycle for Sunday Mass readings (and some solemnities), designated by A, B, or C.
    Each cycle begins on the First Sunday of Advent of the previous civil year and ends on Saturday
    after the Christ the King Solemnity. The cycles follow each other in alphabetical order.
    C year is always divisible by 3, A has remainder of 1, and B remainder of 2.
    """

    YEAR_A = 'YEAR_A'
    YEAR_B = 'YEAR_B'
    YEAR_C = 'YEAR_C'


class WeekdayCycle(Enum):
    """
    A two-year cycle for the weekday Mass readings (also called Cycle I and Cycle II).
    Odd-numbered years are the Cycle I (year 1); even-numbered ones are the Cycle II (year 2).
    """

    YEAR_1 = 'YEAR_1'
    YEAR_2 = 'YEAR_2'


class PsalterWeekCycle(Enum):
    """
    [GILH §133] The four-week cycle of the psalter is coordinated with the liturgical year in such a way that
    on the First Sunday of Advent, the First Sunday in Ordinary Time, the First Sunday of Lent,
    and Easter Sunday the cycle is always begun again with Week 1 (others being omitted when necessary).
    """

    WEEK_1 = 'WEEK_1'
    WEEK_2 = 'WEEK_2'
    WEEK_3 = 'WEEK_3'
    WEEK_4 = 'WEEK_4'


class CalendarContext(Enum):
    """
    Calendar year context for date boundaries.

    Determines how the calendar year is structured and which dates are included
    in a given year's calendar output.
    """

    GREGORIAN = 'GREGORIAN'
    LITURGICAL = 'LITURGICAL'


class SundayCycleCombined(Enum):
    """
    Combined Sunday cycle for cases where readings can apply to multiple years.
    This allows for flexible configuration where the same readings can be used
    across different combinations of Sunday cycles.
    """

    YEAR_A_B = 'YEAR_A_B'
    YEAR_A_C = 'YEAR_A_C'
    YEAR_B_C = 'YEAR_B_C'


class LiturgicalCycle(Enum):
    """
    Liturgical cycle for lectionary readings
    Includes both actual cycles (Year A, B, C, etc.) and invariant content
    """

    invariant = 'invariant'
    year_a = 'year_a'
    year_b = 'year_b'
    year_c = 'year_c'
    year_a_b = 'year_a_b'
    year_a_c = 'year_a_c'
    year_b_c = 'year_b_c'
    year_1 = 'year_1'
    year_2 = 'year_2'


class Acclamation(Enum):
    """
    Acclamations used in liturgical celebrations.
    Acclamations are short liturgical responses or exclamations used during Mass.
    """

    ALLELUIA = 'ALLELUIA'
    LENT = 'LENT'
    MIXED = 'MIXED'
    NONE = 'NONE'


class BibleBook(Enum):
    """
    Books of the Bible using OSIS (Open Scripture Information Standard) identifiers.
    OSIS provides standardized abbreviations for biblical books used in liturgical and biblical applications.
    """

    Gen = 'Gen'
    Exod = 'Exod'
    Lev = 'Lev'
    Num = 'Num'
    Deut = 'Deut'
    Josh = 'Josh'
    Judg = 'Judg'
    Ruth = 'Ruth'
    field_1Sam = '1Sam'
    field_2Sam = '2Sam'
    field_1Kgs = '1Kgs'
    field_2Kgs = '2Kgs'
    field_1Chr = '1Chr'
    field_2Chr = '2Chr'
    Ezra = 'Ezra'
    Neh = 'Neh'
    Tob = 'Tob'
    Jdt = 'Jdt'
    Esth = 'Esth'
    field_1Macc = '1Macc'
    field_2Macc = '2Macc'
    Job = 'Job'
    Ps = 'Ps'
    Prov = 'Prov'
    Eccl = 'Eccl'
    Song = 'Song'
    Wis = 'Wis'
    Sir = 'Sir'
    Isa = 'Isa'
    Jer = 'Jer'
    Lam = 'Lam'
    Bar = 'Bar'
    EpJer = 'EpJer'
    Ezek = 'Ezek'
    Dan = 'Dan'
    Hos = 'Hos'
    Joel = 'Joel'
    Amos = 'Amos'
    Obad = 'Obad'
    Jonah = 'Jonah'
    Mic = 'Mic'
    Nah = 'Nah'
    Hab = 'Hab'
    Zeph = 'Zeph'
    Hag = 'Hag'
    Zech = 'Zech'
    Mal = 'Mal'
    Matt = 'Matt'
    Mark = 'Mark'
    Luke = 'Luke'
    John = 'John'
    Acts = 'Acts'
    Rom = 'Rom'
    field_1Cor = '1Cor'
    field_2Cor = '2Cor'
    Gal = 'Gal'
    Eph = 'Eph'
    Phil = 'Phil'
    Col = 'Col'
    field_1Thess = '1Thess'
    field_2Thess = '2Thess'
    field_1Tim = '1Tim'
    field_2Tim = '2Tim'
    Titus = 'Titus'
    Phlm = 'Phlm'
    Heb = 'Heb'
    Jas = 'Jas'
    field_1Pet = '1Pet'
    field_2Pet = '2Pet'
    field_1John = '1John'
    field_2John = '2John'
    field_3John = '3John'
    Jude = 'Jude'
    Rev = 'Rev'


class MassPart(Enum):
    """
    Parts that make up the Mass celebration.
    Each part represents a specific element of the liturgical celebration.
    """

    messianic_entry = 'messianic_entry'
    entrance_antiphon = 'entrance_antiphon'
    collect = 'collect'
    reading_1 = 'reading_1'
    psalm = 'psalm'
    canticle = 'canticle'
    reading_2 = 'reading_2'
    easter_vigil_psalm_2 = 'easter_vigil_psalm_2'
    easter_vigil_reading_3 = 'easter_vigil_reading_3'
    easter_vigil_canticle_3 = 'easter_vigil_canticle_3'
    easter_vigil_reading_4 = 'easter_vigil_reading_4'
    easter_vigil_psalm_4 = 'easter_vigil_psalm_4'
    easter_vigil_reading_5 = 'easter_vigil_reading_5'
    easter_vigil_canticle_5 = 'easter_vigil_canticle_5'
    easter_vigil_reading_6 = 'easter_vigil_reading_6'
    easter_vigil_psalm_6 = 'easter_vigil_psalm_6'
    easter_vigil_reading_7 = 'easter_vigil_reading_7'
    easter_vigil_psalm_7 = 'easter_vigil_psalm_7'
    easter_vigil_epistle = 'easter_vigil_epistle'
    sequence = 'sequence'
    alleluia = 'alleluia'
    gospel = 'gospel'
    prayer_over_the_offerings = 'prayer_over_the_offerings'
    preface = 'preface'
    communion_antiphon = 'communion_antiphon'
    prayer_after_communion = 'prayer_after_communion'
    solemn_blessing = 'solemn_blessing'
    prayer_over_the_people = 'prayer_over_the_people'


class CalendarMetadata(BaseModel):
    """
    Metadata for a calendar.
    Contains essential information about the calendar's type and jurisdiction.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[CalendarType, Field(description='The type of the calendar')]
    jurisdiction: Annotated[
        CalendarJurisdiction, Field(description='The jurisdiction of the calendar')
    ]


class ParticularConfig(BaseModel):
    """
    Configuration options for "particular" (local/diocesan) calendars.

    In liturgical terminology, a "particular" calendar is one that applies to a specific
    region, diocese, or religious community, as opposed to the General Roman Calendar
    which applies universally.

    These settings can override or extend the default Romcal configuration or any parent
    calendar configuration.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    epiphany_on_sunday: Annotated[
        bool | None, Field(description='Epiphany is celebrated on a Sunday')
    ] = None
    ascension_on_sunday: Annotated[
        bool | None, Field(description='Ascension is celebrated on a Sunday')
    ] = None
    corpus_christi_on_sunday: Annotated[
        bool | None, Field(description='Corpus Christi is celebrated on a Sunday')
    ] = None
    easter_calculation_type: Annotated[
        EasterCalculationType | None,
        Field(description='The type of Easter calculation'),
    ] = None


class DateDef1(BaseModel):
    """
    Simple month/day specification
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    month: Annotated[MonthIndex, Field(description='The month (1-12)')]
    date: Annotated[int, Field(description='The day of the month (1-31)', ge=0, le=255)]
    day_offset: Annotated[
        int | None, Field(description='Optional day offset for adjustments')
    ] = None


class DateDef2(BaseModel):
    """
    Date function calculation (Easter, Epiphany, etc.)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    date_fn: Annotated[
        DateFn, Field(description='The date function to calculate the base date')
    ]
    day_offset: Annotated[
        int | None, Field(description='Optional day offset for adjustments')
    ] = None


class DateDef3(BaseModel):
    """
    Nth weekday of a specific month
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    month: Annotated[MonthIndex, Field(description='The month (1-12)')]
    day_of_week: Annotated[
        DayOfWeek, Field(description='The day of the week (0=Sunday, 1=Monday, etc.)')
    ]
    nth_week_in_month: Annotated[
        int,
        Field(
            description='Which occurrence of the weekday (1st, 2nd, 3rd, etc.)',
            ge=0,
            le=255,
        ),
    ]
    day_offset: Annotated[
        int | None, Field(description='Optional day offset for adjustments')
    ] = None


class DateDef4(BaseModel):
    """
    Last weekday of a specific month
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    month: Annotated[MonthIndex, Field(description='The month (1-12)')]
    last_day_of_week_in_month: Annotated[
        DayOfWeek,
        Field(description='The day of the week to find the last occurrence of'),
    ]
    day_offset: Annotated[
        int | None, Field(description='Optional day offset for adjustments')
    ] = None


class DateDef(RootModel[DateDef1 | DateDef2 | DateDef3 | DateDef4 | dict[str, Any]]):
    root: Annotated[
        DateDef1 | DateDef2 | DateDef3 | DateDef4 | dict[str, Any],
        Field(
            description='Date definition supporting various date calculation methods.\nProvides flexible ways to specify liturgical dates using different approaches.'
        ),
    ]


class ExceptionCondition1(BaseModel):
    """
    If the date is between two specified dates
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    from_: Annotated[
        DateDef, Field(alias='from', description='The start date of the range')
    ]
    to: Annotated[DateDef, Field(description='The end date of the range')]
    inclusive: Annotated[
        bool,
        Field(
            description='Whether the range is inclusive of the start date and the end date'
        ),
    ]


class ExceptionCondition2(BaseModel):
    """
    If the date is the same as another specified date
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    date: Annotated[DateDef, Field(description='The date to compare against')]


class ExceptionCondition(
    RootModel[ExceptionCondition1 | ExceptionCondition2 | ExceptionCondition3]
):
    root: Annotated[
        ExceptionCondition1 | ExceptionCondition2 | ExceptionCondition3,
        Field(
            description='Exception conditions that can trigger a date change.\nDefines various conditions under which a date exception applies.'
        ),
    ]


class DateDefExtended(RootModel[DateDef | DateDefWithOffset]):
    root: Annotated[
        DateDef | DateDefWithOffset,
        Field(
            description='Extended date definition supporting both regular dates and offset dates.\nProvides flexibility for date calculations with optional adjustments.'
        ),
    ]


class CommonsDef(RootModel[CommonDefinition | list[CommonDefinition]]):
    root: CommonDefinition | list[CommonDefinition]


class TitlesDef(RootModel[list[Title] | CompoundTitle]):
    root: Annotated[
        list[Title] | CompoundTitle,
        Field(
            description='Title definition that can be either a simple list or a compound definition.\nSupports both direct title lists and compound title operations.'
        ),
    ]


class ColorsDef(RootModel[Color | list[Color]]):
    root: Color | list[Color]


class MassCycleDefinition(BaseModel):
    """
    Mass contents for a specific mass time, organized by liturgical cycle
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    invariant: Annotated[
        MassContent | None,
        Field(description='Invariant content that applies to all cycles'),
    ] = None
    year_1: Annotated[
        MassContent | None, Field(description='Year 1 of the weekday cycle (Cycle I)')
    ] = None
    year_2: Annotated[
        MassContent | None, Field(description='Year 2 of the weekday cycle (Cycle II)')
    ] = None
    year_a: Annotated[
        MassContent | None, Field(description='Year A of the Sunday cycle')
    ] = None
    year_a_b: Annotated[
        MassContent | None,
        Field(description='Combined years A and B of the Sunday cycle'),
    ] = None
    year_a_c: Annotated[
        MassContent | None,
        Field(description='Combined years A and C of the Sunday cycle'),
    ] = None
    year_b: Annotated[
        MassContent | None, Field(description='Year B of the Sunday cycle')
    ] = None
    year_b_c: Annotated[
        MassContent | None,
        Field(description='Combined years B and C of the Sunday cycle'),
    ] = None
    year_c: Annotated[
        MassContent | None, Field(description='Year C of the Sunday cycle')
    ] = None


class SeasonsMetadata(BaseModel):
    """
    Liturgical season names and descriptions in the locale language.
    Provides localized names for each liturgical season and their components.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    advent: Annotated[
        AdventSeason | None, Field(description='Advent season names and descriptions')
    ] = None
    christmas_time: Annotated[
        ChristmasTimeSeason | None,
        Field(description='Christmas Time season names and descriptions'),
    ] = None
    ordinary_time: Annotated[
        OrdinaryTimeSeason | None,
        Field(description='Ordinary Time season names and descriptions'),
    ] = None
    lent: Annotated[
        LentSeason | None, Field(description='Lent season names and descriptions')
    ] = None
    paschal_triduum: Annotated[
        PaschalTriduumSeason | None,
        Field(description='Paschal Triduum season names and descriptions'),
    ] = None
    easter_time: Annotated[
        EasterTimeSeason | None,
        Field(description='Easter Time season names and descriptions'),
    ] = None


class SaintDateDef1(BaseModel):
    """
    Date range between two dates
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    between: Annotated[
        list[SaintDate],
        Field(
            description='The date range (start and end dates)',
            max_length=2,
            min_length=2,
        ),
    ]


class SaintDateDef2(BaseModel):
    """
    Multiple alternative dates (any one of them)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    or_: Annotated[
        list[SaintDate], Field(alias='or', description='The list of alternative dates')
    ]


class SaintDateDef(
    RootModel[SaintDate | SaintDateDef1 | SaintDateDef2 | SaintDateDef3]
):
    root: Annotated[
        SaintDate | SaintDateDef1 | SaintDateDef2 | SaintDateDef3,
        Field(
            description='Saint date definition supporting various date specifications.\nAllows single dates, date ranges, multiple alternatives, or century specifications.'
        ),
    ]


class PeriodInfo(BaseModel):
    """
    Liturgical period information with localized name.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: Annotated[Period, Field(description='The period key')]
    name: Annotated[str, Field(description='The localized name of the period')]


class CommonInfo(BaseModel):
    """
    Liturgical common information with localized name.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: Annotated[Common, Field(description='The common key')]
    name: Annotated[str, Field(description='The localized name of the common')]


class MassInfo(BaseModel):
    """
    Information about a mass celebration for a liturgical day.
    Contains the type of mass and its localized name.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        MassTime,
        Field(
            description='The type of mass (e.g., DayMass, EasterVigil, etc.)\nSerialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")'
        ),
    ]
    name: Annotated[
        str,
        Field(
            description='The localized name of the mass type (translation key in snake_case)'
        ),
    ]


class DateDefException(BaseModel):
    """
    The liturgical day date exception.
    Represents a condition and the date to set when that condition is met.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    when: Annotated[
        ExceptionCondition,
        Field(description='The condition that triggers the exception'),
    ]
    then: Annotated[
        DateDefExtended, Field(description='The date to set when the condition is met')
    ]


class EntityOverride(BaseModel):
    """
    Custom entity definition that extends or overrides properties from the entity catalog.
    Used when a liturgical day needs specific entity properties that differ from the base entity.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str,
        Field(
            description='The ID of the entity item (must reference an existing entity in the catalog)'
        ),
    ]
    titles: Annotated[
        TitlesDef | None,
        Field(
            description='The custom titles for this entity in the context of this liturgical day'
        ),
    ] = None
    hide_titles: Annotated[
        bool | None,
        Field(
            description='Whether to hide titles when displaying this entity (useful when titles are already included in the entity name)'
        ),
    ] = None
    count: Annotated[
        SaintCount | None,
        Field(
            description='The number of persons this entity represents (useful for groups of martyrs or saints)'
        ),
    ] = None


class MassesDefinitions(BaseModel):
    """
    All mass definitions for a liturgical day
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    celebration_of_the_passion: Annotated[
        MassCycleDefinition | None,
        Field(
            description="Celebration of the Passion - special celebration of Christ's passion"
        ),
    ] = None
    chrism_mass: Annotated[
        MassCycleDefinition | None,
        Field(
            description='Chrism Mass - Mass where holy oils are blessed, typically on Holy Thursday morning'
        ),
    ] = None
    day_mass: Annotated[
        MassCycleDefinition | None,
        Field(description='Day Mass - regular Mass celebrated during the day'),
    ] = None
    easter_vigil: Annotated[
        MassCycleDefinition | None,
        Field(
            description='Easter Vigil - the most important Mass of the liturgical year, celebrated on Holy Saturday night'
        ),
    ] = None
    evening_mass_of_the_lords_supper: Annotated[
        MassCycleDefinition | None,
        Field(
            description="Evening Mass of the Lord's Supper - Mass celebrated on Holy Thursday evening"
        ),
    ] = None
    mass_at_dawn: Annotated[
        MassCycleDefinition | None,
        Field(
            description='Mass at Dawn - Mass celebrated at dawn, particularly on Easter Sunday'
        ),
    ] = None
    mass_of_the_passion: Annotated[
        MassCycleDefinition | None,
        Field(
            description="Mass of the Passion - Mass focusing on Christ's passion, beginning with the procession with palms"
        ),
    ] = None
    morning_mass: Annotated[
        MassCycleDefinition | None,
        Field(description='Morning Mass - Mass celebrated in the morning'),
    ] = None
    night_mass: Annotated[
        MassCycleDefinition | None,
        Field(description='Night Mass - Mass celebrated during the night hours'),
    ] = None
    previous_evening_mass: Annotated[
        MassCycleDefinition | None,
        Field(
            description='Previous Evening Mass - Mass celebrated the evening before a major feast'
        ),
    ] = None


class ResourcesMetadata(BaseModel):
    """
    Metadata for localized resources.
    Contains all the localized strings and configurations for a specific locale.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ordinal_format: Annotated[
        OrdinalFormat | None,
        Field(
            description='Format for displaying ordinal numbers (defaults to Numeric if not specified)'
        ),
    ] = None
    ordinals_letters: Annotated[
        dict[str, Any] | None,
        Field(
            description='Ordinal numbers as words (first, second, third, etc.) in the locale language'
        ),
    ] = None
    ordinals_numeric: Annotated[
        dict[str, Any] | None,
        Field(
            description='Ordinal numbers as numeric with suffix (1st, 2nd, 3rd, etc.) in the locale language'
        ),
    ] = None
    weekdays: Annotated[
        dict[str, Any] | None,
        Field(
            description='Weekday names (Sunday, Monday, etc.) in the locale language'
        ),
    ] = None
    months: Annotated[
        dict[str, Any] | None,
        Field(
            description='Month names (January, February, etc.) in the locale language'
        ),
    ] = None
    colors: Annotated[
        LocaleColors | None,
        Field(description='Liturgical color names in the locale language'),
    ] = None
    seasons: Annotated[
        SeasonsMetadata | None,
        Field(
            description='Liturgical season names and descriptions in the locale language'
        ),
    ] = None
    periods: Annotated[
        PeriodsMetadata | None,
        Field(description='Liturgical period names in the locale language'),
    ] = None
    ranks: Annotated[
        RanksMetadata | None,
        Field(description='Liturgical rank names in the locale language'),
    ] = None
    cycles: Annotated[
        CyclesMetadata | None,
        Field(description='Liturgical cycle names in the locale language'),
    ] = None


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[
        str | None, Field(description='The unique identifier of the entity')
    ] = None
    type: Annotated[
        EntityType | None,
        Field(
            description='The type of the entity.\n\nDefaults to `EntityType::Person`.'
        ),
    ] = 'PERSON'
    fullname: Annotated[
        str | None, Field(description='The full name of the entity.')
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='The short name of the entity, without the canonization level and titles.'
        ),
    ] = None
    canonization_level: Annotated[
        CanonizationLevel | None,
        Field(description='The canonization level of a person.'),
    ] = None
    date_of_canonization: Annotated[
        SaintDateDef | None,
        Field(
            description="Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),\nor an object describing date range, multiple possible date, or a century."
        ),
    ] = None
    date_of_canonization_is_approximative: Annotated[
        bool | None,
        Field(
            description="Specify whether an approximate indicator should be added, when the date is displayed.\nFor example in English: 'c. 201'."
        ),
    ] = None
    date_of_beatification: Annotated[
        SaintDateDef | None,
        Field(
            description="Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),\nor an object describing date range, multiple possible date, or a century."
        ),
    ] = None
    date_of_beatification_is_approximative: Annotated[
        bool | None,
        Field(
            description="Specify whether an approximate indicator should be added, when the date is displayed.\nFor example in English: 'c. 201'."
        ),
    ] = None
    hide_canonization_level: Annotated[
        bool | None,
        Field(
            description="Specify if the canonization level should not be displayed.\nIt's generally the case when the canonization are already included in the name."
        ),
    ] = None
    titles: Annotated[
        list[Title] | None, Field(description='Titles of the Saint or the Blessed')
    ] = None
    sex: Annotated[
        Sex | None,
        Field(
            description='Determine if the Saint or the Blessed is a male or a female.'
        ),
    ] = None
    hide_titles: Annotated[
        bool | None,
        Field(
            description="Specify if the titles should not be displayed.\nIt's generally the case when titles are already included in the name."
        ),
    ] = None
    date_of_dedication: Annotated[
        SaintDateDef | None,
        Field(
            description="Date of Dedication of a church, basilica, or cathedral (or other place of worship),\nas a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),\nor an object describing date range, multiple possible date, or a century."
        ),
    ] = None
    date_of_birth: Annotated[
        SaintDateDef | None,
        Field(
            description="Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),\nor an object describing date range, multiple possible date, or a century."
        ),
    ] = None
    date_of_birth_is_approximative: Annotated[
        bool | None,
        Field(
            description="Specify whether an approximate indicator should be added, when the date is displayed.\nFor example in English: 'c. 201'."
        ),
    ] = None
    date_of_death: Annotated[
        SaintDateDef | None,
        Field(
            description="Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),\nor an object describing date range, multiple possible date, or a century."
        ),
    ] = None
    date_of_death_is_approximative: Annotated[
        bool | None,
        Field(
            description="Specify whether an approximate indicator should be added, when the date is displayed.\nFor example in English: 'c. 201'."
        ),
    ] = None
    count: Annotated[
        SaintCount | None,
        Field(
            description="Number of person that this definition represent.\nIt could be set as 'many' if the number is not defined."
        ),
    ] = None
    sources: Annotated[
        list[str] | None,
        Field(description='Sources for the information about this entity'),
    ] = None
    field_todo: Annotated[
        list[str] | None,
        Field(alias='_todo', description='Internal notes (not serialized).'),
    ] = None


class ParentOverride(BaseModel):
    """
    Represents the differences between a liturgical day definition and its parent definition.
    This is a lightweight structure that only contains fields that can be overridden.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    from_calendar_id: Annotated[
        str,
        Field(description='The ID of the calendar from which this override originates'),
    ]
    date_def: Annotated[
        DateDef | None, Field(description='The date definition if it was changed')
    ] = None
    date_exceptions: Annotated[
        list[DateDefException] | None,
        Field(description='The date exceptions if they were changed'),
    ] = None
    precedence: Annotated[
        Precedence | None, Field(description='The precedence if it was changed')
    ] = None
    rank: Annotated[Rank | None, Field(description='The rank if it was changed')] = None
    colors: Annotated[
        list[ColorInfo] | None, Field(description='The colors if they were changed')
    ] = None
    titles: Annotated[
        TitlesDef | None, Field(description='The titles if they were changed')
    ] = None
    commons_def: Annotated[
        list[CommonDefinition] | None,
        Field(description='The commons definition if it was changed'),
    ] = None
    is_holy_day_of_obligation: Annotated[
        bool | None,
        Field(description='The is_holy_day_of_obligation flag if it was changed'),
    ] = None
    is_optional: Annotated[
        bool | None, Field(description='The is_optional flag if it was changed')
    ] = None
    allow_similar_rank_items: Annotated[
        bool | None,
        Field(description='The allow_similar_rank_items flag if it was changed'),
    ] = None


class CelebrationSummary(BaseModel):
    """
    Summary of a celebration for use in optional celebrations list.
    Contains the essential fields from a LiturgicalDay that identify a celebration.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='The unique identifier of the liturgical day')]
    fullname: Annotated[str, Field(description='The full name of the liturgical day')]
    precedence: Annotated[
        Precedence,
        Field(description='The liturgical precedence for this liturgical day'),
    ]
    rank: Annotated[
        Rank, Field(description='The liturgical rank for this liturgical day')
    ]
    rank_name: Annotated[
        str, Field(description='The localized liturgical rank for this liturgical day')
    ]
    colors: Annotated[
        list[ColorInfo],
        Field(description='The liturgical colors for this liturgical day'),
    ]
    commons: Annotated[
        list[CommonInfo],
        Field(description='The common prayers/readings used for this celebration'),
    ]
    entities: Annotated[
        list[Entity],
        Field(
            description='The entities (Saints, Blessed, or Places) linked to this liturgical day'
        ),
    ]
    titles: Annotated[
        TitlesDef, Field(description='The titles for this liturgical day')
    ]
    is_holy_day_of_obligation: Annotated[
        bool, Field(description='Holy days of obligation')
    ]
    is_optional: Annotated[
        bool, Field(description='Indicates if this liturgical day is optional')
    ]
    from_calendar_id: Annotated[
        str,
        Field(
            description='The ID of the calendar where this liturgical day is defined'
        ),
    ]


class Resources(BaseModel):
    """
    Resources definition
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Annotated[str | None, Field(alias='$schema')] = None
    locale: Annotated[
        str,
        Field(description='Locale code of the resources, in BCP-47 IETF tag format'),
    ]
    metadata: Annotated[
        ResourcesMetadata | None, Field(description='Metadata of the resources')
    ] = None
    entities: Annotated[
        dict[str, Any] | None,
        Field(
            description='Entities of the resources: a person, a place, an event, etc.'
        ),
    ] = None


class LiturgicalDay(BaseModel):
    """
    A single day in the liturgical calendar with computed values and inheritance information.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='The unique identifier of the liturgical day')]
    fullname: Annotated[str, Field(description='The full name of the liturgical day')]
    date: Annotated[str, Field(description='The computed date of the liturgical day.')]
    date_def: Annotated[
        DateDef, Field(description='The date definition for this liturgical day.')
    ]
    date_exceptions: Annotated[
        list[DateDefException],
        Field(description='The date definition exceptions for this liturgical day.'),
    ]
    precedence: Annotated[
        Precedence,
        Field(description='The liturgical precedence for this liturgical day.'),
    ]
    rank: Annotated[
        Rank, Field(description='The liturgical rank for this liturgical day.')
    ]
    rank_name: Annotated[
        str, Field(description='The localized liturgical rank for this liturgical day.')
    ]
    allow_similar_rank_items: Annotated[
        bool,
        Field(
            description='Allows similar items with the same rank and same or lower precedence\nto coexist without this liturgical day overwriting them.'
        ),
    ]
    is_holy_day_of_obligation: Annotated[
        bool,
        Field(
            description='Holy days of obligation are days on which the faithful are expected to attend Mass,\nand engage in rest from work and recreation.'
        ),
    ]
    is_optional: Annotated[
        bool,
        Field(
            description='Indicates if this liturgical day is optional within a specific liturgical calendar.'
        ),
    ]
    season: Annotated[
        Season | None,
        Field(
            description='The liturgical seasons to which this liturgical day belongs.'
        ),
    ] = None
    season_name: Annotated[
        str | None, Field(description='The liturgical season name.')
    ] = None
    periods: Annotated[
        list[PeriodInfo],
        Field(
            description='The liturgical periods to which this liturgical day belongs.'
        ),
    ]
    commons: Annotated[
        list[CommonInfo],
        Field(
            description='The common prayers, readings, and chants used for celebrating saints or\nfeasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed\nVirgin Mary.'
        ),
    ]
    colors: Annotated[
        list[ColorInfo],
        Field(description='The liturgical colors for this liturgical day.'),
    ]
    masses: Annotated[
        list[MassInfo],
        Field(
            description='The masses celebrated on this liturgical day.\nMost days have a single DayMass, but some have multiple masses\n(e.g., Christmas: PreviousEveningMass, NightMass, MassAtDawn, DayMass).\nAliturgical days like Holy Saturday have an empty list.'
        ),
    ]
    titles: Annotated[
        TitlesDef, Field(description='The titles for this liturgical day.')
    ]
    entities: Annotated[
        list[Entity],
        Field(
            description='The entities (Saints, Blessed, or Places) linked to this liturgical day.'
        ),
    ]
    week_of_season: Annotated[
        int | None,
        Field(
            description='The week number of the current liturgical season.\nStarts from `1`, except in the seasons of lent,\nthe week of Ash Wednesday to the next Saturday is counted as `0`.',
            ge=0,
        ),
    ] = None
    day_of_season: Annotated[
        int | None,
        Field(description='The day number within the current liturgical season.', ge=0),
    ] = None
    day_of_week: Annotated[
        DayOfWeek,
        Field(
            description='The day of the week for this liturgical day.\nReturns a number from 0 (Sunday) to 6 (Saturday).'
        ),
    ]
    nth_day_of_week_in_month: Annotated[
        int,
        Field(
            description='The nth occurrence of this day of the week within the current month.\nFor example, the 3rd Sunday of the month would have nth_day_of_week_in_month = 3.',
            ge=0,
            le=255,
        ),
    ]
    start_of_season: Annotated[
        str | None,
        Field(
            description='The first day of the current liturgical season for this liturgical day.'
        ),
    ] = None
    end_of_season: Annotated[
        str | None,
        Field(
            description='The last day of the current liturgical season for this liturgical day.'
        ),
    ] = None
    start_of_liturgical_year: Annotated[
        str,
        Field(
            description='The first day of the current liturgical year for this liturgical day,\ni.e. the first Sunday of Advent.'
        ),
    ]
    end_of_liturgical_year: Annotated[
        str,
        Field(
            description='The last day of the current liturgical year for this liturgical day,\ni.e. the last Saturday of Ordinary Time, in the 34th week.'
        ),
    ]
    sunday_cycle: Annotated[
        SundayCycle,
        Field(description='The Sunday cycle to which this liturgical day belongs.'),
    ]
    sunday_cycle_name: Annotated[
        str,
        Field(
            description='The localized name of the Sunday cycle to which this liturgical day belongs.'
        ),
    ]
    weekday_cycle: Annotated[
        WeekdayCycle,
        Field(description='The weekday cycle to which this liturgical day belongs.'),
    ]
    weekday_cycle_name: Annotated[
        str,
        Field(
            description='The localized name of the weekday cycle to which this liturgical day belongs.'
        ),
    ]
    psalter_week: Annotated[
        PsalterWeekCycle,
        Field(
            description='The psalter week cycle to which this liturgical day belongs.'
        ),
    ]
    psalter_week_name: Annotated[
        str,
        Field(
            description='The localized name of the psalter week cycle to which this liturgical day belongs.'
        ),
    ]
    from_calendar_id: Annotated[
        str,
        Field(
            description='The ID of the calendar where this liturgical day is defined.\nIndicates the source calendar in the inheritance chain.'
        ),
    ]
    parent_overrides: Annotated[
        list[ParentOverride],
        Field(
            description='Contains the differences between this liturgical day and its parent definitions.\nEach element in the array represents the diff from a parent calendar definition.\nThe array is ordered from most general (e.g., general_roman) to most specific.'
        ),
    ]


class MassContext(BaseModel):
    """
    A flat structure representing a single mass with its full liturgical context.

    This is the main type for the mass-centric calendar view. It contains:
    - Mass identification (type, name, civil/liturgical dates)
    - Day-level context (season, cycles, periods)
    - Primary celebration data (flattened from LiturgicalDay)
    - Optional alternative celebrations

    For evening masses (Easter Vigil, Previous Evening Mass), the `civil_date`
    is shifted to the previous day while `liturgical_date` remains the original
    liturgical celebration date.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    mass_time: Annotated[
        MassTime,
        Field(
            description='The type of mass (e.g., DayMass, EasterVigil, etc.)\nSerialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")'
        ),
    ]
    mass_time_name: Annotated[
        str,
        Field(
            description='The localized name of the mass time (translation key in snake_case)'
        ),
    ]
    civil_date: Annotated[
        str,
        Field(
            description='The civil calendar date when this mass is celebrated (YYYY-MM-DD).\nFor evening masses (EasterVigil, PreviousEveningMass), this is the day\nBEFORE the liturgical date.'
        ),
    ]
    liturgical_date: Annotated[
        str,
        Field(
            description='The liturgical date this mass belongs to (YYYY-MM-DD).\nThis is the "theological" date of the celebration.'
        ),
    ]
    season: Annotated[Season | None, Field(description='The liturgical season')] = None
    season_name: Annotated[
        str | None, Field(description='The localized season name')
    ] = None
    sunday_cycle: Annotated[
        SundayCycle, Field(description='The Sunday cycle (Year A, B, or C)')
    ]
    sunday_cycle_name: Annotated[
        str, Field(description='The localized Sunday cycle name')
    ]
    weekday_cycle: Annotated[
        WeekdayCycle, Field(description='The weekday cycle (Year 1 or 2)')
    ]
    weekday_cycle_name: Annotated[
        str, Field(description='The localized weekday cycle name')
    ]
    psalter_week: Annotated[
        PsalterWeekCycle, Field(description='The psalter week cycle (Week 1-4)')
    ]
    psalter_week_name: Annotated[
        str, Field(description='The localized psalter week name')
    ]
    week_of_season: Annotated[
        int | None,
        Field(description='The week number within the liturgical season', ge=0),
    ] = None
    day_of_season: Annotated[
        int | None,
        Field(description='The day number within the liturgical season', ge=0),
    ] = None
    day_of_week: Annotated[
        DayOfWeek, Field(description='The day of the week (0=Sunday to 6=Saturday)')
    ]
    periods: Annotated[
        list[PeriodInfo],
        Field(description='The liturgical periods this day belongs to'),
    ]
    start_of_season: Annotated[
        str | None, Field(description='The first day of the current liturgical season')
    ] = None
    end_of_season: Annotated[
        str | None, Field(description='The last day of the current liturgical season')
    ] = None
    start_of_liturgical_year: Annotated[
        str,
        Field(
            description='The first day of the liturgical year (first Sunday of Advent)'
        ),
    ]
    end_of_liturgical_year: Annotated[
        str, Field(description='The last day of the liturgical year')
    ]
    id: Annotated[str, Field(description='The unique identifier of the liturgical day')]
    fullname: Annotated[str, Field(description='The full name of the liturgical day')]
    precedence: Annotated[Precedence, Field(description='The liturgical precedence')]
    rank: Annotated[Rank, Field(description='The liturgical rank')]
    rank_name: Annotated[str, Field(description='The localized liturgical rank name')]
    colors: Annotated[list[ColorInfo], Field(description='The liturgical colors')]
    commons: Annotated[
        list[CommonInfo], Field(description='The common prayers/readings used')
    ]
    entities: Annotated[
        list[Entity],
        Field(
            description='The entities (Saints, Blessed, or Places) linked to this day'
        ),
    ]
    titles: Annotated[
        TitlesDef, Field(description='The titles for this liturgical day')
    ]
    is_holy_day_of_obligation: Annotated[
        bool, Field(description='Whether this is a holy day of obligation')
    ]
    is_optional: Annotated[
        bool, Field(description='Whether this liturgical day is optional')
    ]
    from_calendar_id: Annotated[
        str,
        Field(
            description='The ID of the calendar where this liturgical day is defined'
        ),
    ]
    optional_celebrations: Annotated[
        list[CelebrationSummary],
        Field(
            description='Optional alternative celebrations (e.g., optional memorials)\nthat can be celebrated instead of the primary celebration.'
        ),
    ]


class DateDefExceptions(RootModel[DateDefException | list[DateDefException]]):
    root: Annotated[
        DateDefException | list[DateDefException],
        Field(
            description='Date exceptions that can be either a single exception or multiple exceptions.\nSupports both simple single exceptions and complex multiple exception scenarios.'
        ),
    ]


class EntityRef(RootModel[str | EntityOverride]):
    root: Annotated[
        str | EntityOverride,
        Field(
            description='A reference to an entity in the entity catalog.\nCan either reference an existing entity by ID or define a custom entity with additional properties.'
        ),
    ]


class DayDefinition(BaseModel):
    """
    Definition of a liturgical day with all its properties and configurations.
    It represents a complete liturgical day definition that can be used
    to generate calendar entries with proper precedence, colors, and entity associations.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    date_def: Annotated[
        DateDef | None, Field(description='The date definition for this liturgical day')
    ] = None
    date_exceptions: Annotated[
        DateDefExceptions | None,
        Field(
            description='The date definition exceptions (overrides for specific circumstances)'
        ),
    ] = None
    precedence: Annotated[
        Precedence | None,
        Field(description='The precedence type of the liturgical day'),
    ] = None
    commons_def: Annotated[
        CommonsDef | None,
        Field(
            description='The **Common** refers to a set of prayers, readings, and chants used for celebrating saints or\nfeasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed\nVirgin Mary.'
        ),
    ] = None
    is_holy_day_of_obligation: Annotated[
        bool | None,
        Field(
            description='Holy days of obligation are days on which the faithful are expected to attend Mass\nand engage in rest from work and recreation'
        ),
    ] = None
    allow_similar_rank_items: Annotated[
        bool | None,
        Field(
            description='Allow similar items that have the same rank and the same or lower precedence\nto coexist with this liturgical day without being overwritten'
        ),
    ] = None
    is_optional: Annotated[
        bool | None,
        Field(
            description='Specify if this liturgical day is optional within a specific liturgical calendar\n\nUNLY #14:\nMemorials are either obligatory or optional; their observance is integrated into\nthe celebration of the occurring weekday in accordance with the norms set forth in the\nGeneral Instruction of the Roman Missal and of the Liturgy of the Hours\n\nNote: also used for the dedication of consecrated churches, which is an optional solemnity\nthat should not overwrite the default weekday.'
        ),
    ] = None
    custom_locale_id: Annotated[
        str | None,
        Field(
            description='The custom locale ID for this date definition in this calendar'
        ),
    ] = None
    entities: Annotated[
        list[EntityRef] | None,
        Field(
            description='The entities (Saints, Blessed, or Places) linked from the Entity catalog'
        ),
    ] = None
    titles: Annotated[
        TitlesDef | None,
        Field(
            description='The combined titles of all entities linked to this date definition'
        ),
    ] = None
    drop: Annotated[
        bool | None,
        Field(
            description='If this liturgical day must be removed from this calendar and from all parent calendars\nin the final calendar generated by romcal'
        ),
    ] = None
    colors: Annotated[
        ColorsDef | None,
        Field(
            description='The liturgical color(s) of the liturgical day.\n\n**Deprecated:** Rely on the `titles` field of entities instead to determine the liturgical color(s).'
        ),
    ] = None
    masses: Annotated[
        MassesDefinitions | None,
        Field(description='The masses definitions for this liturgical day'),
    ] = None


class CalendarDefinition(BaseModel):
    """
    Calendar definition
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Annotated[str | None, Field(alias='$schema')] = None
    id: str
    metadata: CalendarMetadata
    particular_config: ParticularConfig | None = None
    parent_calendar_ids: list[str]
    days_definitions: dict[str, DayDefinition]


class AllTypes(BaseModel):
    liturgicalDay: LiturgicalDay | None = None
    calendarDefinition: CalendarDefinition | None = None
    resources: Resources | None = None
    massContext: MassContext | None = None
    celebrationSummary: CelebrationSummary | None = None
    calendarContext: CalendarContext | None = None
    sundayCycleCombined: SundayCycleCombined | None = None
    monthIndex: MonthIndex | None = None
    dayOfWeek: DayOfWeek | None = None
    dateDefWithOffset: DateDefWithOffset | None = None
    liturgicalCycle: LiturgicalCycle | None = None
    acclamation: Acclamation | None = None
    bibleBook: BibleBook | None = None
    massPart: MassPart | None = None
    saintCount: SaintCount | None = None
