name: Dev Publishing

on:
  push:
    branches:
      - dev-ga-xp

jobs:
  dev_publishing:
    runs-on: ubuntu-latest

    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        with:
          ref: dev-ga-xp

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        with:
          major-wording: 'MajorBump'
          minor-wording: 'MinorBump'
          patch-wording: 'PatchBump'
          rc-wording:
          default: prerelease
          preid: dev
          commit-message: 'ci: bumps version to {{version}}'

