name: Dev branch publishing

on:
  push:
    branches:
      - dev-ga-xp

jobs:
  dev_branch_publishing:
    runs-on: ubuntu-latest

    environment: npm-publish

#    if: github.repository == 'romcal/romcal'

    env:
      CI: true
      GITHUB_USER: romcalproject
      GITHUB_EMAIL: romcalproject@gmail.com

    steps:
      - name: Git checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev-ga-xp

      - name: Install node.js and npm
        uses: volta-cli/action@v1

      - name: Automated version bump
        uses: emagnier/gh-action-bump-version@skip-commit
        with:
          major-wording: 'MajorBump'
          minor-wording: 'MinorBump'
          patch-wording: 'PatchBump'
          rc-wording:
          default: prerelease
          preid: dev
          tag-prefix:  'v'
#          skip-commit: true
          commit-message: 'ci: bump version to {{version}}'

      - name: Install npm dependencies
        run: npm ci --no-audit

      - name: Update browsers list (caniuse)
        run: npx browserslist@latest --update-db

      - name: Build romcal project (romcal + all calendar bundles)
        run: npm run build

      - name: Run tests
        run: npm run test:without-coverage


#      - name: Npm publish a new 'dev' version (romcal + all calendar bundles)
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#        run: node -r ts-node/register scripts/publish.ts
