name: Romcal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci --no-audit
    - run: npm run lint
    - run: npm run bundle
    - run: npm run type
    - run: npm run pack
    - run: npm test

    env:
      CI: true
