// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acclamations used in liturgical celebrations.
 * Acclamations are short liturgical responses or exclamations used during Mass.
 */
export type Acclamation = 'ALLELUIA' | 'LENT' | 'MIXED' | 'NONE'
