// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Books of the Bible using OSIS (Open Scripture Information Standard) identifiers.
 * OSIS provides standardized abbreviations for biblical books used in liturgical and biblical applications.
 */
export type BibleBook = "Gen" | "Exod" | "Lev" | "Num" | "Deut" | "Josh" | "Judg" | "Ruth" | "1Sam" | "2Sam" | "1Kgs" | "2Kgs" | "1Chr" | "2Chr" | "Ezra" | "Neh" | "Tob" | "Jdt" | "Esth" | "1Macc" | "2Macc" | "Job" | "Ps" | "Prov" | "Eccl" | "Song" | "Wis" | "Sir" | "Isa" | "Jer" | "Lam" | "Bar" | "EpJer" | "Ezek" | "Dan" | "Hos" | "Joel" | "Amos" | "Obad" | "Jonah" | "Mic" | "Nah" | "Hab" | "Zeph" | "Hag" | "Zech" | "Mal" | "Matt" | "Mark" | "Luke" | "John" | "Acts" | "Rom" | "1Cor" | "2Cor" | "Gal" | "Eph" | "Phil" | "Col" | "1Thess" | "2Thess" | "1Tim" | "2Tim" | "Titus" | "Phlm" | "Heb" | "Jas" | "1Pet" | "2Pet" | "1John" | "2John" | "3John" | "Jude" | "Rev";
