// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar year context for date boundaries.
 *
 * Determines how the calendar year is structured and which dates are included
 * in a given year's calendar output.
 */
export type CalendarContext = "GREGORIAN" | "LITURGICAL";
