// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of the calendar.
 * Defines the scope and authority level of the liturgical calendar.
 */
export type CalendarType =
  | 'GENERAL_ROMAN'
  | 'REGION'
  | 'COUNTRY'
  | 'ARCHDIOCESE'
  | 'DIOCESE'
  | 'CITY'
  | 'PARISH'
  | 'GENERAL_COMMUNITY'
  | 'REGIONAL_COMMUNITY'
  | 'LOCAL_COMMUNITY'
  | 'OTHER'
