// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarMetadata } from "./CalendarMetadata";
import type { DayDefinition } from "./DayDefinition";
import type { ParticularConfig } from "./ParticularConfig";

/**
 * Calendar definition
 */
export type CalendarDefinition = { $schema: string | null, id: string, metadata: CalendarMetadata, particular_config: ParticularConfig | null, parent_calendar_ids: Array<string>, days_definitions: { [key in string]?: DayDefinition }, };
