// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of the calendar.
 * Defines the scope and authority level of the liturgical calendar.
 */
export type CalendarType =
  | 'general_roman'
  | 'region'
  | 'country'
  | 'archdiocese'
  | 'diocese'
  | 'city'
  | 'parish'
  | 'general_community'
  | 'regional_community'
  | 'local_community'
  | 'other'
