// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The jurisdiction of the calendar.
 * Determines whether the calendar follows ecclesiastical or civil authority.
 */
export type CalendarJurisdiction = 'ecclesiastical' | 'civil'
