// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonization level indicating the official recognition status of a person.
 * Defines whether someone is beatified (Blessed) or canonized (Saint).
 */
export type CanonizationLevel = 'blessed' | 'saint'
