// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInfo } from './ColorInfo'
import type { CommonInfo } from './CommonInfo'
import type { Entity } from './Entity'
import type { Precedence } from './Precedence'
import type { Rank } from './Rank'
import type { TitlesDef } from './TitlesDef'

/**
 * Summary of a celebration for use in optional celebrations list.
 * Contains the essential fields from a LiturgicalDay that identify a celebration.
 */
export type CelebrationSummary = {
  /**
   * The unique identifier of the liturgical day
   */
  id: string
  /**
   * The full name of the liturgical day
   */
  fullname: string
  /**
   * The liturgical precedence for this liturgical day
   */
  precedence: Precedence
  /**
   * The liturgical rank for this liturgical day
   */
  rank: Rank
  /**
   * The localized liturgical rank for this liturgical day
   */
  rank_name: string
  /**
   * The liturgical colors for this liturgical day
   */
  colors: Array<ColorInfo>
  /**
   * The common prayers/readings used for this celebration
   */
  commons: Array<CommonInfo>
  /**
   * The entities (Saints, Blessed, or Places) linked to this liturgical day
   */
  entities: Array<Entity>
  /**
   * The titles for this liturgical day
   */
  titles: TitlesDef
  /**
   * Holy days of obligation
   */
  is_holy_day_of_obligation: boolean
  /**
   * Indicates if this liturgical day is optional
   */
  is_optional: boolean
  /**
   * The ID of the calendar where this liturgical day is defined
   */
  from_calendar_id: string
}
