// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical colors used in the celebration of Mass and other liturgical services.
 * Each color has specific liturgical significance and is used during particular seasons or celebrations.
 */
export type Color = 'red' | 'rose' | 'purple' | 'green' | 'white' | 'gold' | 'black'
