// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from './Color'

/**
 * Liturgical color information with localized name.
 */
export type ColorInfo = {
  /**
   * The color key
   */
  key: Color
  /**
   * The localized name of the color
   */
  name: string
}
