// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Common } from "./Common";

/**
 * Liturgical common information with localized name.
 */
export type CommonInfo = { 
/**
 * The common key
 */
key: Common, 
/**
 * The localized name of the common
 */
name: string, };
