// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Common definition for simplified categorization.
 * Provides a simplified version of the Common enum for easier classification.
 */
export type CommonDefinition =
  | 'none'
  | 'dedication_anniversary__inside'
  | 'dedication_anniversary__outside'
  | 'blessed_virgin_mary'
  | 'martyrs'
  | 'missionary_martyrs'
  | 'virgin_martyrs'
  | 'woman_martyrs'
  | 'pastors'
  | 'popes'
  | 'bishops'
  | 'founders'
  | 'missionaries'
  | 'doctors_of_the_church'
  | 'virgins'
  | 'saints'
  | 'abbots'
  | 'monks'
  | 'nuns'
  | 'religious'
  | 'mercy_workers'
  | 'educators'
  | 'holy_women'
