// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommonDefinition } from "./CommonDefinition";

export type CommonsDef = CommonDefinition | Array<CommonDefinition>;
