// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Title } from './Title'

/**
 * Compound title definition for combining multiple titles.
 * Allows adding titles to the beginning or end of an existing title list.
 */
export type CompoundTitle = {
  /**
   * The title(s) to add to the end of the existing list of title(s)
   */
  append: Array<Title> | null
  /**
   * The title(s) to add to the beginning of the existing list of title(s)
   */
  prepend: Array<Title> | null
}
