// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical cycle names in the locale language.
 */
export type CyclesMetadata = {
  /**
   * Proper of Time cycle name
   */
  proper_of_time: string | null
  /**
   * Proper of Saints cycle name
   */
  proper_of_saints: string | null
  /**
   * Sunday Year A cycle name
   */
  sunday_year_a: string | null
  /**
   * Sunday Year B cycle name
   */
  sunday_year_b: string | null
  /**
   * Sunday Year C cycle name
   */
  sunday_year_c: string | null
  /**
   * Weekday Year 1 cycle name
   */
  weekday_year_1: string | null
  /**
   * Weekday Year 2 cycle name
   */
  weekday_year_2: string | null
  /**
   * Psalter Week 1 cycle name
   */
  psalter_week_1: string | null
  /**
   * Psalter Week 2 cycle name
   */
  psalter_week_2: string | null
  /**
   * Psalter Week 3 cycle name
   */
  psalter_week_3: string | null
  /**
   * Psalter Week 4 cycle name
   */
  psalter_week_4: string | null
}
