// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date function for calculating liturgical dates.
 *
 * Represents movable feasts and special celebrations that require calculation
 * based on Easter or other variable dates.
 */
export type DateFn =
  | 'MARY_MOTHER_OF_THE_CHURCH'
  | 'EPIPHANY_SUNDAY'
  | 'PRESENTATION_OF_THE_LORD'
  | 'ANNUNCIATION'
  | 'PALM_SUNDAY'
  | 'EASTER_SUNDAY'
  | 'DIVINE_MERCY_SUNDAY'
  | 'IMMACULATE_HEART_OF_MARY'
  | 'PENTECOST_SUNDAY'
  | 'CORPUS_CHRISTI_SUNDAY'
  | 'NATIVITY_OF_JOHN_THE_BAPTIST'
  | 'PETER_AND_PAUL_APOSTLES'
  | 'TRANSFIGURATION'
  | 'ASSUMPTION'
  | 'EXALTATION_OF_THE_HOLY_CROSS'
  | 'ALL_SAINTS'
  | 'IMMACULATE_CONCEPTION_OF_MARY'
