// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateDefExtended } from './DateDefExtended'
import type { ExceptionCondition } from './ExceptionCondition'

/**
 * The liturgical day date exception.
 * Represents a condition and the date to set when that condition is met.
 */
export type DateDefException = {
  /**
   * The condition that triggers the exception
   */
  when: ExceptionCondition
  /**
   * The date to set when the condition is met
   */
  then: DateDefExtended
}
