// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date function for calculating liturgical dates.
 *
 * Represents movable feasts and special celebrations that require calculation
 * based on Easter or other variable dates.
 */
export type DateFn =
  | 'mary_mother_of_the_church'
  | 'epiphany_sunday'
  | 'presentation_of_the_lord'
  | 'annunciation'
  | 'palm_sunday'
  | 'easter_sunday'
  | 'divine_mercy_sunday'
  | 'immaculate_heart_of_mary'
  | 'pentecost_sunday'
  | 'corpus_christi_sunday'
  | 'nativity_of_john_the_baptist'
  | 'peter_and_paul_apostles'
  | 'transfiguration'
  | 'assumption'
  | 'exaltation_of_the_holy_cross'
  | 'all_saints'
  | 'immaculate_conception_of_mary'
