// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date definition with offset for adjustments.
 * Used when a date needs to be shifted by a specific number of days.
 */
export type DateDefWithOffset = { 
/**
 * The number of days to offset the date
 */
day_offset: number, };
