// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateDefException } from './DateDefException'

/**
 * Date exceptions that can be either a single exception or multiple exceptions.
 * Supports both simple single exceptions and complex multiple exception scenarios.
 */
export type DateDefExceptions = DateDefException | Array<DateDefException>
