// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFn } from "./DateFn";
import type { DayOfWeek } from "./DayOfWeek";
import type { MonthIndex } from "./MonthIndex";

/**
 * Date definition supporting various date calculation methods.
 * Provides flexible ways to specify liturgical dates using different approaches.
 */
export type DateDef = { 
/**
 * The month (1-12)
 */
month: MonthIndex, 
/**
 * The day of the month (1-31)
 */
date: number, 
/**
 * Optional day offset for adjustments
 */
day_offset: number | null, } | { 
/**
 * The date function to calculate the base date
 */
date_fn: DateFn, 
/**
 * Optional day offset for adjustments
 */
day_offset: number | null, } | { 
/**
 * The month (1-12)
 */
month: MonthIndex, 
/**
 * The day of the week (0=Sunday, 1=Monday, etc.)
 */
day_of_week: DayOfWeek, 
/**
 * Which occurrence of the weekday (1st, 2nd, 3rd, etc.)
 */
nth_week_in_month: number, 
/**
 * Optional day offset for adjustments
 */
day_offset: number | null, } | { 
/**
 * The month (1-12)
 */
month: MonthIndex, 
/**
 * The day of the week to find the last occurrence of
 */
last_day_of_week_in_month: DayOfWeek, 
/**
 * Optional day offset for adjustments
 */
day_offset: number | null, } | Record<string, never>;
