// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorsDef } from './ColorsDef'
import type { CommonsDef } from './CommonsDef'
import type { DateDef } from './DateDef'
import type { DateDefExceptions } from './DateDefExceptions'
import type { MartyrologyRef } from './MartyrologyRef'
import type { MassesDefinitions } from './MassesDefinitions'
import type { Precedence } from './Precedence'
import type { TitlesDef } from './TitlesDef'

/**
 * Definition of a liturgical day with all its properties and configurations.
 * It represents a complete liturgical day definition that can be used
 * to generate calendar entries with proper precedence, colors, and martyrology associations.
 */
export type DayDefinition = {
  /**
   * The date definition for this liturgical day
   */
  date_def: DateDef | null
  /**
   * The date definition exceptions (overrides for specific circumstances)
   */
  date_exceptions: DateDefExceptions | null
  /**
   * The precedence type of the liturgical day
   */
  precedence: Precedence | null
  /**
   * The **Common** refers to a set of prayers, readings, and chants used for celebrating saints or
   * feasts that belong to a specific category, such as martyrs, virgins, pastors, or the Blessed
   * Virgin Mary.
   */
  commons_def: CommonsDef | null
  /**
   * Holy days of obligation are days on which the faithful are expected to attend Mass
   * and engage in rest from work and recreation
   */
  is_holy_day_of_obligation: boolean | null
  /**
   * Allow similar items that have the same rank and the same or lower precedence
   * to coexist with this liturgical day without being overwritten
   */
  allow_similar_rank_items: boolean | null
  /**
   * Specify if this liturgical day is optional within a specific liturgical calendar
   *
   * GNLY #14:
   * Memorials are either obligatory or optional; their observance is integrated into
   * the celebration of the occurring weekday in accordance with the norms set forth in the
   * General Instruction of the Roman Missal and of the Liturgy of the Hours
   *
   * Note: also used for the dedication of consecrated churches, which is an optional solemnity
   * that should not overwrite the default weekday.
   */
  is_optional: boolean | null
  /**
   * The custom locale ID for this date definition in this calendar
   */
  custom_locale_id: string | null
  /**
   * The martyrology entries (Saints, Blessed, or Places) linked from the martyrology catalog
   */
  martyrology: Array<MartyrologyRef> | null
  /**
   * The combined titles of all entries linked to this date definition
   */
  titles: TitlesDef | null
  /**
   * If this liturgical day must be removed from this calendar and from all parent calendars
   * in the final calendar generated by romcal
   */
  drop: boolean | null
  /**
   * The liturgical color(s) of the liturgical day.
   *
   * **Deprecated:** Rely on the `titles` field of entries instead to determine the liturgical color(s).
   */
  colors: ColorsDef | null
  /**
   * The masses definitions for this liturgical day
   */
  masses: MassesDefinitions | null
}
