// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Day of week (0-6, where 0=Sunday) with automatic validation
 *
 * This type ensures that only valid day-of-week values are accepted during
 * deserialization. The value 0 represents Sunday, 1 represents Monday, etc.
 */
export type DayOfWeek = number;
