// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Easter Time season localized names and descriptions.
 */
export type EasterTimeSeason = { 
/**
 * General season name for Easter Time
 */
season: string | null, 
/**
 * Weekday terminology during Easter Time
 */
weekday: string | null, 
/**
 * Sunday terminology during Easter Time
 */
sunday: string | null, 
/**
 * Octave terminology during Easter Time
 */
octave: string | null, };
