// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Easter date calculation method.
 *
 * Determines which algorithm to use for calculating the date of Easter Sunday,
 * which is the basis for most movable feasts in the liturgical calendar.
 */
export type EasterCalculationType = "GREGORIAN" | "JULIAN";
