// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonizationLevel } from './CanonizationLevel'
import type { EntityType } from './EntityType'
import type { Sex } from './Sex'
import type { Title } from './Title'

/**
 * Query parameters for searching entities.
 *
 * All fields are optional. When a field is `None`, it is not used for filtering.
 * When `text` is provided, fuzzy matching is performed on entity ID, fullname, and name.
 */
export type EntityQuery = {
  /**
   * Fuzzy text search on id, fullname, and name fields.
   */
  text?: string
  /**
   * Filter by entity type (Person, Place, Event).
   */
  entity_type?: EntityType
  /**
   * Filter by canonization level (Saint, Blessed).
   */
  canonization_level?: CanonizationLevel
  /**
   * Filter by sex (Male, Female).
   */
  sex?: Sex
  /**
   * Filter by titles. Entity must have at least one of the specified titles.
   */
  titles?: Array<Title>
  /**
   * Maximum number of results to return.
   * Default: 20 (applied in search logic).
   */
  limit?: number
  /**
   * Minimum score threshold (0.0 to 1.0).
   * Default: 0.3 (applied in search logic).
   */
  min_score?: number
}
