// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonizationLevel } from './CanonizationLevel'
import type { EntityType } from './EntityType'
import type { SaintCount } from './SaintCount'
import type { SaintDateDef } from './SaintDateDef'
import type { Sex } from './Sex'
import type { Title } from './Title'

/**
 * An entity with a guaranteed ID.
 *
 * This struct is used for entities that have been resolved from the resources,
 * where the ID is always present (e.g., in search results, liturgical days).
 */
export type Entity = {
  /**
   * The unique identifier of the entity (required)
   */
  id: string
  /**
   * The type of the entity.
   */
  type: EntityType
  /**
   * The full name of the entity.
   */
  fullname?: string
  /**
   * The short name of the entity, without the canonization level and titles.
   */
  name?: string
  /**
   * The canonization level of a person.
   */
  canonization_level?: CanonizationLevel
  /**
   * Date of Canonization.
   */
  date_of_canonization?: SaintDateDef
  /**
   * Specify whether an approximate indicator should be added for canonization date.
   */
  date_of_canonization_is_approximative?: boolean
  /**
   * Date of Beatification.
   */
  date_of_beatification?: SaintDateDef
  /**
   * Specify whether an approximate indicator should be added for beatification date.
   */
  date_of_beatification_is_approximative?: boolean
  /**
   * Specify if the canonization level should not be displayed.
   */
  hide_canonization_level?: boolean
  /**
   * Titles of the Saint or the Blessed.
   */
  titles?: Array<Title>
  /**
   * Determine if the Saint or the Blessed is a male or a female.
   */
  sex?: Sex
  /**
   * Specify if the titles should not be displayed.
   */
  hide_titles?: boolean
  /**
   * Date of Dedication of a place of worship.
   */
  date_of_dedication?: SaintDateDef
  /**
   * Date of Birth.
   */
  date_of_birth?: SaintDateDef
  /**
   * Specify whether an approximate indicator should be added for birth date.
   */
  date_of_birth_is_approximative?: boolean
  /**
   * Date of Death.
   */
  date_of_death?: SaintDateDef
  /**
   * Specify whether an approximate indicator should be added for death date.
   */
  date_of_death_is_approximative?: boolean
  /**
   * Number of persons that this definition represents.
   */
  count?: SaintCount
  /**
   * Sources for the information about this entity.
   */
  sources?: Array<string>
}
