// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonizationLevel } from './CanonizationLevel'
import type { EntityType } from './EntityType'
import type { SaintCount } from './SaintCount'
import type { SaintDateDef } from './SaintDateDef'
import type { Sex } from './Sex'
import type { Title } from './Title'

export type Entity = {
  /**
   * The unique identifier of the entity
   */
  id: string | null
  /**
   * The type of the entity.
   *
   * Defaults to `EntityType::Person`.
   */
  type: EntityType | null
  /**
   * The full name of the entity.
   */
  fullname: string | null
  /**
   * The short name of the entity, without the canonization level and titles.
   */
  name: string | null
  /**
   * The canonization level of a person.
   */
  canonization_level: CanonizationLevel | null
  /**
   * Date of Canonization, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_canonization: SaintDateDef | null
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_canonization_is_approximative: boolean | null
  /**
   * Date of Beatification, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_beatification: SaintDateDef | null
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_beatification_is_approximative: boolean | null
  /**
   * Specify if the canonization level should not be displayed.
   * It's generally the case when the canonization are already included in the name.
   */
  hide_canonization_level: boolean | null
  /**
   * Titles of the Saint or the Blessed
   */
  titles: Array<Title> | null
  /**
   * Determine if the Saint or the Blessed is a male or a female.
   */
  sex: Sex | null
  /**
   * Specify if the titles should not be displayed.
   * It's generally the case when titles are already included in the name.
   */
  hide_titles: boolean | null
  /**
   * Date of Dedication of a church, basilica, or cathedral (or other place of worship),
   * as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_dedication: SaintDateDef | null
  /**
   * Date of Birth, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_birth: SaintDateDef | null
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_birth_is_approximative: boolean | null
  /**
   * Date of Death, as a Number (year), a String (in 'YYYY-MM' or 'YYYY-MM-DD' format),
   * or an object describing date range, multiple possible date, or a century.
   */
  date_of_death: SaintDateDef | null
  /**
   * Specify whether an approximate indicator should be added, when the date is displayed.
   * For example in English: 'c. 201'.
   */
  date_of_death_is_approximative: boolean | null
  /**
   * Number of person that this definition represent.
   * It could be set as 'many' if the number is not defined.
   */
  count: SaintCount | null
  /**
   * Sources for the information about this entity
   */
  sources: Array<string> | null
  /**
   * Internal notes (not serialized).
   */
  _todo: Array<string> | null
}
