// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of entity in the liturgical calendar.
 * Defines whether the entity represents a person, place, or event.
 */
export type EntityType = "PERSON" | "PLACE" | "EVENT";
