// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityOverride } from "./EntityOverride";

/**
 * A reference to an entity in the entity catalog.
 * Can either reference an existing entity by ID or define a custom entity with additional properties.
 */
export type EntityRef = string | EntityOverride;
