// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from './Entity'
import type { MatchType } from './MatchType'

/**
 * Result of an entity search.
 */
export type EntitySearchResult = {
  /**
   * The matched entity.
   */
  entity: Entity
  /**
   * Match score from 0.0 to 1.0, where 1.0 is a perfect match.
   */
  score: number
  /**
   * Type of match that was found.
   */
  match_type: MatchType
  /**
   * Names of fields that matched the query.
   */
  matched_fields: Array<string>
}
