// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateDef } from "./DateDef";
import type { DayOfWeek } from "./DayOfWeek";

/**
 * Exception conditions that can trigger a date change.
 * Defines various conditions under which a date exception applies.
 */
export type ExceptionCondition = { 
/**
 * The start date of the range
 */
from: DateDef, 
/**
 * The end date of the range
 */
to: DateDef, 
/**
 * Whether the range is inclusive of the start date and the end date
 */
inclusive: boolean, } | { 
/**
 * The date to compare against
 */
date: DateDef, } | { 
/**
 * The day of the week to match
 */
day_of_week: DayOfWeek, };
