// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lent season localized names and descriptions.
 */
export type LentSeason = {
  /**
   * General season name for Lent
   */
  season: string | null
  /**
   * Weekday terminology during Lent
   */
  weekday: string | null
  /**
   * Sunday terminology during Lent
   */
  sunday: string | null
  /**
   * Day after Ash Wednesday terminology
   */
  day_after_ash_wed: string | null
  /**
   * Holy Week day terminology
   */
  holy_week_day: string | null
}
