// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical color names in the locale language.
 * Provides localized names for each liturgical color.
 */
export type LocaleColors = { 
/**
 * Black color name in the locale language
 */
black: string | null, 
/**
 * Gold color name in the locale language
 */
gold: string | null, 
/**
 * Green color name in the locale language
 */
green: string | null, 
/**
 * Purple color name in the locale language
 */
purple: string | null, 
/**
 * Red color name in the locale language
 */
red: string | null, 
/**
 * Rose color name in the locale language
 */
rose: string | null, 
/**
 * White color name in the locale language
 */
white: string | null, };
