// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MartyrologyEntryOverride } from './MartyrologyEntryOverride'

/**
 * A reference to an entry in the martyrology catalog.
 * Can either reference an existing entry by ID or define a custom entry with additional properties.
 */
export type MartyrologyRef = string | MartyrologyEntryOverride
