// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of entry in the Roman Martyrology.
 * Defines whether the entry represents a person, place, or event.
 */
export type MartyrologyEntryType = 'person' | 'place' | 'event'
