// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaintCount } from './SaintCount'
import type { TitlesDef } from './TitlesDef'

/**
 * Custom martyrology entry definition that extends or overrides properties from the martyrology catalog.
 * Used when a liturgical day needs specific entry properties that differ from the base entry.
 */
export type MartyrologyEntryOverride = {
  /**
   * The ID of the martyrology entry (must reference an existing entry in the catalog)
   */
  id: string
  /**
   * The custom titles for this entry in the context of this liturgical day
   */
  titles: TitlesDef | null
  /**
   * Whether to hide titles when displaying this entry (useful when titles are already included in the entry name)
   */
  hide_titles: boolean | null
  /**
   * The number of persons this entry represents (useful for groups of martyrs or saints)
   */
  count: SaintCount | null
}
