// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content of a mass for a specific liturgical cycle
 * Maps mass parts (readings, psalms, prayers, antiphons, etc.) to their texts
 */
export type MassContent = Record<string, string>
