// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Times of Mass celebrations in the liturgical calendar.
 * Different Masses are celebrated at various times and occasions throughout the liturgical year.
 */
export type MassTime =
  | 'EasterVigil'
  | 'PreviousEveningMass'
  | 'NightMass'
  | 'MassAtDawn'
  | 'MorningMass'
  | 'MassOfThePassion'
  | 'CelebrationOfThePassion'
  | 'DayMass'
  | 'ChrismMass'
  | 'EveningMassOfTheLordsSupper'
