// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiturgicalDay } from "./LiturgicalDay.js";
import type { CelebrationSummary } from "./CelebrationSummary";
import type { ColorInfo } from "./ColorInfo";
import type { CommonInfo } from "./CommonInfo";
import type { DayOfWeek } from "./DayOfWeek";
import type { Entity } from "./Entity";
import type { MassTime } from "./MassTime";
import type { PeriodInfo } from "./PeriodInfo";
import type { Precedence } from "./Precedence";
import type { PsalterWeekCycle } from "./PsalterWeekCycle";
import type { Rank } from "./Rank";
import type { Season } from "./Season";
import type { SundayCycle } from "./SundayCycle";
import type { TitlesDef } from "./TitlesDef";
import type { WeekdayCycle } from "./WeekdayCycle";

/**
 * A flat structure representing a single mass with its full liturgical context.
 *
 * This is the main type for the mass-centric calendar view. It contains:
 * - Mass identification (type, name, civil/liturgical dates)
 * - Day-level context (season, cycles, periods)
 * - Primary celebration data (flattened from LiturgicalDay)
 * - Optional alternative celebrations
 *
 * For evening masses (Easter Vigil, Previous Evening Mass), the `civil_date`
 * is shifted to the previous day while `liturgical_date` remains the original
 * liturgical celebration date.
 */
export type MassContext = { 
/**
 * The type of mass (e.g., DayMass, EasterVigil, etc.)
 * Serialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")
 */
mass_time: MassTime, 
/**
 * The localized name of the mass time (translation key in snake_case)
 */
mass_time_name: string, 
/**
 * The civil calendar date when this mass is celebrated (YYYY-MM-DD).
 * For evening masses (EasterVigil, PreviousEveningMass), this is the day
 * BEFORE the liturgical date.
 */
civil_date: string, 
/**
 * The liturgical date this mass belongs to (YYYY-MM-DD).
 * This is the "theological" date of the celebration.
 */
liturgical_date: string, 
/**
 * The liturgical season
 */
season: Season | null, 
/**
 * The localized season name
 */
season_name: string | null, 
/**
 * The Sunday cycle (Year A, B, or C)
 */
sunday_cycle: SundayCycle, 
/**
 * The localized Sunday cycle name
 */
sunday_cycle_name: string, 
/**
 * The weekday cycle (Year 1 or 2)
 */
weekday_cycle: WeekdayCycle, 
/**
 * The localized weekday cycle name
 */
weekday_cycle_name: string, 
/**
 * The psalter week cycle (Week 1-4)
 */
psalter_week: PsalterWeekCycle, 
/**
 * The localized psalter week name
 */
psalter_week_name: string, 
/**
 * The week number within the liturgical season
 */
week_of_season: number | null, 
/**
 * The day number within the liturgical season
 */
day_of_season: number | null, 
/**
 * The day of the week (0=Sunday to 6=Saturday)
 */
day_of_week: DayOfWeek, 
/**
 * The liturgical periods this day belongs to
 */
periods: Array<PeriodInfo>, 
/**
 * The first day of the current liturgical season
 */
start_of_season: string | null, 
/**
 * The last day of the current liturgical season
 */
end_of_season: string | null, 
/**
 * The first day of the liturgical year (first Sunday of Advent)
 */
start_of_liturgical_year: string, 
/**
 * The last day of the liturgical year
 */
end_of_liturgical_year: string, 
/**
 * The unique identifier of the liturgical day
 */
id: string, 
/**
 * The full name of the liturgical day
 */
fullname: string, 
/**
 * The liturgical precedence
 */
precedence: Precedence, 
/**
 * The liturgical rank
 */
rank: Rank, 
/**
 * The localized liturgical rank name
 */
rank_name: string, 
/**
 * The liturgical colors
 */
colors: Array<ColorInfo>, 
/**
 * The common prayers/readings used
 */
commons: Array<CommonInfo>, 
/**
 * The entities (Saints, Blessed, or Places) linked to this day
 */
entities: Array<Entity>, 
/**
 * The titles for this liturgical day
 */
titles: TitlesDef, 
/**
 * Whether this is a holy day of obligation
 */
is_holy_day_of_obligation: boolean, 
/**
 * Whether this liturgical day is optional
 */
is_optional: boolean, 
/**
 * The ID of the calendar where this liturgical day is defined
 */
from_calendar_id: string, 
/**
 * Optional alternative celebrations (e.g., optional memorials)
 * that can be celebrated instead of the primary celebration.
 */
optional_celebrations: Array<CelebrationSummary>, };
