// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiturgicalCycle } from './LiturgicalCycle.js'
import type { MassContent } from './MassContent.js'

/**
 * Mass contents for a specific mass time, organized by liturgical cycle
 */
export type MassCycleDefinition = Record<LiturgicalCycle, MassContent>
