// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassTime } from "./MassTime.js";
import type { MassCycleDefinition } from "./MassCycleDefinition.js";

/**
 * All mass definitions for a liturgical day
 */
export type MassesDefinitions = Record<MassTime, MassCycleDefinition>;
