// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassTime } from './MassTime'

/**
 * Information about a mass celebration for a liturgical day.
 * Contains the type of mass and its localized name.
 */
export type MassInfo = {
  /**
   * The type of mass (e.g., DayMass, EasterVigil, etc.)
   * Serialized as SCREAMING_SNAKE_CASE (e.g., "DAY_MASS")
   */
  mass_type: MassTime
  /**
   * The localized name of the mass type (translation key in snake_case)
   */
  name: string
}
