// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Times of Mass celebrations in the liturgical calendar.
 * Different Masses are celebrated at various times and occasions throughout the liturgical year.
 */
export type MassTime =
  | 'EASTER_VIGIL'
  | 'PREVIOUS_EVENING_MASS'
  | 'NIGHT_MASS'
  | 'MASS_AT_DAWN'
  | 'MORNING_MASS'
  | 'MASS_OF_THE_PASSION'
  | 'CELEBRATION_OF_THE_PASSION'
  | 'DAY_MASS'
  | 'CHRISM_MASS'
  | 'EVENING_MASS_OF_THE_LORDS_SUPPER'
