// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of match that was found for a search result.
 */
export type MatchType = 'exact_id' | 'fuzzy' | 'filter_only'
