// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Month index (1-12) with automatic validation
 *
 * This type ensures that only valid month values are accepted during
 * deserialization. The value 1 represents January, 2 represents February, etc.
 */
export type MonthIndex = number
