// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ordinary Time season localized names and descriptions.
 */
export type OrdinaryTimeSeason = { 
/**
 * General season name for Ordinary Time
 */
season: string | null, 
/**
 * Weekday terminology during Ordinary Time
 */
weekday: string | null, 
/**
 * Sunday terminology during Ordinary Time
 */
sunday: string | null, };
