// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format for displaying ordinal numbers.
 *
 * - `Letters`: Display ordinals as words (e.g., "first", "second", "premier", "deuxième")
 * - `Numeric`: Display ordinals as numbers with suffixes (e.g., "1st", "2nd", "1er", "2e")
 */
export type OrdinalFormat = 'letters' | 'numeric'
