// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInfo } from './ColorInfo'
import type { CommonDefinition } from './CommonDefinition'
import type { DateDef } from './DateDef'
import type { DateDefException } from './DateDefException'
import type { Precedence } from './Precedence'
import type { Rank } from './Rank'
import type { TitlesDef } from './TitlesDef'

/**
 * Represents the differences between a liturgical day definition and its parent definition.
 * This is a lightweight structure that only contains fields that can be overridden.
 */
export type ParentOverride = {
  /**
   * The ID of the calendar from which this override originates
   */
  from_calendar_id: string
  /**
   * The date definition if it was changed
   */
  date_def: DateDef | null
  /**
   * The date exceptions if they were changed
   */
  date_exceptions: Array<DateDefException> | null
  /**
   * The precedence if it was changed
   */
  precedence: Precedence | null
  /**
   * The rank if it was changed
   */
  rank: Rank | null
  /**
   * The colors if they were changed
   */
  colors: Array<ColorInfo> | null
  /**
   * The titles if they were changed
   */
  titles: TitlesDef | null
  /**
   * The commons definition if it was changed
   */
  commons_def: Array<CommonDefinition> | null
  /**
   * The is_holy_day_of_obligation flag if it was changed
   */
  is_holy_day_of_obligation: boolean | null
  /**
   * The is_optional flag if it was changed
   */
  is_optional: boolean | null
  /**
   * The allow_similar_rank_items flag if it was changed
   */
  allow_similar_rank_items: boolean | null
}
