// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EasterCalculationType } from "./EasterCalculationType";

/**
 * Configuration options for "particular" (local/diocesan) calendars.
 *
 * In liturgical terminology, a "particular" calendar is one that applies to a specific
 * region, diocese, or religious community, as opposed to the General Roman Calendar
 * which applies universally.
 *
 * These settings can override or extend the default Romcal configuration or any parent
 * calendar configuration.
 */
export type ParticularConfig = { 
/**
 * Epiphany is celebrated on a Sunday
 */
epiphany_on_sunday: boolean | null, 
/**
 * Ascension is celebrated on a Sunday
 */
ascension_on_sunday: boolean | null, 
/**
 * Corpus Christi is celebrated on a Sunday
 */
corpus_christi_on_sunday: boolean | null, 
/**
 * The type of Easter calculation
 */
easter_calculation_type: EasterCalculationType | null, };
