// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paschal Triduum season localized names and descriptions.
 */
export type PaschalTriduumSeason = {
  /**
   * General season name for Paschal Triduum
   */
  season: string | null
}
