// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical period names in the locale language.
 */
export type PeriodsMetadata = { 
/**
 * Christmas Octave period name
 */
christmas_octave: string | null, 
/**
 * Days before Epiphany period name
 */
days_before_epiphany: string | null, 
/**
 * Days from Epiphany period name
 */
days_from_epiphany: string | null, 
/**
 * Christmas to Presentation of the Lord period name
 */
christmas_to_presentation_of_the_lord: string | null, 
/**
 * Presentation of the Lord to Holy Thursday period name
 */
presentation_of_the_lord_to_holy_thursday: string | null, 
/**
 * Holy Week period name
 */
holy_week: string | null, 
/**
 * Paschal Triduum period name
 */
paschal_triduum: string | null, 
/**
 * Easter Octave period name
 */
easter_octave: string | null, 
/**
 * Early Ordinary Time period name
 */
early_ordinary_time: string | null, 
/**
 * Late Ordinary Time period name
 */
late_ordinary_time: string | null, };
