// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specific periods within liturgical seasons.
 * Defines sub-periods that have special liturgical characteristics or rules.
 */
export type Period =
  | 'christmas_octave'
  | 'days_before_epiphany'
  | 'days_from_epiphany'
  | 'christmas_to_presentation_of_the_lord'
  | 'presentation_of_the_lord_to_holy_thursday'
  | 'holy_week'
  | 'paschal_triduum'
  | 'easter_octave'
  | 'early_ordinary_time'
  | 'late_ordinary_time'
