// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Period } from "./Period";

/**
 * Liturgical period information with localized name.
 */
export type PeriodInfo = { 
/**
 * The period key
 */
key: Period, 
/**
 * The localized name of the period
 */
name: string, };
