// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Specific periods within liturgical seasons.
 * Defines sub-periods that have special liturgical characteristics or rules.
 */
export type Period =
  | 'CHRISTMAS_OCTAVE'
  | 'DAYS_BEFORE_EPIPHANY'
  | 'DAYS_FROM_EPIPHANY'
  | 'CHRISTMAS_TO_PRESENTATION_OF_THE_LORD'
  | 'PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY'
  | 'HOLY_WEEK'
  | 'PASCHAL_TRIDUUM'
  | 'EASTER_OCTAVE'
  | 'EARLY_ORDINARY_TIME'
  | 'LATE_ORDINARY_TIME'
