// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical precedence levels for determining which celebration takes priority.
 * Defines the hierarchical order of liturgical celebrations according to UNLY norms.
 */
export type Precedence =
  | 'triduum_1'
  | 'proper_of_time_solemnity_2'
  | 'privileged_sunday_2'
  | 'ash_wednesday_2'
  | 'weekday_of_holy_week_2'
  | 'weekday_of_easter_octave_2'
  | 'general_solemnity_3'
  | 'commemoration_of_all_the_faithful_departed_3'
  | 'proper_solemnity__principal_patron_4a'
  | 'proper_solemnity__dedication_of_the_own_church_4b'
  | 'proper_solemnity__title_of_the_own_church_4c'
  | 'proper_solemnity__title_or_founder_or_primary_patron_of_a_religious_org_4d'
  | 'general_lord_feast_5'
  | 'unprivileged_sunday_6'
  | 'general_feast_7'
  | 'proper_feast__principal_patron_of_a_diocese_8a'
  | 'proper_feast__dedication_of_the_cathedral_church_8b'
  | 'proper_feast__principal_patron_of_a_region_8c'
  | 'proper_feast__title_or_founder_or_primary_patron_of_a_religious_org_8d'
  | 'proper_feast__to_an_individual_church_8e'
  | 'proper_feast_8f'
  | 'privileged_weekday_9'
  | 'general_memorial_10'
  | 'proper_memorial__second_patron_11a'
  | 'proper_memorial_11b'
  | 'optional_memorial_12'
  | 'weekday_13'
