// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [GILH §133] The four-week cycle of the psalter is coordinated with the liturgical year in such a way that
 * on the First Sunday of Advent, the First Sunday in Ordinary Time, the First Sunday of Lent,
 * and Easter Sunday the cycle is always begun again with Week 1 (others being omitted when necessary).
 */
export type PsalterWeekCycle = 'week_1' | 'week_2' | 'week_3' | 'week_4'
