// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical rank names in the locale language.
 */
export type RanksMetadata = {
  /**
   * Solemnity rank name
   */
  solemnity: string | null
  /**
   * Sunday rank name
   */
  sunday: string | null
  /**
   * Feast rank name
   */
  feast: string | null
  /**
   * Memorial rank name
   */
  memorial: string | null
  /**
   * Optional memorial rank name
   */
  optional_memorial: string | null
  /**
   * Weekday rank name
   */
  weekday: string | null
}
