// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Liturgical rank indicating the importance and celebration style of a liturgical day
 */
export type Rank = 'solemnity' | 'sunday' | 'feast' | 'memorial' | 'optional_memorial' | 'weekday'
