// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CyclesMetadata } from "./CyclesMetadata";
import type { LocaleColors } from "./LocaleColors";
import type { OrdinalFormat } from "./OrdinalFormat";
import type { PeriodsMetadata } from "./PeriodsMetadata";
import type { RanksMetadata } from "./RanksMetadata";
import type { SeasonsMetadata } from "./SeasonsMetadata";

/**
 * Metadata for localized resources.
 * Contains all the localized strings and configurations for a specific locale.
 */
export type ResourcesMetadata = { 
/**
 * Format for displaying ordinal numbers (defaults to Numeric if not specified)
 */
ordinal_format: OrdinalFormat | null, 
/**
 * Ordinal numbers as words (first, second, third, etc.) in the locale language
 */
ordinals_letters: { [key in string]?: string } | null, 
/**
 * Ordinal numbers as numeric with suffix (1st, 2nd, 3rd, etc.) in the locale language
 */
ordinals_numeric: { [key in string]?: string } | null, 
/**
 * Weekday names (Sunday, Monday, etc.) in the locale language
 */
weekdays: { [key in string]?: string } | null, 
/**
 * Month names (January, February, etc.) in the locale language
 */
months: { [key in string]?: string } | null, 
/**
 * Liturgical color names in the locale language
 */
colors: LocaleColors | null, 
/**
 * Liturgical season names and descriptions in the locale language
 */
seasons: SeasonsMetadata | null, 
/**
 * Liturgical period names in the locale language
 */
periods: PeriodsMetadata | null, 
/**
 * Liturgical rank names in the locale language
 */
ranks: RanksMetadata | null, 
/**
 * Liturgical cycle names in the locale language
 */
cycles: CyclesMetadata | null, };
