// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";
import type { ResourcesMetadata } from "./ResourcesMetadata";

/**
 * Resources definition
 */
export type Resources = { $schema: string | null, 
/**
 * Locale code of the resources, in BCP-47 IETF tag format
 */
locale: string, 
/**
 * Metadata of the resources
 */
metadata: ResourcesMetadata | null, 
/**
 * Entities of the resources: a person, a place, an event, etc.
 */
entities: { [key in string]?: Entity } | null, };
