// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Saint date representation with different precision levels.
 * Supports year-only, year-month, or full date specifications.
 */
export type SaintDate = number | string | string
