// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaintDate } from "./SaintDate";

/**
 * Saint date definition supporting various date specifications.
 * Allows single dates, date ranges, multiple alternatives, or century specifications.
 */
export type SaintDateDef = SaintDate | { 
/**
 * The date range (start and end dates)
 */
between: [SaintDate, SaintDate], } | { 
/**
 * The list of alternative dates
 */
or: Array<SaintDate>, } | { 
/**
 * The century number
 */
century: number, };
