// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the number of saints for an entry or a group of entries.
 *
 * Can be either a specific number (u32) or "many" to indicate
 * an indeterminate number of saints.
 *
 * # Serialization
 * - `Number(n)` serializes as integer `n`
 * - `Many` serializes as string `"many"`
 *
 * # Deserialization
 * - Integers are converted to `Number(u32)`
 * - String `"many"` is converted to `Many`
 * - All other types generate an error
 */
export type SaintCount = { Number: number } | { Many: string }
