// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Combined Sunday cycle for cases where readings can apply to multiple years.
 * This allows for flexible configuration where the same readings can be used
 * across different combinations of Sunday cycles.
 */
export type SundayCycleCombined = 'year_a_b' | 'year_a_c' | 'year_b_c'
