// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A three-year cycle for Sunday Mass readings (and some solemnities), designated by A, B, or C.
 * Each cycle begins on the First Sunday of Advent of the previous civil year and ends on Saturday
 * after the Christ the King Solemnity. The cycles follow each other in alphabetical order.
 * C year is always divisible by 3, A has remainder of 1, and B remainder of 2.
 */
export type SundayCycle = 'year_a' | 'year_b' | 'year_c'
