// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompoundTitle } from "./CompoundTitle";
import type { Title } from "./Title";

/**
 * Title definition that can be either a simple list or a compound definition.
 * Supports both direct title lists and compound title operations.
 */
export type TitlesDef = Array<Title> | CompoundTitle;
